export type Pair = [ar: string, en: string];
export type DemoRow = [icon: string, title: Pair, meta: Pair, status: Pair];

export type ContextDemo = {
  brand: Pair;
  headline: Pair;
  description: Pair;
  action: Pair;
  result: Pair;
  client: { label: Pair; title: Pair; rows: DemoRow[] };
  admin: { label: Pair; title: Pair; rows: DemoRow[] };
  stats: Array<[value: string, label: Pair]>;
  flow: Pair[];
  tone: "cyan" | "amber" | "violet" | "green";
};

const services: Record<string, ContextDemo> = {
  websites: {
    brand: ["مدى للأعمال", "Mada Business"],
    headline: ["موقع شركة يشرح الخدمة ويجمع الطلبات", "A company site that explains the offer and captures enquiries"],
    description: ["صفحة رئيسية، وصفحات خدمات، وعناصر تعزز الثقة، ونموذج طلب واحد.", "Homepage, services, trust signals and one focused enquiry form."],
    action: ["جرّب إرسال طلب", "Try an enquiry"], result: ["تم تجهيز طلب تجريبي للمتابعة", "Demo enquiry prepared for follow-up"],
    client: { label: ["واجهة الموقع", "Website view"], title: ["ما يراه الزائر", "Visitor experience"], rows: [["⌂", ["صفحة رئيسية مقنعة", "Focused homepage"], ["عرض القيمة خلال ثوانٍ", "Value explained in seconds"], ["جاهزة", "Ready"]], ["▦", ["صفحات خدمات مستقلة", "Dedicated service pages"], ["تفاصيل وفوائد وأسئلة شائعة", "Details, value and FAQs"], ["منظمة", "Structured"]], ["✉", ["نموذج طلب مختصر", "Short enquiry form"], ["الاسم ووسيلة التواصل", "Name and preferred contact"], ["آمن", "Protected"]]] },
    admin: { label: ["صندوق الطلبات", "Enquiry inbox"], title: ["ما يراه صاحب العمل", "Business view"], rows: [["01", ["طلب موقع شركة", "Company website enquiry"], ["بغداد • وصل اليوم", "Baghdad • today"], ["جديد", "New"]], ["02", ["تحديث متجر موجود", "Store refresh"], ["أربيل • بانتظار الرد", "Erbil • awaiting reply"], ["متابعة", "Follow-up"]], ["03", ["صفحة هبوط لحملة", "Campaign landing page"], ["البصرة • نطاق واضح", "Basra • scope clear"], ["مؤهل", "Qualified"]]] },
    stats: [["2", ["لغتان", "languages"]], ["06", ["صفحات أساسية", "core pages"]], ["24/7", ["استقبال طلبات", "enquiry access"]]], flow: [["يدخل الزائر", "Visitor arrives"], ["يفهم العرض", "Understands offer"], ["يرسل الطلب", "Sends enquiry"]], tone: "cyan",
  },
  "web-apps": {
    brand: ["بوابة الخدمة", "Service Portal"], headline: ["تطبيق ويب لرحلة مستخدم كاملة", "A web app for a complete user journey"], description: ["حساب مستخدم وطلب خدمة ومتابعة حالة وإشعارات.", "Account, service request, status tracking and notifications."], action: ["أنشئ طلبًا تجريبيًا", "Create a demo request"], result: ["أُنشئ الطلب وانتقل إلى المراجعة", "Request created and moved to review"],
    client: { label: ["تطبيق المستخدم", "User app"], title: ["رحلة المستخدم", "User journey"], rows: [["＋", ["طلب خدمة جديد", "New service request"], ["خطوات قصيرة وواضحة", "Short guided steps"], ["ابدأ", "Start"]], ["◉", ["متابعة الطلب", "Track request"], ["آخر تحديث قبل 8 دقائق", "Updated 8 minutes ago"], ["قيد العمل", "In progress"]], ["✦", ["الإشعارات", "Notifications"], ["تنبيه عند كل تغيير", "Alert on each change"], ["مفعلة", "Active"]]] },
    admin: { label: ["لوحة المشرف", "Admin dashboard"], title: ["إدارة العمليات", "Operations control"], rows: [["A", ["طلبات تحتاج مراجعة", "Requests to review"], ["6 طلبات حسب الأولوية", "6 requests by priority"], ["06", "06"]], ["B", ["مهام الفريق", "Team workload"], ["12 مهمة موزعة", "12 assigned tasks"], ["متوازن", "Balanced"]], ["C", ["نشاط النظام", "System activity"], ["سجل واضح للتغييرات", "Clear change log"], ["مباشر", "Live"]]] },
    stats: [["128", ["مستخدمًا تجريبيًا", "demo users"]], ["18", ["طلبًا نشطًا", "active requests"]], ["04", ["صلاحيات", "roles"]]], flow: [["ينشئ حسابًا", "Creates account"], ["يرسل الطلب", "Submits request"], ["يتابع الحالة", "Tracks status"]], tone: "violet",
  },
  commerce: {
    brand: ["سوق دجلة", "Tigris Market"], headline: ["متجر وطلبات مصممة لطريقة البيع المحلية", "Commerce designed around local selling workflows"], description: ["كتالوج وسلة وتوصيل ومتابعة طلب بلا تعقيد.", "Catalogue, cart, delivery and order tracking without friction."], action: ["أضف طلبًا تجريبيًا", "Add a demo order"], result: ["أُضيف الطلب إلى قائمة التجهيز", "Demo order added to the packing queue"],
    client: { label: ["واجهة المتجر", "Storefront"], title: ["منتجات مقترحة", "Featured products"], rows: [["◇", ["سلة تمور فاخرة", "Premium date basket"], ["متوفر • 28,000 د.ع", "Available • IQD 28,000"], ["أضف", "Add"]], ["□", ["قهوة عراقية", "Iraqi coffee"], ["متوفر • 12,000 د.ع", "Available • IQD 12,000"], ["أضف", "Add"]], ["△", ["باقة هدية", "Gift bundle"], ["كمية محدودة • 35,000 د.ع", "Low stock • IQD 35,000"], ["أضف", "Add"]]] },
    admin: { label: ["إدارة الطلبات", "Order management"], title: ["قائمة التجهيز", "Packing queue"], rows: [["#", ["طلب #1042", "Order #1042"], ["الكرادة • توصيل", "Karrada • delivery"], ["للتجهيز", "To pack"]], ["#", ["طلب #1041", "Order #1041"], ["المنصور • استلام", "Mansour • pickup"], ["مؤكد", "Confirmed"]], ["#", ["طلب #1040", "Order #1040"], ["زيونة • توصيل", "Zayouna • delivery"], ["في الطريق", "On route"]]] },
    stats: [["48", ["منتجًا", "products"]], ["12", ["طلبًا اليوم", "orders today"]], ["3", ["مناطق توصيل", "delivery zones"]]], flow: [["يختار المنتج", "Selects product"], ["يؤكد التفاصيل", "Confirms details"], ["يتابع الطلب", "Tracks order"]], tone: "amber",
  },
  "management-systems": {
    brand: ["نظام المدار", "Madar OS"], headline: ["لوحة تشغيل تجمع العمل في مكان واحد", "An operations dashboard that brings work together"], description: ["العملاء والمهام والملفات والمؤشرات حسب صلاحيات الفريق.", "Customers, tasks, files and indicators with team permissions."], action: ["أضف مهمة تجريبية", "Add a demo task"], result: ["أُضيفت المهمة وأُسندت إلى الفريق", "Task added and assigned to the team"],
    client: { label: ["ملخص الإدارة", "Management summary"], title: ["نظرة عامة", "Overview"], rows: [["▦", ["مشروع فرع بغداد", "Baghdad branch project"], ["المرحلة الثالثة من خمس", "Stage three of five"], ["يسير جيدًا", "On track"]], ["◫", ["طلبات الموافقة", "Approval requests"], ["3 عناصر تحتاج قرارًا", "3 items need a decision"], ["مراجعة", "Review"]], ["↗", ["التقرير الأسبوعي", "Weekly report"], ["تم تحديثه اليوم", "Updated today"], ["جاهز", "Ready"]]] },
    admin: { label: ["عمل الفريق", "Team workspace"], title: ["المهام المفتوحة", "Open tasks"], rows: [["01", ["مراجعة عرض السعر", "Review quotation"], ["مسندة إلى سارة", "Assigned to Sara"], ["اليوم", "Today"]], ["02", ["رفع مخطط الإصدار", "Upload revision plan"], ["مسندة إلى أحمد", "Assigned to Ahmed"], ["غدًا", "Tomorrow"]], ["03", ["تأكيد استلام المواد", "Confirm materials receipt"], ["مسندة إلى علي", "Assigned to Ali"], ["مفتوحة", "Open"]]] },
    stats: [["34", ["مهمة نشطة", "active tasks"]], ["09", ["مشاريع", "projects"]], ["92%", ["اكتمال البيانات", "data complete"]]], flow: [["تُسجَّل المعلومة", "Record information"], ["تُسنَد المسؤولية", "Assign ownership"], ["تظهر النتيجة", "See outcome"]], tone: "green",
  },
  "booking-crm": {
    brand: ["موعد ومتابعة", "Book & Follow"], headline: ["نظام حجز ومتابعة لا يُضيّع موعدًا أو فرصة", "Booking and CRM that misses no appointment or lead"], description: ["تقويم مركزي، وملف للعميل، ومراحل متابعة قابلة للقياس.", "Central calendar, customer profile and measurable follow-up stages."], action: ["احجز موعدًا تجريبيًا", "Book a demo slot"], result: ["تم حجز الموعد وإضافته إلى المتابعة", "Appointment booked and added to follow-up"],
    client: { label: ["صفحة الحجز", "Booking page"], title: ["المواعيد المتاحة", "Available slots"], rows: [["09", ["الأحد 09:30", "Sunday 09:30"], ["استشارة أولية • 30 دقيقة", "Initial consult • 30 min"], ["متاح", "Available"]], ["11", ["الأحد 11:00", "Sunday 11:00"], ["اجتماع مشروع • 45 دقيقة", "Project meeting • 45 min"], ["متاح", "Available"]], ["02", ["الاثنين 14:00", "Monday 14:00"], ["متابعة • 20 دقيقة", "Follow-up • 20 min"], ["متاح", "Available"]]] },
    admin: { label: ["خط المتابعة", "Follow-up pipeline"], title: ["العملاء اليوم", "Today's customers"], rows: [["م", ["مريم خالد", "Maryam Khalid"], ["09:30 • استشارة", "09:30 • consultation"], ["مؤكد", "Confirmed"]], ["ع", ["علي حسن", "Ali Hassan"], ["11:00 • مشروع جديد", "11:00 • new project"], ["يحتاج ردًا", "Needs reply"]], ["س", ["سارة كريم", "Sara Kareem"], ["14:00 • متابعة", "14:00 • follow-up"], ["تم التذكير", "Reminded"]]] },
    stats: [["08", ["مواعيد اليوم", "today's bookings"]], ["03", ["فرص متابعة", "follow-ups"]], ["0", ["تداخلات", "conflicts"]]], flow: [["يختار الموعد", "Selects time"], ["يصل التأكيد", "Gets confirmation"], ["تبدأ المتابعة", "Follow-up starts"]], tone: "cyan",
  },
  automation: {
    brand: ["مسار آلي", "AutoFlow"], headline: ["مسار يُحرّك البيانات بدلًا من نسخها يدويًا", "A workflow that moves data without manual copying"], description: ["من النموذج إلى المسؤول ونظام CRM والتقرير، وفق قواعد واضحة.", "From form to owner, CRM and report through clear rules."], action: ["شغّل المسار التجريبي", "Run demo workflow"], result: ["اكتملت أربع خطوات آلية خلال ثانيتين", "Four automated steps completed in two seconds"],
    client: { label: ["بداية المسار", "Workflow input"], title: ["طلب جديد", "New request"], rows: [["①", ["استقبال النموذج", "Capture form"], ["التحقق من الحقول", "Validate fields"], ["جاهز", "Ready"]], ["②", ["تصنيف الطلب", "Classify request"], ["حسب الخدمة والمحافظة", "By service and governorate"], ["تلقائي", "Automatic"]], ["③", ["توجيه المسؤول", "Assign owner"], ["إنشاء مهمة وتنبيه", "Create task and notify"], ["تلقائي", "Automatic"]]] },
    admin: { label: ["سجل التنفيذ", "Execution log"], title: ["آخر عمليات التشغيل", "Recent workflow runs"], rows: [["✓", ["تم إنشاء سجل CRM", "CRM record created"], ["طلب تجريبي #204", "Demo request #204"], ["نجح", "Passed"]], ["✓", ["تم إشعار المسؤول", "Owner notified"], ["فريق المبيعات", "Sales team"], ["نجح", "Passed"]], ["✓", ["تم تحديث التقرير", "Report updated"], ["لوحة اليوم", "Today's dashboard"], ["نجح", "Passed"]]] },
    stats: [["4", ["خطوات آلية", "automated steps"]], ["2s", ["وقت التنفيذ", "run time"]], ["0", ["عمليات نقل يدوية", "manual copies"]]], flow: [["الاستقبال", "Capture"], ["التحقق والتصنيف", "Validate & classify"], ["التنفيذ والإشعار", "Act & notify"]], tone: "violet",
  },
  "performance-care": {
    brand: ["فحص المنصة", "Platform Check"], headline: ["لوحة فحص للأداء والحماية والصيانة", "A health dashboard for performance, security and maintenance"], description: ["ما المشكلة وما أثرها وما الذي يُصلح أولًا.", "What is wrong, why it matters and what to fix first."], action: ["شغّل فحصًا تجريبيًا", "Run demo audit"], result: ["اكتمل الفحص: 3 تحسينات ذات أولوية", "Audit complete: three priority improvements"],
    client: { label: ["نتيجة الفحص", "Audit result"], title: ["صحة الموقع", "Site health"], rows: [["↯", ["سرعة الصفحة الرئيسية", "Homepage speed"], ["زمن عرض المحتوى الأساسي", "Main content render time"], ["1.4 ثانية", "1.4 sec"]], ["⌾", ["الروابط والفهرسة", "Links and indexing"], ["لا توجد روابط مكسورة", "No broken links"], ["سليم", "Healthy"]], ["▣", ["النسخ الاحتياطي", "Backups"], ["نسخة أسبوعية مشفرة", "Encrypted weekly copy"], ["نشط", "Active"]]] },
    admin: { label: ["خطة التحسين", "Improvement plan"], title: ["الإجراءات المقترحة", "Recommended actions"], rows: [["01", ["ضغط الصور", "Compress images"], ["أثر مرتفع • جهد منخفض", "High impact • low effort"], ["أولوية", "Priority"]], ["02", ["تحديث الحزم", "Update packages"], ["أثر أمني", "Security impact"], ["مجدول", "Scheduled"]], ["03", ["مراقبة التوفر", "Uptime monitoring"], ["تنبيه عند الانقطاع", "Alert on downtime"], ["مقترح", "Proposed"]]] },
    stats: [["92", ["درجة الأداء", "performance score"]], ["A", ["أساسيات الأمان", "security baseline"]], ["7d", ["آخر نسخة", "latest backup"]]], flow: [["نفحص", "Audit"], ["نرتب الأولويات", "Prioritise"], ["نُنفّذ ونراقب", "Improve & monitor"]], tone: "green",
  },
};

type SectorDemoSeed = {
  brand: Pair;
  headline: Pair;
  description: Pair;
  action: Pair;
  result: Pair;
  clientLabel: Pair;
  clientTitle: Pair;
  clientRows: DemoRow[];
  adminLabel: Pair;
  adminTitle: Pair;
  adminRows: DemoRow[];
  stats: ContextDemo["stats"];
  flow: Pair[];
  tone: ContextDemo["tone"];
};

const sectorDemo = (seed: SectorDemoSeed): ContextDemo => ({
  brand: seed.brand,
  headline: seed.headline,
  description: seed.description,
  action: seed.action,
  result: seed.result,
  client: { label: seed.clientLabel, title: seed.clientTitle, rows: seed.clientRows },
  admin: { label: seed.adminLabel, title: seed.adminTitle, rows: seed.adminRows },
  stats: seed.stats,
  flow: seed.flow,
  tone: seed.tone,
});

const expandedIndustryDemos: Record<string, ContextDemo> = {
  "law-firms": sectorDemo({
    brand: ["ميزان للمحاماة", "Mizan Law"], headline: ["مكتب قانوني يستقبل الاستشارة وينظّم الملف بسرية", "A legal practice that captures enquiries and organises matters privately"], description: ["نوع الاستشارة والموعد وقائمة المستندات وحالة الملف في مساحة مهنية واحدة.", "Consultation type, appointment, document checklist and matter status in one professional space."], action: ["أرسل طلب استشارة تجريبيًا", "Send a demo consultation request"], result: ["أُنشئ ملف استشارة خيالي وحُدّد موعد المراجعة", "Fictional consultation file created and review scheduled"],
    clientLabel: ["بوابة الموكل", "Client portal"], clientTitle: ["طلب استشارة أولية", "Initial consultation request"], clientRows: [["§", ["استشارة شركات", "Corporate consultation"], ["تأسيس وعقود تجارية", "Formation and commercial contracts"], ["اختر", "Select"]], ["⌘", ["نزاع مدني", "Civil matter"], ["مراجعة أولية للمستندات", "Initial document review"], ["اختر", "Select"]], ["◷", ["موعد استشارة", "Consultation slot"], ["الثلاثاء • 11:30", "Tuesday • 11:30"], ["متاح", "Available"]]],
    adminLabel: ["إدارة الملفات", "Matter management"], adminTitle: ["ملفات تحتاج متابعة", "Matters requiring follow-up"], adminRows: [["L1", ["ملف #L-204", "Matter #L-204"], ["قائمة المستندات مكتملة", "Document list complete"], ["مراجعة", "Review"]], ["L2", ["موعد استشارة", "Consultation appointment"], ["اليوم • 14:00", "Today • 14:00"], ["مؤكد", "Confirmed"]], ["L3", ["مهلة إجرائية", "Procedural deadline"], ["بعد 4 أيام", "In 4 days"], ["تنبيه", "Alert"]]],
    stats: [["12", ["ملفًا نشطًا", "active matters"]], ["04", ["مواعيد اليوم", "appointments today"]], ["03", ["تنبيهات", "alerts"]]], flow: [["يصف الطلب", "Describe request"], ["يضيف المستندات", "Add documents"], ["يُحدّد الموعد", "Schedule meeting"]], tone: "violet",
  }),
  "private-schools": sectorDemo({
    brand: ["مدارس الرافدين", "Rafidain Schools"], headline: ["تسجيل مدرسي وبوابة تجمع الإدارة وولي الأمر", "Admissions and a portal connecting school and parent"], description: ["طلب تسجيل وجدول وحضور وأقساط وإعلانات بحسب الصف.", "Admissions, timetable, attendance, fees and class-based announcements."], action: ["أرسل طلب تسجيل تجريبيًا", "Send a demo admission"], result: ["أُضيف طلب التسجيل الخيالي إلى مراجعة الصف الرابع", "Fictional admission added to grade-four review"],
    clientLabel: ["بوابة ولي الأمر", "Parent portal"], clientTitle: ["يوم الطالب", "Student day"], clientRows: [["▤", ["الجدول الدراسي", "Class timetable"], ["العربية • الرياضيات • العلوم", "Arabic • maths • science"], ["اليوم", "Today"]], ["✓", ["الحضور", "Attendance"], ["حاضر منذ 07:42", "Present since 07:42"], ["مؤكد", "Confirmed"]], ["$", ["القسط القادم", "Next fee"], ["يستحق في 25 آب", "Due 25 Aug"], ["قادم", "Upcoming"]]],
    adminLabel: ["إدارة المدرسة", "School office"], adminTitle: ["طلبات التسجيل", "Admission applications"], adminRows: [["4A", ["طلب الصف الرابع", "Grade four application"], ["البيانات الأساسية مكتملة", "Core data complete"], ["مراجعة", "Review"]], ["1B", ["طلب الصف الأول", "Grade one application"], ["يحتاج وثيقة واحدة", "Needs one document"], ["ناقص", "Incomplete"]], ["6A", ["مقاعد الصف السادس", "Grade six places"], ["تبقى 8 مقاعد", "8 places remain"], ["متاح", "Available"]]],
    stats: [["418", ["طالبًا تجريبيًا", "demo students"]], ["96%", ["حضور اليوم", "attendance today"]], ["08", ["طلبات جديدة", "new applications"]]], flow: [["يُكمل الطلب", "Complete application"], ["تراجعه الإدارة", "Office review"], ["يصل القرار", "Receive decision"]], tone: "cyan",
  }),
  kindergartens: sectorDemo({
    brand: ["روضة غيمة", "Ghaima Nursery"], headline: ["يوم الطفل يصل إلى الأهل بصورة لطيفة ومنظمة", "A child’s day shared with parents in a warm organised way"], description: ["الأنشطة والوجبات والقيلولة وملاحظات المربية، دون استخدام بيانات أطفال حقيقية.", "Activities, meals, naps and educator notes, with no real children’s data."], action: ["أضف تحديثًا يوميًا تجريبيًا", "Add a demo daily update"], result: ["أُضيف تحديث خيالي عن نشاط الرسم", "Fictional painting activity update added"],
    clientLabel: ["ملخص اليوم", "Daily summary"], clientTitle: ["يوم مليء بالاكتشاف", "A day of discovery"], clientRows: [["☀", ["استقبال صباحي", "Morning welcome"], ["دخلت المجموعة عند 08:05", "Group arrived at 08:05"], ["تم", "Done"]], ["✿", ["نشاط الألوان", "Colour activity"], ["رسم وتعرّف إلى الأشكال", "Painting and shape discovery"], ["اليوم", "Today"]], ["☾", ["وقت الراحة", "Rest time"], ["13:00 — 14:00", "13:00 — 14:00"], ["قادم", "Upcoming"]]],
    adminLabel: ["لوحة المربيات", "Educator board"], adminTitle: ["تحديثات المجموعة", "Group updates"], adminRows: [["أ", ["مجموعة الأقحوان", "Daisy group"], ["12 طفلًا • حضور كامل", "12 children • full attendance"], ["جيد", "Good"]], ["و", ["وجبة اليوم", "Today’s meal"], ["تم تسجيل الحساسية مسبقًا", "Allergies pre-recorded"], ["جاهزة", "Ready"]], ["ر", ["رسالة إلى الأهل", "Parent note"], ["مستلزمات نشاط الخميس", "Thursday activity supplies"], ["إرسال", "Send"]]],
    stats: [["12", ["طفلًا في المجموعة", "children in group"]], ["04", ["أنشطة اليوم", "activities today"]], ["100%", ["اكتمال التحديث", "update complete"]]], flow: [["تُسجّل المربية", "Educator records"], ["يصل الملخص", "Summary arrives"], ["يتابع الأهل", "Parents follow"]], tone: "amber",
  }),
  "medical-labs": sectorDemo({
    brand: ["مختبر بيّنة", "Bayina Lab"], headline: ["من طلب الفحص إلى نتيجة جاهزة برمز تحقق", "From test request to a result protected by a verification code"], description: ["دليل تحضيرات وحالة عينة وتنبيه جاهزية، من دون بيانات صحية حقيقية.", "Preparation guide, sample status and result alert, with no real health data."], action: ["حرّك العينة التجريبية", "Advance the demo sample"], result: ["انتقلت العينة الخيالية إلى مرحلة اعتماد النتيجة", "Fictional sample moved to result approval"],
    clientLabel: ["دليل الفحوصات", "Test guide"], clientTitle: ["فحوصات شائعة", "Common tests"], clientRows: [["⚗", ["فحص دم عام", "Complete blood count"], ["لا يحتاج إلى صيام", "No fasting required"], ["متاح", "Available"]], ["◌", ["وظائف الغدة", "Thyroid panel"], ["تعليمات قبل الزيارة", "Pre-visit guidance"], ["عرض", "View"]], ["⌂", ["سحب منزلي", "Home collection"], ["مناطق مختارة في بغداد", "Selected Baghdad areas"], ["اطلب", "Request"]]],
    adminLabel: ["مسار العينات", "Sample workflow"], adminTitle: ["العينات النشطة", "Active samples"], adminRows: [["S1", ["عينة #B-142", "Sample #B-142"], ["تم الاستلام 09:12", "Received 09:12"], ["قيد الفحص", "Testing"]], ["S2", ["عينة #B-141", "Sample #B-141"], ["بانتظار الاعتماد", "Awaiting approval"], ["مراجعة", "Review"]], ["S3", ["نتيجة #B-139", "Result #B-139"], ["جاهزة برمز تحقق", "Ready with verification"], ["جاهزة", "Ready"]]],
    stats: [["38", ["عينة اليوم", "samples today"]], ["07", ["قيد الاعتماد", "awaiting approval"]], ["02", ["طلبات منزلية", "home requests"]]], flow: [["تُسجّل العينة", "Register sample"], ["تُفحص وتُراجع", "Test and review"], ["يصل التنبيه", "Send notification"]], tone: "green",
  }),
  pharmacies: sectorDemo({
    brand: ["صيدلية نبض", "Nabd Pharmacy"], headline: ["توافر ومخزون وطلب تجهيز بلا التباس", "Availability, inventory and preparation requests without confusion"], description: ["بحث عن منتجات صحية غير وصفية، واختيار فرع، ومتابعة التجهيز.", "Search non-prescription health products, choose a branch and track preparation."], action: ["أرسل طلب تجهيز تجريبيًا", "Send a demo preparation request"], result: ["حُجز المنتج الخيالي في فرع المنصور لمدة محدودة", "Fictional item reserved at Mansour branch for a limited time"],
    clientLabel: ["البحث والتوافر", "Search and availability"], clientTitle: ["منتجات صحية", "Health products"], clientRows: [["✚", ["جهاز قياس حرارة", "Thermometer"], ["متوفر في فرعين", "Available at two branches"], ["متوفر", "Available"]], ["◇", ["ضمادات طبية", "Medical dressings"], ["3 أحجام", "Three sizes"], ["اختر", "Choose"]], ["◌", ["عناية يومية", "Daily care"], ["مجموعة منتجات مختارة", "Selected product range"], ["تصفح", "Browse"]]],
    adminLabel: ["إدارة الفرع", "Branch operations"], adminTitle: ["المخزون والطلبات", "Stock and requests"], adminRows: [["P1", ["طلب تجهيز #P-82", "Prep request #P-82"], ["فرع المنصور • منتجان", "Mansour • two items"], ["للتجهيز", "Prepare"]], ["!", ["مخزون منخفض", "Low stock"], ["ضمادات الحجم المتوسط", "Medium dressings"], ["6 قطع", "6 left"]], ["⇄", ["نقل بين الفروع", "Branch transfer"], ["من زيونة إلى الكرادة", "Zayouna to Karrada"], ["قيد النقل", "Moving"]]],
    stats: [["840", ["صنفًا تجريبيًا", "demo SKUs"]], ["16", ["طلب تجهيز", "prep requests"]], ["05", ["تنبيهات مخزون", "stock alerts"]]], flow: [["يبحث عن المنتج", "Search item"], ["يختار الفرع", "Choose branch"], ["يستلم التأكيد", "Receive confirmation"]], tone: "cyan",
  }),
  "sports-clubs": sectorDemo({
    brand: ["نادي حركة", "Haraka Club"], headline: ["عضوية وحصص ومدربون في جدول يشجع على الاستمرار", "Membership, classes and coaches in a schedule built for consistency"], description: ["اكتشاف الحصة وحجز المقعد وتسجيل الحضور ومتابعة العضوية.", "Discover a class, reserve a place, record attendance and track membership."], action: ["احجز الحصة التجريبية", "Book the demo class"], result: ["حُجز مقعد خيالي في حصة القوة عند 18:30", "Fictional place booked in the 18:30 strength class"],
    clientLabel: ["جدول العضو", "Member schedule"], clientTitle: ["حصص اليوم", "Today’s classes"], clientRows: [["●", ["تمارين القوة", "Strength training"], ["18:30 • المدرب علي", "18:30 • Coach Ali"], ["4 مقاعد", "4 places"]], ["◒", ["لياقة وظيفية", "Functional fitness"], ["19:30 • القاعة B", "19:30 • Studio B"], ["متاح", "Available"]], ["↗", ["جري جماعي", "Group run"], ["الجمعة • 07:00", "Friday • 07:00"], ["انضم", "Join"]]],
    adminLabel: ["تشغيل النادي", "Club operations"], adminTitle: ["الحصص والعضويات", "Classes and memberships"], adminRows: [["18", ["حصة القوة", "Strength class"], ["16 من 20 مقعدًا", "16 of 20 places"], ["مفتوحة", "Open"]], ["M", ["عضويات تنتهي قريبًا", "Memberships expiring"], ["9 خلال هذا الأسبوع", "9 this week"], ["متابعة", "Follow up"]], ["✓", ["حضور اليوم", "Attendance today"], ["74 عضوًا", "74 members"], ["مباشر", "Live"]]],
    stats: [["126", ["عضوًا نشطًا", "active members"]], ["11", ["حصة اليوم", "classes today"]], ["74", ["حضورًا", "check-ins"]]], flow: [["يختار الحصة", "Choose class"], ["يحجز المقعد", "Book place"], ["يُسجّل الحضور", "Check in"]], tone: "violet",
  }),
  "beauty-salons": sectorDemo({
    brand: ["دار لمسة", "Lamsa Studio"], headline: ["حجز أنيق يبدأ بالخدمة وينتهي بموعد مؤكد", "A polished booking journey from service to confirmed appointment"], description: ["خدمات وأسعار وأخصائيون وأوقات متاحة في واجهة تناسب الهاتف.", "Services, prices, specialists and available times in a mobile-friendly interface."], action: ["أكّد الموعد التجريبي", "Confirm the demo appointment"], result: ["تأكّد الموعد الخيالي مع نور عند 17:00", "Fictional appointment confirmed with Noor at 17:00"],
    clientLabel: ["قائمة الخدمات", "Service menu"], clientTitle: ["اختاري تجربتك", "Choose your experience"], clientRows: [["✦", ["تصفيف الشعر", "Hair styling"], ["45 دقيقة • من 25,000 د.ع", "45 min • from IQD 25,000"], ["احجزي", "Book"]], ["◇", ["العناية بالبشرة", "Skin care"], ["60 دقيقة • استشارة أولية", "60 min • initial consultation"], ["اختاري", "Choose"]], ["◌", ["العناية بالأظافر", "Nail care"], ["40 دقيقة • 3 أوقات", "40 min • 3 slots"], ["متاح", "Available"]]],
    adminLabel: ["رزنامة الصالون", "Salon calendar"], adminTitle: ["مواعيد اليوم", "Today’s appointments"], adminRows: [["ن", ["نور", "Noor"], ["17:00 • تصفيف شعر", "17:00 • styling"], ["مؤكد", "Confirmed"]], ["س", ["سارة", "Sara"], ["18:00 • عناية بالبشرة", "18:00 • skin care"], ["مؤكد", "Confirmed"]], ["ر", ["رُبى", "Ruba"], ["19:15 • وقت متاح", "19:15 • open slot"], ["متاح", "Available"]]],
    stats: [["14", ["موعدًا اليوم", "appointments today"]], ["03", ["أخصائيات", "specialists"]], ["04", ["أوقات متاحة", "open slots"]]], flow: [["تختار الخدمة", "Choose service"], ["تختار الأخصائي", "Choose specialist"], ["تؤكد الموعد", "Confirm time"]], tone: "amber",
  }),
  accounting: sectorDemo({
    brand: ["مكتب رصيد", "Raseed Office"], headline: ["إقفال شهري واضح بدل مطاردة الملفات", "A clear monthly close instead of chasing files"], description: ["قائمة وثائق ومهام ومراجعة وحالة نهائية لكل عميل.", "Documents, tasks, review and final status for every client."], action: ["أكمل مهمة تجريبية", "Complete a demo task"], result: ["أُضيف كشف البنك الخيالي وانتقل الإقفال إلى المراجعة", "Fictional bank statement added and close moved to review"],
    clientLabel: ["مساحة العميل", "Client workspace"], clientTitle: ["إقفال تموز", "July close"], clientRows: [["✓", ["فواتير المبيعات", "Sales invoices"], ["24 ملفًا مرفوعًا", "24 files uploaded"], ["مكتمل", "Complete"]], ["$", ["كشف الحساب المصرفي", "Bank statement"], ["ملف واحد مطلوب", "One file required"], ["ناقص", "Missing"]], ["∑", ["ملخص المصروفات", "Expense summary"], ["قيد المراجعة", "Under review"], ["مراجعة", "Review"]]],
    adminLabel: ["لوحة المكتب", "Office dashboard"], adminTitle: ["حالة العملاء", "Client status"], adminRows: [["A", ["شركة ألف", "Company Alef"], ["اكتمل 8 من 9", "8 of 9 complete"], ["قريب", "Nearly done"]], ["B", ["متجر باء", "Store Baa"], ["ينقص ملفان", "Two files missing"], ["متابعة", "Follow up"]], ["C", ["مكتب جيم", "Office Jeem"], ["جاهز للمراجعة", "Ready for review"], ["جاهز", "Ready"]]],
    stats: [["18", ["عميلًا نشطًا", "active clients"]], ["82%", ["اكتمال الإقفال", "close complete"]], ["07", ["ملفات ناقصة", "missing files"]]], flow: [["يرفع العميل", "Client uploads"], ["يراجع المحاسب", "Accountant reviews"], ["يُغلق الشهر", "Close month"]], tone: "green",
  }),
  architecture: sectorDemo({
    brand: ["أثر للهندسة", "Athar Studio"], headline: ["مشروع معماري من الفكرة إلى اعتماد المخطط", "An architectural project from concept to drawing approval"], description: ["معرض أعمال ومتطلبات وإصدارات مخططات وقرارات عميل موثقة.", "Portfolio, briefs, drawing revisions and recorded client decisions."], action: ["اعتمد الإصدار التجريبي", "Approve the demo revision"], result: ["اعتُمد المخطط الخيالي R03 وانتقلت المرحلة إلى التصميم التفصيلي", "Fictional R03 plan approved and moved to detailed design"],
    clientLabel: ["بوابة المشروع", "Project portal"], clientTitle: ["منزل الجادرية", "Jadriya House"], clientRows: [["R1", ["المخطط الأولي", "Concept plan"], ["اعتمد في 04 آب", "Approved 4 Aug"], ["مكتمل", "Complete"]], ["R3", ["توزيع الطابق الأرضي", "Ground-floor layout"], ["الإصدار الثالث • للمراجعة", "Revision three • review"], ["قرار", "Decision"]], ["3D", ["المشاهد الخارجية", "Exterior views"], ["4 مشاهد جاهزة", "Four views ready"], ["جاهزة", "Ready"]]],
    adminLabel: ["إدارة المكتب", "Studio management"], adminTitle: ["المراحل والاعتمادات", "Stages and approvals"], adminRows: [["01", ["التصميم الأولي", "Concept design"], ["100%", "100%"], ["مكتمل", "Complete"]], ["02", ["التصميم التفصيلي", "Detailed design"], ["يبدأ بعد الاعتماد", "Starts after approval"], ["قادم", "Next"]], ["!", ["قرار العميل", "Client decision"], ["توزيع الصالة", "Living area layout"], ["مطلوب", "Required"]]],
    stats: [["03", ["إصدارات", "revisions"]], ["12", ["لوحة معتمدة", "approved sheets"]], ["01", ["قرار مطلوب", "decision needed"]]], flow: [["يُرفع الإصدار", "Upload revision"], ["يراجعه العميل", "Client reviews"], ["يُوثّق الاعتماد", "Record approval"]], tone: "cyan",
  }),
  recruitment: sectorDemo({
    brand: ["كفاءات", "Kafaat"], headline: ["مرشحون ومقابلات وقرارات في خط توظيف واحد", "Candidates, interviews and decisions in one hiring pipeline"], description: ["فرز أولي وملفات مرشحين وجدولة مقابلات وتحديثات واضحة.", "Pre-screening, candidate profiles, interview scheduling and clear updates."], action: ["انقل المرشح إلى المقابلة", "Move candidate to interview"], result: ["انتقل المرشح الخيالي أحمد إلى مرحلة المقابلة الفنية", "Fictional candidate Ahmed moved to technical interview"],
    clientLabel: ["بوابة الوظائف", "Jobs portal"], clientTitle: ["فرص مفتوحة", "Open roles"], clientRows: [["D", ["مصمم واجهات", "UI designer"], ["بغداد • دوام كامل", "Baghdad • full time"], ["تقدّم", "Apply"]], ["S", ["مندوب مبيعات", "Sales representative"], ["البصرة • خبرة سنتين", "Basra • 2 years"], ["تقدّم", "Apply"]], ["A", ["محاسب", "Accountant"], ["أربيل • حضوري", "Erbil • on site"], ["مفتوحة", "Open"]]],
    adminLabel: ["خط التوظيف", "Hiring pipeline"], adminTitle: ["مرشحون نشطون", "Active candidates"], adminRows: [["أ", ["أحمد كريم", "Ahmed Kareem"], ["مصمم واجهات • 82%", "UI designer • 82%"], ["فرز أولي", "Screening"]], ["س", ["سارة ليث", "Sara Laith"], ["محاسبة • مقابلة اليوم", "Accounting • interview today"], ["مقابلة", "Interview"]], ["م", ["محمد علي", "Mohammed Ali"], ["مبيعات • مراجع مكتملة", "Sales • references complete"], ["قرار", "Decision"]]],
    stats: [["46", ["مرشحًا", "candidates"]], ["08", ["مقابلات", "interviews"]], ["05", ["وظائف مفتوحة", "open roles"]]], flow: [["يتقدم المرشح", "Candidate applies"], ["يُفرز ويُقابل", "Screen and interview"], ["يصل القرار", "Reach decision"]], tone: "violet",
  }),
  "training-institutes": sectorDemo({
    brand: ["معهد بيان", "Bayan Institute"], headline: ["اختبار مستوى وجدول وتقدم في رحلة تعليمية واحدة", "Placement, schedule and progress in one learning journey"], description: ["اختبار قصير يقترح المستوى، ثم اختيار المجموعة ومتابعة الحضور.", "A short placement check, group selection and attendance tracking."], action: ["أكمل اختبار المستوى التجريبي", "Complete the demo placement"], result: ["اقتُرح المستوى B1 وأصبحت مجموعتان متاحتين", "Level B1 suggested with two groups available"],
    clientLabel: ["مسار المتدرب", "Learner journey"], clientTitle: ["اللغة الإنجليزية", "English language"], clientRows: [["A2", ["المستوى الحالي", "Current level"], ["نتيجة التقييم الأولي", "Initial assessment result"], ["مبدئي", "Initial"]], ["B1", ["المستوى المقترح", "Suggested level"], ["4 مهارات • 24 جلسة", "Four skills • 24 sessions"], ["مقترح", "Suggested"]], ["◷", ["المجموعة المسائية", "Evening group"], ["الأحد والثلاثاء • 18:00", "Sun & Tue • 18:00"], ["6 مقاعد", "6 places"]]],
    adminLabel: ["إدارة المعهد", "Institute office"], adminTitle: ["المجموعات النشطة", "Active groups"], adminRows: [["B1", ["الإنجليزية B1", "English B1"], ["18 من 24 متدربًا", "18 of 24 learners"], ["مفتوحة", "Open"]], ["D", ["التصميم المهني", "Vocational design"], ["الحضور 91%", "91% attendance"], ["نشطة", "Active"]], ["C", ["شهادات هذا الشهر", "Certificates this month"], ["22 شهادة للمراجعة", "22 to review"], ["مراجعة", "Review"]]],
    stats: [["09", ["مجموعات نشطة", "active groups"]], ["126", ["متدربًا", "learners"]], ["91%", ["نسبة الحضور", "attendance"]]], flow: [["يختبر مستواه", "Check level"], ["يختار المجموعة", "Choose group"], ["يتابع التقدم", "Track progress"]], tone: "amber",
  }),
  automotive: sectorDemo({
    brand: ["مسار للسيارات", "Masar Auto"], headline: ["المركبة من الحجز إلى الفحص ثم التسليم", "A vehicle journey from booking to inspection and handover"], description: ["كتالوج وحجز وتجهيز وموافقة على العمل وحالة مباشرة للمركبة.", "Catalogue, booking, preparation, work approval and live vehicle status."], action: ["وافق على الإصلاح التجريبي", "Approve the demo repair"], result: ["اعتُمد تغيير البطارية الخيالي وانتقلت المركبة إلى التنفيذ", "Fictional battery replacement approved and moved to work"],
    clientLabel: ["ملف المركبة", "Vehicle profile"], clientTitle: ["Toyota Camry 2022", "Toyota Camry 2022"], clientRows: [["◉", ["الفحص الأولي", "Initial inspection"], ["اكتمل في 10:20", "Completed 10:20"], ["مكتمل", "Complete"]], ["!", ["موافقة مطلوبة", "Approval required"], ["استبدال البطارية", "Battery replacement"], ["قرار", "Decision"]], ["◷", ["موعد التسليم", "Handover time"], ["اليوم • 17:30", "Today • 17:30"], ["متوقع", "Expected"]]],
    adminLabel: ["لوحة الورشة", "Workshop board"], adminTitle: ["المركبات النشطة", "Active vehicles"], adminRows: [["B2", ["Camry • B2", "Camry • B2"], ["بانتظار الموافقة", "Awaiting approval"], ["متوقفة", "Paused"]], ["A1", ["Sportage • A1", "Sportage • A1"], ["صيانة دورية", "Routine service"], ["قيد العمل", "In service"]], ["C3", ["Corolla • C3", "Corolla • C3"], ["جاهزة للتسليم", "Ready for handover"], ["جاهزة", "Ready"]]],
    stats: [["11", ["مركبة اليوم", "vehicles today"]], ["04", ["قيد العمل", "in service"]], ["02", ["بانتظار قرار", "awaiting approval"]]], flow: [["يحجز العميل", "Customer books"], ["تُفحص المركبة", "Inspect vehicle"], ["يوافق ويتابع", "Approve and track"]], tone: "green",
  }),
  logistics: sectorDemo({
    brand: ["وصل للشحن", "Wasal Logistics"], headline: ["شحنة واضحة من الاستلام إلى التسليم", "A clear shipment journey from pickup to delivery"], description: ["عنوان ومسار وسائق ومحاولات تسليم وتحديثات حالة في شاشة واحدة.", "Address, route, driver, delivery attempts and status updates in one screen."], action: ["حرّك الشحنة إلى المرحلة التالية", "Move shipment to next stage"], result: ["غادرت الشحنة الخيالية مركز الفرز نحو المنصور", "Fictional shipment left the hub for Mansour"],
    clientLabel: ["تتبع الشحنة", "Shipment tracking"], clientTitle: ["الشحنة #W-2048", "Shipment #W-2048"], clientRows: [["✓", ["استلام الشحنة", "Shipment collected"], ["بغداد الجديدة • 09:10", "New Baghdad • 09:10"], ["مكتمل", "Complete"]], ["⇄", ["مركز الفرز", "Sorting hub"], ["غادرت عند 12:25", "Departed 12:25"], ["مباشر", "Live"]], ["⌖", ["التسليم", "Delivery"], ["المنصور • 15:00–17:00", "Mansour • 15:00–17:00"], ["قادم", "Next"]]],
    adminLabel: ["مركز التوزيع", "Dispatch centre"], adminTitle: ["جولات اليوم", "Today’s routes"], adminRows: [["R1", ["جولة المنصور", "Mansour route"], ["18 شحنة • السائق حيدر", "18 shipments • Haider"], ["في الطريق", "On route"]], ["R2", ["جولة الكرادة", "Karrada route"], ["14 شحنة • محاولتان", "14 shipments • 2 attempts"], ["متابعة", "Follow up"]], ["R3", ["جولة زيونة", "Zayouna route"], ["11 شحنة • 82%", "11 shipments • 82%"], ["جيدة", "Healthy"]]],
    stats: [["146", ["شحنة اليوم", "shipments today"]], ["09", ["سائقين نشطين", "active drivers"]], ["82%", ["تم التسليم", "delivered"]]], flow: [["تُستلم الشحنة", "Collect shipment"], ["تُفرز وتُوجّه", "Sort and route"], ["تُسلّم وتُوثّق", "Deliver and record"]], tone: "cyan",
  }),
  hospitality: sectorDemo({
    brand: ["دار دجلة", "Dar Dijla"], headline: ["إقامة تبدأ باختيار واضح وتنتهي بطلب حجز مكتمل", "A stay that starts with clear choice and a complete booking request"], description: ["غرف ومزايا وتواريخ وضيوف وتعليمات وصول في تجربة ضيافة واحدة.", "Rooms, amenities, dates, guests and arrival information in one hospitality journey."], action: ["أرسل طلب الحجز التجريبي", "Send the demo booking request"], result: ["استُلم طلب خيالي لغرفة دجلة من 20 إلى 23 آب", "Fictional request received for Dijla Room, 20–23 Aug"],
    clientLabel: ["اختيار الإقامة", "Stay selection"], clientTitle: ["الغرف المتاحة", "Available rooms"], clientRows: [["▥", ["غرفة دجلة", "Dijla Room"], ["شخصان • فطور", "Two guests • breakfast"], ["متاحة", "Available"]], ["⌂", ["شقة الرافدين", "Rafidain Suite"], ["4 أشخاص • مطبخ", "Four guests • kitchen"], ["متاحة", "Available"]], ["✦", ["إطلالة المدينة", "City View"], ["شرفة • طابق مرتفع", "Balcony • high floor"], ["اطلب", "Request"]]],
    adminLabel: ["مكتب الاستقبال", "Front desk"], adminTitle: ["الإشغال والطلبات", "Occupancy and requests"], adminRows: [["20", ["وصول اليوم", "Arrivals today"], ["8 حجوزات مؤكدة", "8 confirmed bookings"], ["جاهز", "Ready"]], ["23", ["مغادرة اليوم", "Departures today"], ["5 غرف", "5 rooms"], ["قيد العمل", "In progress"]], ["!", ["طلب خاص", "Special request"], ["تسجيل وصول متأخر", "Late check-in"], ["ملاحظة", "Note"]]],
    stats: [["78%", ["نسبة الإشغال", "occupancy"]], ["08", ["وصول اليوم", "arrivals today"]], ["03", ["غرف متاحة", "rooms available"]]], flow: [["يختار الغرفة", "Choose room"], ["يحدد التواريخ", "Select dates"], ["يرسل الطلب", "Send request"]], tone: "amber",
  }),
  events: sectorDemo({
    brand: ["ليلة للمناسبات", "Layla Events"], headline: ["مناسبة تُبنى من العدد والقاعة إلى الباقة والتجهيز", "An event built from guest count and venue to package and setup"], description: ["مقارنة قاعات وباقات ومخطط تجهيز وقائمة قرارات قبل الموعد.", "Venue and package comparison, setup plan and decision checklist before the date."], action: ["احفظ مخطط المناسبة التجريبي", "Save the demo event plan"], result: ["حُفظ مخطط خيالي لـ180 ضيفًا مع باقة المساء", "Fictional plan saved for 180 guests with Evening package"],
    clientLabel: ["مخطط المناسبة", "Event planner"], clientTitle: ["اختر القاعة والباقة", "Choose venue and package"], clientRows: [["180", ["عدد الضيوف", "Guest count"], ["قابل للتعديل", "Adjustable"], ["180", "180"]], ["✧", ["قاعة النخيل", "Palm Hall"], ["حتى 220 ضيفًا", "Up to 220 guests"], ["متاحة", "Available"]], ["M", ["باقة المساء", "Evening package"], ["ضيافة • إضاءة • تنسيق", "Catering • lighting • styling"], ["مختارة", "Selected"]]],
    adminLabel: ["لوحة المنظم", "Planner board"], adminTitle: ["قرارات وتجهيزات", "Decisions and setup"], adminRows: [["✓", ["مخطط الطاولات", "Table plan"], ["18 طاولة • 10 ضيوف", "18 tables • 10 guests"], ["جاهز", "Ready"]], ["!", ["اختيار الألوان", "Colour selection"], ["مطلوب قبل 18 آب", "Due before 18 Aug"], ["قرار", "Decision"]], ["◷", ["موعد التجربة", "Tasting session"], ["الأربعاء • 17:00", "Wednesday • 17:00"], ["مؤكد", "Confirmed"]]],
    stats: [["180", ["ضيفًا", "guests"]], ["18", ["طاولة", "tables"]], ["02", ["قرارات مطلوبة", "decisions needed"]]], flow: [["يحدد التفاصيل", "Set details"], ["يقارن الباقات", "Compare packages"], ["يعتمد المخطط", "Approve plan"]], tone: "violet",
  }),
  manufacturing: sectorDemo({
    brand: ["مصنع أساس", "Asas Factory"], headline: ["خط إنتاج يُظهر الأمر والجودة والتوقف لحظة بلحظة", "A production line showing orders, quality and downtime as they happen"], description: ["أوامر عمل ومحطات ومواد وفحص جودة وصيانة ضمن لوحة تشغيل.", "Work orders, stations, materials, quality checks and maintenance in one board."], action: ["شغّل المحطة التجريبية", "Run the demo station"], result: ["اكتملت الدفعة الخيالية #B-71 واجتازت فحص الجودة", "Fictional batch #B-71 completed and passed quality check"],
    clientLabel: ["خطة الإنتاج", "Production plan"], clientTitle: ["أوامر العمل", "Work orders"], clientRows: [["B71", ["دفعة #B-71", "Batch #B-71"], ["240 وحدة • خط 2", "240 units • line 2"], ["قيد العمل", "Running"]], ["B72", ["دفعة #B-72", "Batch #B-72"], ["180 وحدة • بعد B-71", "180 units • after B-71"], ["قادمة", "Queued"]], ["M2", ["المادة الخام M2", "Raw material M2"], ["تكفي 1.8 وردية", "1.8 shifts remaining"], ["تنبيه", "Alert"]]],
    adminLabel: ["غرفة التشغيل", "Operations room"], adminTitle: ["حالة المحطات", "Station status"], adminRows: [["01", ["القص", "Cutting"], ["98% كفاءة", "98% efficiency"], ["تعمل", "Running"]], ["02", ["التجميع", "Assembly"], ["دفعة B-71", "Batch B-71"], ["تعمل", "Running"]], ["03", ["فحص الجودة", "Quality check"], ["4 عينات بانتظار الفحص", "4 samples waiting"], ["فحص", "Inspect"]]],
    stats: [["82%", ["كفاءة الوردية", "shift efficiency"]], ["420", ["وحدة اليوم", "units today"]], ["04", ["عينات جودة", "quality samples"]]], flow: [["يُفتح أمر العمل", "Open work order"], ["يمر بالمحطات", "Move through stations"], ["يُعتمد الفحص", "Approve quality"]], tone: "green",
  }),
  insurance: sectorDemo({
    brand: ["أمان للوساطة", "Aman Brokerage"], headline: ["تغطية مفهومة وطلب عرض ومطالبة قابلة للتتبع", "Understandable coverage, quote requests and trackable claims"], description: ["مقارنة مبسطة وحقول مكتملة وقائمة مستندات وحالة مطالبة واضحة.", "Plain comparison, complete fields, document checklist and clear claim status."], action: ["أرسل طلب العرض التجريبي", "Send the demo quote request"], result: ["أُرسل الطلب الخيالي للمراجعة دون إصدار سعر أو وثيقة", "Fictional request sent for review without issuing a price or policy"],
    clientLabel: ["مقارنة التغطية", "Coverage comparison"], clientTitle: ["خيارات توضيحية", "Illustrative options"], clientRows: [["S", ["تغطية أساسية", "Essential cover"], ["مزايا رئيسية موضحة", "Core benefits explained"], ["قارن", "Compare"]], ["P", ["تغطية موسعة", "Extended cover"], ["حدود واستثناءات أوضح", "Clearer limits and exclusions"], ["قارن", "Compare"]], ["C", ["مطالبة حالية", "Existing claim"], ["تم استلام 3 مستندات", "Three documents received"], ["متابعة", "Track"]]],
    adminLabel: ["لوحة الوسيط", "Broker dashboard"], adminTitle: ["الطلبات والمطالبات", "Quotes and claims"], adminRows: [["Q1", ["طلب عرض #Q-91", "Quote #Q-91"], ["الحقول مكتملة", "Fields complete"], ["مراجعة", "Review"]], ["C8", ["مطالبة #C-28", "Claim #C-28"], ["بانتظار تقرير واحد", "Waiting for one report"], ["ناقص", "Incomplete"]], ["R", ["تجديد قريب", "Renewal due"], ["بعد 12 يومًا", "In 12 days"], ["تنبيه", "Alert"]]],
    stats: [["18", ["طلب عرض", "quote requests"]], ["07", ["مطالبات نشطة", "active claims"]], ["05", ["تجديدات قريبة", "renewals due"]]], flow: [["يقارن الخيارات", "Compare options"], ["يُكمل الطلب", "Complete request"], ["يراجعه المختص", "Specialist review"]], tone: "cyan",
  }),
  "religious-travel": sectorDemo({
    brand: ["قافلة للزيارات", "Qafila Travel"], headline: ["برنامج زيارة ومجموعة ومستندات في رحلة منظمة", "An organised pilgrimage itinerary, group and document journey"], description: ["تفاصيل الأيام ونقاط التجمع وقائمة المستندات وتحديثات المجموعة دون تأكيد وهمي.", "Daily details, meeting points, document checklist and group updates without false confirmation."], action: ["أرسل طلب الانضمام التجريبي", "Send the demo join request"], result: ["استُلم طلب خيالي للانضمام إلى مجموعة النجف وكربلاء", "Fictional request received for the Najaf and Karbala group"],
    clientLabel: ["برنامج الزائر", "Traveller itinerary"], clientTitle: ["زيارة النجف وكربلاء", "Najaf and Karbala visit"], clientRows: [["01", ["اليوم الأول", "Day one"], ["الوصول ونقطة التجمع", "Arrival and meeting point"], ["عرض", "View"]], ["02", ["اليوم الثاني", "Day two"], ["برنامج الزيارة والنقل", "Visit programme and transport"], ["عرض", "View"]], ["✓", ["قائمة المستندات", "Document checklist"], ["اكتمل 4 من 5", "4 of 5 complete"], ["ناقص واحد", "One missing"]]],
    adminLabel: ["إدارة المجموعة", "Group management"], adminTitle: ["الرحلات والمشاركون", "Trips and participants"], adminRows: [["G1", ["مجموعة 21 آب", "21 Aug group"], ["34 من 40 مشاركًا", "34 of 40 travellers"], ["مفتوحة", "Open"]], ["D", ["المستندات", "Documents"], ["6 ملفات تحتاج متابعة", "6 files need follow-up"], ["متابعة", "Follow up"]], ["M", ["تنبيه التجمع", "Meeting alert"], ["يرسل قبل 6 ساعات", "Sends 6 hours before"], ["جاهز", "Ready"]]],
    stats: [["34", ["مشاركًا", "travellers"]], ["05", ["أيام البرنامج", "itinerary days"]], ["06", ["ملفات ناقصة", "missing files"]]], flow: [["يختار البرنامج", "Choose programme"], ["يُكمل المستندات", "Complete documents"], ["يتابع المجموعة", "Follow group"]], tone: "amber",
  }),
};

const industries: Record<string, ContextDemo> = {
  clinics: {
    brand: ["عيادة الشفاء", "Al-Shifa Clinic"], headline: ["حجز موعد واضح للمراجع والعيادة", "Clear appointment booking for patients and clinic staff"], description: ["اختيار الاختصاص والطبيب والوقت ثم تأكيد آمن دون بيانات صحية حقيقية.", "Choose speciality, doctor and time, then get a safe confirmation without real health data."], action: ["احجز موعدًا تجريبيًا", "Book a demo appointment"], result: ["تم حجز موعد خيالي: الأحد، 10:30", "Fictional appointment booked: Sunday, 10:30"],
    client: { label: ["حجز المراجع", "Patient booking"], title: ["اختر موعدًا متاحًا", "Choose an available time"], rows: [["✚", ["طب الأسرة", "Family medicine"], ["د. نور • الأحد 10:30", "Dr Noor • Sunday 10:30"], ["متاح", "Available"]], ["◎", ["طب الأسنان", "Dentistry"], ["د. ليث • الأحد 12:00", "Dr Laith • Sunday 12:00"], ["متاح", "Available"]], ["◌", ["استشارة أطفال", "Paediatrics"], ["د. زهراء • الاثنين 09:00", "Dr Zahra • Monday 09:00"], ["متاح", "Available"]]] },
    admin: { label: ["جدول العيادة", "Clinic schedule"], title: ["مواعيد اليوم", "Today's appointments"], rows: [["10", ["موعد تجريبي #31", "Demo appointment #31"], ["10:30 • طب الأسرة", "10:30 • family medicine"], ["مؤكد", "Confirmed"]], ["11", ["موعد تجريبي #32", "Demo appointment #32"], ["11:15 • فحص عام", "11:15 • general check"], ["بانتظار الوصول", "Awaiting arrival"]], ["12", ["موعد تجريبي #33", "Demo appointment #33"], ["12:00 • أسنان", "12:00 • dentistry"], ["تم التذكير", "Reminded"]]] },
    stats: [["12", ["موعدًا اليوم", "appointments today"]], ["03", ["أطباء متاحون", "available doctors"]], ["0", ["تداخلات", "conflicts"]]], flow: [["اختيار الاختصاص", "Choose speciality"], ["اختيار الوقت", "Choose time"], ["استلام التأكيد", "Get confirmation"]], tone: "cyan",
  },
  restaurants: {
    brand: ["مقهى النخلة", "Palm Café"], headline: ["قائمة رقمية وطلب واضح عبر الهاتف", "A mobile menu and clear ordering journey"], description: ["الأصناف والإضافات والسعر وطريقة الاستلام في تجربة واحدة.", "Items, options, price and fulfilment in one experience."], action: ["أرسل طلبًا تجريبيًا", "Place a demo order"], result: ["وصل الطلب الخيالي إلى شاشة المطبخ", "Fictional order sent to the kitchen screen"],
    client: { label: ["قائمة الزبون", "Customer menu"], title: ["الأكثر طلبًا", "Popular today"], rows: [["☕", ["لاتيه بالهيل", "Cardamom latte"], ["حجم وسط • 5,000 د.ع", "Medium • IQD 5,000"], ["أضف", "Add"]], ["◒", ["برغر دجاج", "Chicken burger"], ["مع بطاطا • 9,500 د.ع", "With fries • IQD 9,500"], ["خصص", "Customise"]], ["◇", ["كنافة صغيرة", "Small kunafa"], ["طازجة • 4,000 د.ع", "Fresh • IQD 4,000"], ["أضف", "Add"]]] },
    admin: { label: ["شاشة المطبخ", "Kitchen screen"], title: ["طلبات قيد التحضير", "Orders being prepared"], rows: [["24", ["طلب #24", "Order #24"], ["برغر ×2 • لاتيه ×1", "Burger ×2 • latte ×1"], ["قيد التحضير", "Preparing"]], ["25", ["طلب #25", "Order #25"], ["كنافة ×1 • شاي ×2", "Kunafa ×1 • tea ×2"], ["جديد", "New"]], ["23", ["طلب #23", "Order #23"], ["استلام من الفرع", "Branch pickup"], ["جاهز", "Ready"]]] },
    stats: [["18", ["صنفًا متاحًا", "available items"]], ["07", ["طلبات مفتوحة", "open orders"]], ["22m", ["متوسط التجهيز", "average prep"]]], flow: [["يختار الأصناف", "Choose items"], ["يخصص الطلب", "Customise order"], ["يتابع التجهيز", "Track preparation"]], tone: "amber",
  },
  retail: {
    brand: ["متجر الرافدين", "Rafidain Store"], headline: ["متجر عراقي يعرض المنتجات والمخزون والطلبات بوضوح", "An Iraqi store with clear products, stock and orders"], description: ["تصفح سريع، وسلة مختصرة، وتحديث واضح لحالة الطلب.", "Fast browsing, simple cart and clear order status."], action: ["أضف إلى السلة التجريبية", "Add to demo cart"], result: ["أُضيف منتج خيالي إلى السلة", "Fictional product added to the cart"],
    client: { label: ["واجهة المتجر", "Storefront"], title: ["منتجات مختارة", "Selected products"], rows: [["□", ["مصباح مكتبي", "Desk lamp"], ["متوفر • 32,000 د.ع", "Available • IQD 32,000"], ["أضف", "Add"]], ["◇", ["حافظة هاتف", "Phone case"], ["3 ألوان • 15,000 د.ع", "3 colours • IQD 15,000"], ["اختر", "Choose"]], ["△", ["سماعة لاسلكية", "Wireless headset"], ["ضمان سنة • 48,000 د.ع", "1-year warranty • IQD 48,000"], ["أضف", "Add"]]] },
    admin: { label: ["لوحة التاجر", "Merchant dashboard"], title: ["الطلبات والمخزون", "Orders and inventory"], rows: [["#", ["طلب #812", "Order #812"], ["3 منتجات • بغداد", "3 items • Baghdad"], ["للتجهيز", "To pack"]], ["!", ["سماعة لاسلكية", "Wireless headset"], ["تبقى 4 قطع", "4 units left"], ["مخزون منخفض", "Low stock"]], ["↗", ["مبيعات هذا الأسبوع", "Sales this week"], ["+18% مقارنة بالأسبوع السابق", "+18% vs previous"], ["جيد", "Healthy"]]] },
    stats: [["64", ["منتجًا", "products"]], ["11", ["طلب اليوم", "orders today"]], ["05", ["تنبيهات مخزون", "stock alerts"]]], flow: [["بحث وتصفح", "Search & browse"], ["سلة وتأكيد", "Cart & confirm"], ["تجهيز وتتبع", "Pack & track"]], tone: "violet",
  },
  construction: {
    brand: ["مشروع النخيل", "Palm Project"], headline: ["لوحة تربط المراحل والملفات والدفعات", "A board connecting milestones, files and payments"], description: ["رؤية موحّدة لما أُنجز، وما تأخر، وما يحتاج إلى قرار.", "One view of what is done, delayed and awaiting a decision."], action: ["حدّث مرحلة تجريبية", "Update a demo milestone"], result: ["انتقلت مرحلة الهيكل إلى حالة «مكتمل»", "Structure milestone moved to complete"],
    client: { label: ["عرض المشروع", "Project view"], title: ["تقدم المشروع", "Project progress"], rows: [["01", ["الأعمال الترابية", "Groundwork"], ["أُنجزت وفق الخطة", "Completed to plan"], ["مكتمل", "Complete"]], ["02", ["الهيكل الإنشائي", "Structure"], ["الفحص النهائي اليوم", "Final inspection today"], ["قيد التنفيذ", "In progress"]], ["03", ["الأعمال الكهربائية", "Electrical work"], ["تبدأ بعد الاعتماد", "Starts after approval"], ["قادم", "Upcoming"]]] },
    admin: { label: ["إدارة التنفيذ", "Delivery management"], title: ["المراحل المفتوحة", "Open milestones"], rows: [["!", ["اعتماد مخطط الكهرباء", "Approve electrical plan"], ["مطلوب من الاستشاري", "Consultant action required"], ["قرار", "Decision"]], ["▣", ["تقرير الموقع الأسبوعي", "Weekly site report"], ["12 صورة وملاحظة واحدة", "12 photos and one note"], ["جاهز", "Ready"]], ["$", ["دفعة المرحلة الثانية", "Stage two payment"], ["تاريخ الاستحقاق 18 آب", "Due 18 Aug"], ["قادم", "Upcoming"]]] },
    stats: [["68%", ["نسبة الإنجاز", "completion"]], ["14", ["ملفًا معتمدًا", "approved files"]], ["02", ["قرارات مطلوبة", "decisions needed"]]], flow: [["تحديث الموقع", "Site update"], ["اعتماد المرحلة", "Approve milestone"], ["إصدار التقرير", "Issue report"]], tone: "green",
  },
  consulting: {
    brand: ["مكتب بُعد", "Dimension Office"], headline: ["معالج يجمع متطلبات المشروع قبل الاجتماع", "An intake wizard that captures requirements before the meeting"], description: ["نوع المشروع، والموقع، والمساحة، والملفات، والجدول الزمني المتوقع.", "Project type, location, area, files and expected timeline."], action: ["أكمل طلبًا تجريبيًا", "Complete demo brief"], result: ["اكتمل الملخص وأُنشئ رقم طلب خيالي", "Brief complete and fictional request number created"],
    client: { label: ["معالج العميل", "Client wizard"], title: ["ملخص مشروعك", "Your project brief"], rows: [["⌂", ["نوع المشروع", "Project type"], ["تصميم منزل سكني", "Residential house design"], ["مكتمل", "Complete"]], ["▰", ["المساحة والموقع", "Area and location"], ["420 م² • بغداد", "420 m² • Baghdad"], ["مكتمل", "Complete"]], ["◷", ["المدة المتوقعة", "Expected timeline"], ["البدء خلال 3 أشهر", "Start within 3 months"], ["محدد", "Set"]]] },
    admin: { label: ["مراجعة المكتب", "Office review"], title: ["الطلبات الواردة", "Incoming briefs"], rows: [["01", ["طلب #E-204", "Brief #E-204"], ["تصميم سكني • كامل", "Residential • complete"], ["مؤهل", "Qualified"]], ["02", ["طلب #E-203", "Brief #E-203"], ["استشارة إنشائية", "Structural consultation"], ["مراجعة", "Review"]], ["03", ["طلب #E-202", "Brief #E-202"], ["يحتاج مخطط الأرض", "Needs site plan"], ["ناقص", "Incomplete"]]] },
    stats: [["5/5", ["أقسام مكتملة", "sections complete"]], ["03", ["ملفات تجريبية", "demo attachments"]], ["1", ["قرار مطلوب", "decision needed"]]], flow: [["يجيب عن الأسئلة", "Answers questions"], ["يرفع الملفات", "Adds files"], ["يصل ملخص واضح", "Clear brief arrives"]], tone: "cyan",
  },
  travel: {
    brand: ["رحلات دجلة", "Tigris Travel"], headline: ["عروض قابلة للمقارنة وطلب سفر مكتمل", "Comparable offers and a complete travel request"], description: ["الوجهة والتاريخ والمسافرون والخدمات دون تأكيد وهمي.", "Destination, dates, travellers and services without false confirmation."], action: ["أرسل طلب سفر تجريبيًا", "Send a demo travel request"], result: ["استُلم الطلب للمراجعة وليس للحجز", "Request received for review—not booking"],
    client: { label: ["عروض المسافر", "Traveller offers"], title: ["باقات مقترحة", "Suggested packages"], rows: [["✦", ["إسطنبول — 5 ليالٍ", "Istanbul — 5 nights"], ["فندق ونقل • تاريخ مرن", "Hotel & transfer • flexible"], ["اطلب عرضًا", "Request quote"]], ["✦", ["أنطاليا — 6 ليالٍ", "Antalya — 6 nights"], ["منتجع وإفطار", "Resort & breakfast"], ["اطلب عرضًا", "Request quote"]], ["✦", ["دبي — 4 ليالٍ", "Dubai — 4 nights"], ["فندق وسط المدينة", "Central hotel"], ["قارن", "Compare"]]] },
    admin: { label: ["متابعة الطلبات", "Request follow-up"], title: ["طلبات تحتاج عرضًا", "Requests needing a quote"], rows: [["01", ["عائلة من 4 أشخاص", "Family of four"], ["بغداد • إسطنبول", "Baghdad • Istanbul"], ["تسعير", "Quoting"]], ["02", ["مسافران", "Two travellers"], ["النجف • دبي", "Najaf • Dubai"], ["بيانات كاملة", "Complete"]], ["03", ["مجموعة تدريب", "Training group"], ["أربيل • أنطاليا", "Erbil • Antalya"], ["يحتاج تاريخًا", "Needs date"]]] },
    stats: [["08", ["عروض متاحة", "available offers"]], ["04", ["وجهات", "destinations"]], ["24h", ["وقت الرد المتوقع", "expected response"]]], flow: [["يقارن العروض", "Compare offer"], ["يُكمل الطلب", "Complete request"], ["يستلم عرضًا", "Receive quote"]], tone: "amber",
  },
  education: {
    brand: ["أكاديمية خطوة", "Khatwa Academy"], headline: ["رحلة الدورة من الاكتشاف إلى التسجيل", "A course journey from discovery to enrolment"], description: ["تفاصيل الدورة، والمواعيد، والمدرب، والتقدم في مكان واحد.", "Course details, sessions, trainer and progress in one place."], action: ["سجّل في دورة تجريبية", "Join a demo course"], result: ["أُنشئ تسجيل خيالي وحُدّد تاريخ البدء", "Fictional enrolment created and start date added"],
    client: { label: ["بوابة الطالب", "Student portal"], title: ["دورات مقترحة", "Suggested courses"], rows: [["▱", ["أساسيات Excel", "Excel essentials"], ["12 ساعة • يبدأ 20 آب", "12 hours • starts 20 Aug"], ["8 مقاعد", "8 seats"]], ["⌘", ["التسويق الرقمي", "Digital marketing"], ["16 ساعة • مسائي", "16 hours • evening"], ["متاح", "Available"]], ["◎", ["إدارة المشاريع", "Project management"], ["20 ساعة • حضوري", "20 hours • in person"], ["قريبًا", "Soon"]]] },
    admin: { label: ["إدارة المركز", "Centre dashboard"], title: ["التسجيل والحضور", "Enrolment and attendance"], rows: [["أ", ["مجموعة Excel — A", "Excel group — A"], ["18 مسجلًا من 24", "18 of 24 enrolled"], ["مفتوح", "Open"]], ["ت", ["جلسة التسويق 03", "Marketing session 03"], ["حضور 92%", "92% attendance"], ["تمت", "Done"]], ["ش", ["الشهادات", "Certificates"], ["14 شهادة جاهزة", "14 certificates ready"], ["للمراجعة", "Review"]]] },
    stats: [["06", ["دورات نشطة", "active courses"]], ["84", ["طالبًا تجريبيًا", "demo learners"]], ["91%", ["نسبة الحضور", "attendance"]]], flow: [["يختار الدورة", "Choose course"], ["يُسجّل بياناته", "Enrol"], ["يتابع تقدمه", "Track progress"]], tone: "violet",
  },
  maintenance: {
    brand: ["خدمة البيت", "Home Service"], headline: ["طلب صيانة يبدأ بوصف العطل وينتهي بإغلاقه", "A maintenance request from issue to completion"], description: ["نوع الخدمة، والموقع، والموعد، والفني، والحالة في مسار واحد.", "Service type, location, slot, technician and status in one flow."], action: ["سجّل عطلًا تجريبيًا", "Log a demo issue"], result: ["أُنشئ طلب خيالي وأُسند إلى فني", "Fictional request created and assigned"],
    client: { label: ["طلب العميل", "Customer request"], title: ["اختر نوع الخدمة", "Choose service type"], rows: [["⚡", ["عطل كهربائي", "Electrical issue"], ["فحص قاطع أو إنارة", "Breaker or lighting check"], ["اطلب", "Request"]], ["◉", ["تسرب ماء", "Water leak"], ["مطبخ أو حمام", "Kitchen or bathroom"], ["عاجل", "Urgent"]], ["△", ["صيانة تكييف", "AC maintenance"], ["تنظيف أو تشخيص", "Clean or diagnose"], ["احجز", "Book"]]] },
    admin: { label: ["جدول الفنيين", "Technician schedule"], title: ["طلبات اليوم", "Today's jobs"], rows: [["01", ["طلب #M-88", "Job #M-88"], ["المنصور • كهرباء", "Mansour • electrical"], ["الفني في الطريق", "En route"]], ["02", ["طلب #M-89", "Job #M-89"], ["الكرادة • تسرب", "Karrada • leak"], ["عاجل", "Urgent"]], ["03", ["طلب #M-90", "Job #M-90"], ["زيونة • تكييف", "Zayouna • AC"], ["16:00", "16:00"]]] },
    stats: [["09", ["طلبات اليوم", "jobs today"]], ["04", ["فنيين متاحين", "available technicians"]], ["36m", ["متوسط التوجيه", "average dispatch"]]], flow: [["يصف العطل", "Describe issue"], ["يُسند الفني", "Assign technician"], ["يتابع ويقيّم", "Track & rate"]], tone: "green",
  },
  distribution: {
    brand: ["موزّع العراق", "Iraq Distributor"], headline: ["طلبات وكلاء ومبيعات حسب المحافظة", "Dealer orders and sales by governorate"], description: ["سعر الوكيل والحد الائتماني وحالة الطلب في لوحة واحدة.", "Dealer pricing, credit limit and order status in one dashboard."], action: ["اعتمد طلبًا تجريبيًا", "Approve a demo order"], result: ["اعتُمد الطلب الخيالي وحُجز المخزون", "Fictional order approved and stock reserved"],
    client: { label: ["بوابة الوكيل", "Dealer portal"], title: ["طلب جملة جديد", "New wholesale order"], rows: [["A", ["منتج الفئة A", "Category A product"], ["سعر وكيل • متوفر 240", "Dealer price • 240 available"], ["اطلب", "Order"]], ["B", ["منتج الفئة B", "Category B product"], ["سعر وكيل • متوفر 85", "Dealer price • 85 available"], ["اطلب", "Order"]], ["C", ["منتج الفئة C", "Category C product"], ["عرض 10+1", "10+1 offer"], ["عرض", "Offer"]]] },
    admin: { label: ["لوحة المبيعات", "Sales dashboard"], title: ["الأداء حسب المنطقة", "Regional performance"], rows: [["BG", ["بغداد", "Baghdad"], ["54 طلبًا • +12%", "54 orders • +12%"], ["الأعلى", "Top"]], ["BR", ["البصرة", "Basra"], ["31 طلبًا • +8%", "31 orders • +8%"], ["ينمو", "Growing"]], ["NJ", ["النجف", "Najaf"], ["22 طلبًا • ثابت", "22 orders • stable"], ["مستقر", "Stable"]]] },
    stats: [["27", ["وكيلًا نشطًا", "active dealers"]], ["142", ["طلبًا شهريًا", "monthly orders"]], ["94%", ["توفر المخزون", "stock availability"]]], flow: [["يرسل الوكيل", "Dealer submits"], ["يُراجع الائتمان", "Check credit"], ["يُحجز المخزون", "Reserve stock"]], tone: "cyan",
  },
  startups: {
    brand: ["نسخة أولى", "First Version"], headline: ["نسخة أولية (MVP) تختبر أهم رحلة قبل التوسع", "An MVP prototype that tests the core journey"], description: ["فرضية واضحة، وميزات أساسية، ومؤشرات للتعلّم.", "Clear hypothesis, essential features and learning signals."], action: ["شغّل تجربة النسخة الأولية", "Run MVP experiment"], result: ["سُجّل تفاعل خيالي في لوحة التعلّم", "Fictional interaction recorded in the learning board"],
    client: { label: ["النموذج الأولي", "Prototype"], title: ["التجربة الأساسية", "Core experience"], rows: [["01", ["اكتشف القيمة", "Discover value"], ["رسالة واحدة واضحة", "One clear promise"], ["مفهوم", "Clear"]], ["02", ["جرّب الميزة", "Try the feature"], ["أقل عدد من الخطوات", "Fewest possible steps"], ["نشط", "Active"]], ["03", ["أرسل رأيك", "Share feedback"], ["سؤالان فقط", "Only two questions"], ["سريع", "Quick"]]] },
    admin: { label: ["لوحة التعلم", "Learning board"], title: ["ماذا تعلمنا؟", "What did we learn?"], rows: [["H1", ["هل المشكلة مهمة؟", "Does the problem matter?"], ["31 من 42 أكملوا الرحلة", "31 of 42 completed"], ["إشارة قوية", "Strong signal"]], ["H2", ["هل العرض مفهوم؟", "Is the offer clear?"], ["8 أسئلة متكررة", "8 repeated questions"], ["يحتاج تعديلًا", "Iterate"]], ["H3", ["هل يعود المستخدم؟", "Will users return?"], ["قياس الأسبوع القادم", "Measure next week"], ["قيد الاختبار", "Testing"]]] },
    stats: [["01", ["رحلة أساسية", "core journey"]], ["03", ["فرضيات", "hypotheses"]], ["42", ["تفاعلًا تجريبيًا", "demo interactions"]]], flow: [["نبني الأساس", "Build core"], ["نقيس السلوك", "Measure behaviour"], ["نقرر التوسع", "Decide what scales"]], tone: "violet",
  },
  ...expandedIndustryDemos,
};

export function getContextDemo(kind: "service" | "industry", slug: string) {
  return (kind === "service" ? services : industries)[slug];
}
