export type Pair = [ar: string, en: string, de?: string];
export type DemoRow = [icon: string, title: Pair, meta: Pair, status: Pair];

export type ContextDemo = {
  brand: Pair;
  headline: Pair;
  description: Pair;
  action: Pair;
  result: Pair;
  client: { label: Pair; title: Pair; rows: DemoRow[] };
  admin: { label: Pair; title: Pair; rows: DemoRow[] };
  stats: Array<[value: string, label: Pair]>;
  flow: Pair[];
  tone: "cyan" | "amber" | "violet" | "green";
};

const services: Record<string, ContextDemo> = {
  websites: {
    brand: ["مدى للأعمال", "Mada Business", "Mada-Geschäft"],
    headline: ["موقع شركة يشرح الخدمة ويجمع الطلبات", "A company site that explains the offer and captures enquiries", "Eine Unternehmensseite, die das Angebot erläutert und Anfragen erfasst"],
    description: ["صفحة رئيسية، وصفحات خدمات، وعناصر تعزز الثقة، ونموذج طلب واحد.", "Homepage, services, trust signals and one focused enquiry form.", "Homepage, Services, Vertrauenssignale und ein fokussiertes Anfrageformular."],
    action: ["جرّب إرسال طلب", "Try an enquiry", "Versuchen Sie es mit einer Anfrage"], result: ["تم تجهيز طلب تجريبي للمتابعة", "Demo enquiry prepared for follow-up", "Demo-Anfrage zur Nachverfolgung vorbereitet"],
    client: { label: ["واجهة الموقع", "Website view", "Website-Ansicht"], title: ["ما يراه الزائر", "Visitor experience", "Besuchererlebnis"], rows: [["⌂", ["صفحة رئيسية مقنعة", "Focused homepage", "Fokussierte Homepage"], ["عرض القيمة خلال ثوانٍ", "Value explained in seconds", "Wert in Sekunden erklärt"], ["جاهزة", "Ready", "Bereit"]], ["▦", ["صفحات خدمات مستقلة", "Dedicated service pages", "Spezielle Serviceseiten"], ["تفاصيل وفوائد وأسئلة شائعة", "Details, value and FAQs", "Details, Wert und FAQs"], ["منظمة", "Structured", "Strukturiert"]], ["✉", ["نموذج طلب مختصر", "Short enquiry form", "Kurzes Anfrageformular"], ["الاسم ووسيلة التواصل", "Name and preferred contact", "Name und bevorzugter Kontakt"], ["آمن", "Protected", "Geschützt"]]] },
    admin: { label: ["صندوق الطلبات", "Enquiry inbox", "Anfrage-Posteingang"], title: ["ما يراه صاحب العمل", "Business view", "Geschäftsansicht"], rows: [["01", ["طلب موقع شركة", "Company website enquiry", "Anfrage zur Unternehmenswebsite"], ["بغداد • وصل اليوم", "Baghdad • today", "Bagdad • heute"], ["جديد", "New", "Neu"]], ["02", ["تحديث متجر موجود", "Store refresh", "Ladenaktualisierung"], ["أربيل • بانتظار الرد", "Erbil • awaiting reply", "Erbil • wartet auf Antwort"], ["متابعة", "Follow-up", "Nachverfolgen"]], ["03", ["صفحة هبوط لحملة", "Campaign landing page", "Zielseite der Kampagne"], ["البصرة • نطاق واضح", "Basra • scope clear", "Basra • Zielfernrohr klar"], ["مؤهل", "Qualified", "Qualifiziert"]]] },
    stats: [["2", ["لغتان", "languages", "Sprachen"]], ["06", ["صفحات أساسية", "core pages", "Kernseiten"]], ["24/7", ["استقبال طلبات", "enquiry access", "Anfragezugang"]]], flow: [["يدخل الزائر", "Visitor arrives", "Besucher kommt"], ["يفهم العرض", "Understands offer", "Versteht Angebot"], ["يرسل الطلب", "Sends enquiry", "Sendet eine Anfrage"]], tone: "cyan",
  },
  "web-apps": {
    brand: ["بوابة الخدمة", "Service Portal", "Serviceportal"], headline: ["تطبيق ويب لرحلة مستخدم كاملة", "A web app for a complete user journey", "Eine Web-App für eine vollständige User Journey"], description: ["حساب مستخدم وطلب خدمة ومتابعة حالة وإشعارات.", "Account, service request, status tracking and notifications.", "Konto, Serviceanfrage, Statusverfolgung und Benachrichtigungen."], action: ["أنشئ طلبًا تجريبيًا", "Create a demo request", "Erstellen Sie eine Demo-Anfrage"], result: ["أُنشئ الطلب وانتقل إلى المراجعة", "Request created and moved to review", "Anfrage erstellt und zur Überprüfung verschoben"],
    client: { label: ["تطبيق المستخدم", "User app", "Benutzer-App"], title: ["رحلة المستخدم", "User journey", "Benutzerreise"], rows: [["＋", ["طلب خدمة جديد", "New service request", "Neue Serviceanfrage"], ["خطوات قصيرة وواضحة", "Short guided steps", "Kurze geführte Schritte"], ["ابدأ", "Start", "Start"]], ["◉", ["متابعة الطلب", "Track request", "Anfrage verfolgen"], ["آخر تحديث قبل 8 دقائق", "Updated 8 minutes ago", "Vor 8 Minuten aktualisiert"], ["قيد العمل", "In progress", "Im Gange"]], ["✦", ["الإشعارات", "Notifications", "Benachrichtigungen"], ["تنبيه عند كل تغيير", "Alert on each change", "Benachrichtigung bei jeder Änderung"], ["مفعلة", "Active", "Aktiv"]]] },
    admin: { label: ["لوحة المشرف", "Admin dashboard", "Admin-Dashboard"], title: ["إدارة العمليات", "Operations control", "Betriebskontrolle"], rows: [["A", ["طلبات تحتاج مراجعة", "Requests to review", "Bitte um Überprüfung"], ["6 طلبات حسب الأولوية", "6 requests by priority", "6 Anfragen nach Priorität"], ["06", "06"]], ["B", ["مهام الفريق", "Team workload", "Arbeitsbelastung des Teams"], ["12 مهمة موزعة", "12 assigned tasks", "12 zugewiesene Aufgaben"], ["متوازن", "Balanced", "Ausgewogen"]], ["C", ["نشاط النظام", "System activity", "Systemaktivität"], ["سجل واضح للتغييرات", "Clear change log", "Änderungsprotokoll löschen"], ["مباشر", "Live", "Live"]]] },
    stats: [["128", ["مستخدمًا تجريبيًا", "demo users", "Demo-Benutzer"]], ["18", ["طلبًا نشطًا", "active requests", "aktive Anfragen"]], ["04", ["صلاحيات", "roles", "Rollen"]]], flow: [["ينشئ حسابًا", "Creates account", "Erstellt ein Konto"], ["يرسل الطلب", "Submits request", "Sendet die Anfrage"], ["يتابع الحالة", "Tracks status", "Verfolgt den Status"]], tone: "violet",
  },
  commerce: {
    brand: ["سوق دجلة", "Tigris Market", "Tigris-Markt"], headline: ["متجر وطلبات مصممة لطريقة البيع المحلية", "Commerce designed around local selling workflows", "Der Handel ist auf lokale Verkaufsabläufe ausgelegt"], description: ["كتالوج وسلة وتوصيل ومتابعة طلب بلا تعقيد.", "Catalogue, cart, delivery and order tracking without friction.", "Reibungslose Katalog-, Warenkorb-, Liefer- und Bestellverfolgung."], action: ["أضف طلبًا تجريبيًا", "Add a demo order", "Fügen Sie eine Demobestellung hinzu"], result: ["أُضيف الطلب إلى قائمة التجهيز", "Demo order added to the packing queue", "Demobestellung zur Packwarteschlange hinzugefügt"],
    client: { label: ["واجهة المتجر", "Storefront", "Schaufenster"], title: ["منتجات مقترحة", "Featured products", "Ausgewählte Produkte"], rows: [["◇", ["سلة تمور فاخرة", "Premium date basket", "Premium-Dattelkorb"], ["متوفر • 28,000 د.ع", "Available • IQD 28,000", "Verfügbar • IQD 28.000"], ["أضف", "Add", "Hinzufügen"]], ["□", ["قهوة عراقية", "Iraqi coffee", "Irakischer Kaffee"], ["متوفر • 12,000 د.ع", "Available • IQD 12,000", "Verfügbar • IQD 12.000"], ["أضف", "Add", "Hinzufügen"]], ["△", ["باقة هدية", "Gift bundle", "Geschenkpaket"], ["كمية محدودة • 35,000 د.ع", "Low stock • IQD 35,000", "Geringer Lagerbestand • IQD 35.000"], ["أضف", "Add", "Hinzufügen"]]] },
    admin: { label: ["إدارة الطلبات", "Order management", "Auftragsverwaltung"], title: ["قائمة التجهيز", "Packing queue", "Packwarteschlange"], rows: [["#", ["طلب #1042", "Order #1042", "Bestellnr. 1042"], ["الكرادة • توصيل", "Karrada • delivery", "Karrada • Lieferung"], ["للتجهيز", "To pack", "Zum Packen"]], ["#", ["طلب #1041", "Order #1041", "Bestellnr. 1041"], ["المنصور • استلام", "Mansour • pickup", "Mansour • Abholung"], ["مؤكد", "Confirmed", "Bestätigt"]], ["#", ["طلب #1040", "Order #1040", "Bestellnr. 1040"], ["زيونة • توصيل", "Zayouna • delivery", "Zayouna • Lieferung"], ["في الطريق", "On route", "Unterwegs"]]] },
    stats: [["48", ["منتجًا", "products", "Produkte"]], ["12", ["طلبًا اليوم", "orders today", "Bestellungen heute"]], ["3", ["مناطق توصيل", "delivery zones", "Lieferzonen"]]], flow: [["يختار المنتج", "Selects product", "Wählt Produkt aus"], ["يؤكد التفاصيل", "Confirms details", "Bestätigt Details"], ["يتابع الطلب", "Tracks order", "Verfolgt die Reihenfolge"]], tone: "amber",
  },
  "management-systems": {
    brand: ["نظام المدار", "Madar OS", "Madar OS"], headline: ["لوحة تشغيل تجمع العمل في مكان واحد", "An operations dashboard that brings work together", "Ein Betriebs-Dashboard, das die Arbeit zusammenführt"], description: ["العملاء والمهام والملفات والمؤشرات حسب صلاحيات الفريق.", "Customers, tasks, files and indicators with team permissions.", "Kunden, Aufgaben, Dateien und Indikatoren mit Teamberechtigungen."], action: ["أضف مهمة تجريبية", "Add a demo task", "Fügen Sie eine Demo-Aufgabe hinzu"], result: ["أُضيفت المهمة وأُسندت إلى الفريق", "Task added and assigned to the team", "Aufgabe hinzugefügt und dem Team zugewiesen"],
    client: { label: ["ملخص الإدارة", "Management summary", "Zusammenfassung des Managements"], title: ["نظرة عامة", "Overview", "Überblick"], rows: [["▦", ["مشروع فرع بغداد", "Baghdad branch project", "Zweigstellenprojekt in Bagdad"], ["المرحلة الثالثة من خمس", "Stage three of five", "Stufe drei von fünf"], ["يسير جيدًا", "On track", "Auf dem richtigen Weg"]], ["◫", ["طلبات الموافقة", "Approval requests", "Genehmigungsanfragen"], ["3 عناصر تحتاج قرارًا", "3 items need a decision", "3 Punkte erfordern eine Entscheidung"], ["مراجعة", "Review", "Rezension"]], ["↗", ["التقرير الأسبوعي", "Weekly report", "Wochenbericht"], ["تم تحديثه اليوم", "Updated today", "Heute aktualisiert"], ["جاهز", "Ready", "Bereit"]]] },
    admin: { label: ["عمل الفريق", "Team workspace", "Team-Arbeitsbereich"], title: ["المهام المفتوحة", "Open tasks", "Offene Aufgaben"], rows: [["01", ["مراجعة عرض السعر", "Review quotation", "Überprüfen Sie das Angebot"], ["مسندة إلى سارة", "Assigned to Sara", "Sara zugewiesen"], ["اليوم", "Today", "Heute"]], ["02", ["رفع مخطط الإصدار", "Upload revision plan", "Revisionsplan hochladen"], ["مسندة إلى أحمد", "Assigned to Ahmed", "Ahmed zugewiesen"], ["غدًا", "Tomorrow", "Morgen"]], ["03", ["تأكيد استلام المواد", "Confirm materials receipt", "Bestätigen Sie den Materialeingang"], ["مسندة إلى علي", "Assigned to Ali", "Ali zugewiesen"], ["مفتوحة", "Open", "Offen"]]] },
    stats: [["34", ["مهمة نشطة", "active tasks", "aktive Aufgaben"]], ["09", ["مشاريع", "projects", "Projekte"]], ["92%", ["اكتمال البيانات", "data complete", "Daten vollständig"]]], flow: [["تُسجَّل المعلومة", "Record information", "Informationen aufzeichnen"], ["تُسنَد المسؤولية", "Assign ownership", "Eigentum zuweisen"], ["تظهر النتيجة", "See outcome", "Siehe Ergebnis"]], tone: "green",
  },
  "booking-crm": {
    brand: ["موعد ومتابعة", "Book & Follow", "Buchen und folgen"], headline: ["نظام حجز ومتابعة لا يُضيّع موعدًا أو فرصة", "Booking and CRM that misses no appointment or lead", "Buchung und CRM, die keinen Termin oder Lead verpassen"], description: ["تقويم مركزي، وملف للعميل، ومراحل متابعة قابلة للقياس.", "Central calendar, customer profile and measurable follow-up stages.", "Zentraler Kalender, Kundenprofil und messbare Folgephasen."], action: ["احجز موعدًا تجريبيًا", "Book a demo slot", "Buchen Sie einen Demo-Slot"], result: ["تم حجز الموعد وإضافته إلى المتابعة", "Appointment booked and added to follow-up", "Termin gebucht und zur Nachverfolgung hinzugefügt"],
    client: { label: ["صفحة الحجز", "Booking page", "Buchungsseite"], title: ["المواعيد المتاحة", "Available slots", "Verfügbare Slots"], rows: [["09", ["الأحد 09:30", "Sunday 09:30", "Sonntag 09:30"], ["استشارة أولية • 30 دقيقة", "Initial consult • 30 min", "Erstberatung • 30 Min"], ["متاح", "Available", "Verfügbar"]], ["11", ["الأحد 11:00", "Sunday 11:00", "Sonntag 11:00"], ["اجتماع مشروع • 45 دقيقة", "Project meeting • 45 min", "Projekttreffen • 45 Min"], ["متاح", "Available", "Verfügbar"]], ["02", ["الاثنين 14:00", "Monday 14:00", "Montag 14:00"], ["متابعة • 20 دقيقة", "Follow-up • 20 min", "Nachbereitung • 20 Min"], ["متاح", "Available", "Verfügbar"]]] },
    admin: { label: ["خط المتابعة", "Follow-up pipeline", "Folgepipeline"], title: ["العملاء اليوم", "Today's customers", "Die Kunden von heute"], rows: [["م", ["مريم خالد", "Maryam Khalid", "Maryam Khalid"], ["09:30 • استشارة", "09:30 • consultation", "09:30 • Beratung"], ["مؤكد", "Confirmed", "Bestätigt"]], ["ع", ["علي حسن", "Ali Hassan", "Ali Hassan"], ["11:00 • مشروع جديد", "11:00 • new project", "11:00 • neues Projekt"], ["يحتاج ردًا", "Needs reply", "Benötigt eine Antwort"]], ["س", ["سارة كريم", "Sara Kareem", "Sara Kareem"], ["14:00 • متابعة", "14:00 • follow-up", "14:00 Uhr • Nachbereitung"], ["تم التذكير", "Reminded", "Erinnert"]]] },
    stats: [["08", ["مواعيد اليوم", "today's bookings", "Die heutigen Buchungen"]], ["03", ["فرص متابعة", "follow-ups", "Folgemaßnahmen"]], ["0", ["تداخلات", "conflicts", "Konflikte"]]], flow: [["يختار الموعد", "Selects time", "Wählt die Zeit aus"], ["يصل التأكيد", "Gets confirmation", "Erhält eine Bestätigung"], ["تبدأ المتابعة", "Follow-up starts", "Die Nachverfolgung beginnt"]], tone: "cyan",
  },
  automation: {
    brand: ["مسار آلي", "AutoFlow", "AutoFlow"], headline: ["مسار يُحرّك البيانات بدلًا من نسخها يدويًا", "A workflow that moves data without manual copying", "Ein Workflow, der Daten ohne manuelles Kopieren verschiebt"], description: ["من النموذج إلى المسؤول ونظام CRM والتقرير، وفق قواعد واضحة.", "From form to owner, CRM and report through clear rules.", "Vom Formular über Eigentümer, CRM und Bericht durch klare Regeln."], action: ["شغّل المسار التجريبي", "Run demo workflow", "Führen Sie den Demo-Workflow aus"], result: ["اكتملت أربع خطوات آلية خلال ثانيتين", "Four automated steps completed in two seconds", "Vier automatisierte Schritte in zwei Sekunden erledigt"],
    client: { label: ["بداية المسار", "Workflow input", "Workflow-Eingabe"], title: ["طلب جديد", "New request", "Neue Anfrage"], rows: [["①", ["استقبال النموذج", "Capture form", "Formular erfassen"], ["التحقق من الحقول", "Validate fields", "Felder validieren"], ["جاهز", "Ready", "Bereit"]], ["②", ["تصنيف الطلب", "Classify request", "Anfrage klassifizieren"], ["حسب الخدمة والمحافظة", "By service and governorate", "Nach Dienst und Gouvernement"], ["تلقائي", "Automatic", "Automatisch"]], ["③", ["توجيه المسؤول", "Assign owner", "Besitzer zuweisen"], ["إنشاء مهمة وتنبيه", "Create task and notify", "Aufgabe erstellen und benachrichtigen"], ["تلقائي", "Automatic", "Automatisch"]]] },
    admin: { label: ["سجل التنفيذ", "Execution log", "Ausführungsprotokoll"], title: ["آخر عمليات التشغيل", "Recent workflow runs", "Letzte Workflow-Ausführungen"], rows: [["✓", ["تم إنشاء سجل CRM", "CRM record created", "CRM-Datensatz erstellt"], ["طلب تجريبي #204", "Demo request #204", "Demoanfrage Nr. 204"], ["نجح", "Passed", "Bestanden"]], ["✓", ["تم إشعار المسؤول", "Owner notified", "Besitzer benachrichtigt"], ["فريق المبيعات", "Sales team", "Vertriebsteam"], ["نجح", "Passed", "Bestanden"]], ["✓", ["تم تحديث التقرير", "Report updated", "Bericht aktualisiert"], ["لوحة اليوم", "Today's dashboard", "Das heutige Dashboard"], ["نجح", "Passed", "Bestanden"]]] },
    stats: [["4", ["خطوات آلية", "automated steps", "automatisierte Schritte"]], ["2s", ["وقت التنفيذ", "run time", "Laufzeit"]], ["0", ["عمليات نقل يدوية", "manual copies", "manuelle Kopien"]]], flow: [["الاستقبال", "Capture", "Erfassen"], ["التحقق والتصنيف", "Validate & classify", "Validieren und klassifizieren"], ["التنفيذ والإشعار", "Act & notify", "Handeln und benachrichtigen"]], tone: "violet",
  },
  "performance-care": {
    brand: ["فحص المنصة", "Platform Check", "Plattformcheck"], headline: ["لوحة فحص للأداء والحماية والصيانة", "A health dashboard for performance, security and maintenance", "Ein Gesundheits-Dashboard für Leistung, Sicherheit und Wartung"], description: ["ما المشكلة وما أثرها وما الذي يُصلح أولًا.", "What is wrong, why it matters and what to fix first.", "Was ist falsch, warum ist es wichtig und was muss zuerst behoben werden?"], action: ["شغّل فحصًا تجريبيًا", "Run demo audit", "Führen Sie ein Demo-Audit durch"], result: ["اكتمل الفحص: 3 تحسينات ذات أولوية", "Audit complete: three priority improvements", "Audit abgeschlossen: drei vorrangige Verbesserungen"],
    client: { label: ["نتيجة الفحص", "Audit result", "Audit-Ergebnis"], title: ["صحة الموقع", "Site health", "Website-Zustand"], rows: [["↯", ["سرعة الصفحة الرئيسية", "Homepage speed", "Homepage-Geschwindigkeit"], ["زمن عرض المحتوى الأساسي", "Main content render time", "Renderzeit des Hauptinhalts"], ["1.4 ثانية", "1.4 sec", "1,4 Sek"]], ["⌾", ["الروابط والفهرسة", "Links and indexing", "Links und Indizierung"], ["لا توجد روابط مكسورة", "No broken links", "Keine defekten Links"], ["سليم", "Healthy", "Gesund"]], ["▣", ["النسخ الاحتياطي", "Backups", "Backups"], ["نسخة أسبوعية مشفرة", "Encrypted weekly copy", "Verschlüsselte wöchentliche Kopie"], ["نشط", "Active", "Aktiv"]]] },
    admin: { label: ["خطة التحسين", "Improvement plan", "Verbesserungsplan"], title: ["الإجراءات المقترحة", "Recommended actions", "Empfohlene Maßnahmen"], rows: [["01", ["ضغط الصور", "Compress images", "Bilder komprimieren"], ["أثر مرتفع • جهد منخفض", "High impact • low effort", "Hohe Wirkung • geringer Aufwand"], ["أولوية", "Priority", "Priorität"]], ["02", ["تحديث الحزم", "Update packages", "Pakete aktualisieren"], ["أثر أمني", "Security impact", "Auswirkungen auf die Sicherheit"], ["مجدول", "Scheduled", "Geplant"]], ["03", ["مراقبة التوفر", "Uptime monitoring", "Überwachung der Betriebszeit"], ["تنبيه عند الانقطاع", "Alert on downtime", "Benachrichtigung bei Ausfallzeiten"], ["مقترح", "Proposed", "Vorgeschlagen"]]] },
    stats: [["92", ["درجة الأداء", "performance score", "Leistungsbewertung"]], ["A", ["أساسيات الأمان", "security baseline", "Sicherheitsgrundlinie"]], ["7d", ["آخر نسخة", "latest backup", "letztes Backup"]]], flow: [["نفحص", "Audit", "Prüfung"], ["نرتب الأولويات", "Prioritise", "Priorisieren"], ["نُنفّذ ونراقب", "Improve & monitor", "Verbessern und überwachen"]], tone: "green",
  },
};

type SectorDemoSeed = {
  brand: Pair;
  headline: Pair;
  description: Pair;
  action: Pair;
  result: Pair;
  clientLabel: Pair;
  clientTitle: Pair;
  clientRows: DemoRow[];
  adminLabel: Pair;
  adminTitle: Pair;
  adminRows: DemoRow[];
  stats: ContextDemo["stats"];
  flow: Pair[];
  tone: ContextDemo["tone"];
};

const sectorDemo = (seed: SectorDemoSeed): ContextDemo => ({
  brand: seed.brand,
  headline: seed.headline,
  description: seed.description,
  action: seed.action,
  result: seed.result,
  client: { label: seed.clientLabel, title: seed.clientTitle, rows: seed.clientRows },
  admin: { label: seed.adminLabel, title: seed.adminTitle, rows: seed.adminRows },
  stats: seed.stats,
  flow: seed.flow,
  tone: seed.tone,
});

const expandedIndustryDemos: Record<string, ContextDemo> = {
  "law-firms": sectorDemo({
    brand: ["ميزان للمحاماة", "Mizan Law", "Mizan-Gesetz"], headline: ["مكتب قانوني يستقبل الاستشارة وينظّم الملف بسرية", "A legal practice that captures enquiries and organises matters privately", "Eine Anwaltskanzlei, die Anfragen entgegennimmt und Angelegenheiten privat organisiert"], description: ["نوع الاستشارة والموعد وقائمة المستندات وحالة الملف في مساحة مهنية واحدة.", "Consultation type, appointment, document checklist and matter status in one professional space.", "Beratungsart, Termin, Dokumentencheckliste und Sachstand in einem professionellen Bereich."], action: ["أرسل طلب استشارة تجريبيًا", "Send a demo consultation request", "Senden Sie eine Demo-Beratungsanfrage"], result: ["أُنشئ ملف استشارة خيالي وحُدّد موعد المراجعة", "Fictional consultation file created and review scheduled", "Fiktive Konsultationsdatei erstellt und Überprüfung geplant"],
    clientLabel: ["بوابة الموكل", "Client portal", "Kundenportal"], clientTitle: ["طلب استشارة أولية", "Initial consultation request", "Erstberatungsanfrage"], clientRows: [["§", ["استشارة شركات", "Corporate consultation", "Unternehmensberatung"], ["تأسيس وعقود تجارية", "Formation and commercial contracts", "Gründung und Handelsverträge"], ["اختر", "Select", "Wählen"]], ["⌘", ["نزاع مدني", "Civil matter", "Zivilsache"], ["مراجعة أولية للمستندات", "Initial document review", "Erste Dokumentenprüfung"], ["اختر", "Select", "Wählen"]], ["◷", ["موعد استشارة", "Consultation slot", "Beratungsslot"], ["الثلاثاء • 11:30", "Tuesday • 11:30", "Dienstag • 11:30"], ["متاح", "Available", "Verfügbar"]]],
    adminLabel: ["إدارة الملفات", "Matter management", "Materiemanagement"], adminTitle: ["ملفات تحتاج متابعة", "Matters requiring follow-up", "Angelegenheiten, die einer Nachverfolgung bedürfen"], adminRows: [["L1", ["ملف #L-204", "Matter #L-204", "Materie Nr. L-204"], ["قائمة المستندات مكتملة", "Document list complete", "Dokumentenliste vollständig"], ["مراجعة", "Review", "Rezension"]], ["L2", ["موعد استشارة", "Consultation appointment", "Beratungstermin"], ["اليوم • 14:00", "Today • 14:00", "Heute • 14:00"], ["مؤكد", "Confirmed", "Bestätigt"]], ["L3", ["مهلة إجرائية", "Procedural deadline", "Verfahrensfrist"], ["بعد 4 أيام", "In 4 days", "In 4 Tagen"], ["تنبيه", "Alert", "Alarm"]]],
    stats: [["12", ["ملفًا نشطًا", "active matters", "aktive Angelegenheiten"]], ["04", ["مواعيد اليوم", "appointments today", "Termine heute"]], ["03", ["تنبيهات", "alerts", "Warnungen"]]], flow: [["يصف الطلب", "Describe request", "Bitte beschreiben Sie die Anfrage"], ["يضيف المستندات", "Add documents", "Dokumente hinzufügen"], ["يُحدّد الموعد", "Schedule meeting", "Termin vereinbaren"]], tone: "violet",
  }),
  "private-schools": sectorDemo({
    brand: ["مدارس الرافدين", "Rafidain Schools", "Rafidain-Schulen"], headline: ["تسجيل مدرسي وبوابة تجمع الإدارة وولي الأمر", "Admissions and a portal connecting school and parent", "Zulassungen und ein Portal, das Schule und Eltern verbindet"], description: ["طلب تسجيل وجدول وحضور وأقساط وإعلانات بحسب الصف.", "Admissions, timetable, attendance, fees and class-based announcements.", "Zulassungen, Stundenplan, Anwesenheit, Gebühren und klassenbezogene Ankündigungen."], action: ["أرسل طلب تسجيل تجريبيًا", "Send a demo admission", "Senden Sie eine Demo-Zulassung"], result: ["أُضيف طلب التسجيل الخيالي إلى مراجعة الصف الرابع", "Fictional admission added to grade-four review", "Fiktive Zulassung zur Rezension der vierten Klasse hinzugefügt"],
    clientLabel: ["بوابة ولي الأمر", "Parent portal", "Elternportal"], clientTitle: ["يوم الطالب", "Student day", "Studententag"], clientRows: [["▤", ["الجدول الدراسي", "Class timetable", "Stundenplan"], ["العربية • الرياضيات • العلوم", "Arabic • maths • science", "Arabisch • Mathematik • Naturwissenschaften"], ["اليوم", "Today", "Heute"]], ["✓", ["الحضور", "Attendance", "Teilnahme"], ["حاضر منذ 07:42", "Present since 07:42", "Anwesend seit 07:42"], ["مؤكد", "Confirmed", "Bestätigt"]], ["$", ["القسط القادم", "Next fee", "Nächste Gebühr"], ["يستحق في 25 آب", "Due 25 Aug", "Fällig am 25. August"], ["قادم", "Upcoming", "Demnächst"]]],
    adminLabel: ["إدارة المدرسة", "School office", "Schulbüro"], adminTitle: ["طلبات التسجيل", "Admission applications", "Zulassungsanträge"], adminRows: [["4A", ["طلب الصف الرابع", "Grade four application", "Bewerbung der vierten Klasse"], ["البيانات الأساسية مكتملة", "Core data complete", "Kerndaten vollständig"], ["مراجعة", "Review", "Rezension"]], ["1B", ["طلب الصف الأول", "Grade one application", "Bewerbung der ersten Klasse"], ["يحتاج وثيقة واحدة", "Needs one document", "Benötigt ein Dokument"], ["ناقص", "Incomplete", "Unvollständig"]], ["6A", ["مقاعد الصف السادس", "Grade six places", "Sechste Plätze belegen"], ["تبقى 8 مقاعد", "8 places remain", "Es sind noch 8 Plätze übrig"], ["متاح", "Available", "Verfügbar"]]],
    stats: [["418", ["طالبًا تجريبيًا", "demo students", "Demo-Studenten"]], ["96%", ["حضور اليوم", "attendance today", "Anwesenheit heute"]], ["08", ["طلبات جديدة", "new applications", "neue Anwendungen"]]], flow: [["يُكمل الطلب", "Complete application", "Vollständige Bewerbung"], ["تراجعه الإدارة", "Office review", "Bürobewertung"], ["يصل القرار", "Receive decision", "Entscheidung erhalten"]], tone: "cyan",
  }),
  kindergartens: sectorDemo({
    brand: ["روضة غيمة", "Ghaima Nursery", "Ghaima-Kindergarten"], headline: ["يوم الطفل يصل إلى الأهل بصورة لطيفة ومنظمة", "A child’s day shared with parents in a warm organised way", "Ein gemeinsamer Kindertag mit den Eltern auf herzliche, organisierte Art und Weise"], description: ["الأنشطة والوجبات والقيلولة وملاحظات المربية، دون استخدام بيانات أطفال حقيقية.", "Activities, meals, naps and educator notes, with no real children’s data.", "Aktivitäten, Mahlzeiten, Nickerchen und Notizen von Pädagogen, ohne echte Kinderdaten."], action: ["أضف تحديثًا يوميًا تجريبيًا", "Add a demo daily update", "Fügen Sie ein tägliches Demo-Update hinzu"], result: ["أُضيف تحديث خيالي عن نشاط الرسم", "Fictional painting activity update added", "Aktualisierung der fiktiven Malaktivität hinzugefügt"],
    clientLabel: ["ملخص اليوم", "Daily summary", "Tägliche Zusammenfassung"], clientTitle: ["يوم مليء بالاكتشاف", "A day of discovery", "Ein Tag voller Entdeckungen"], clientRows: [["☀", ["استقبال صباحي", "Morning welcome", "Willkommen am Morgen"], ["دخلت المجموعة عند 08:05", "Group arrived at 08:05", "Die Gruppe traf um 08:05 Uhr ein"], ["تم", "Done", "Erledigt"]], ["✿", ["نشاط الألوان", "Colour activity", "Farbaktivität"], ["رسم وتعرّف إلى الأشكال", "Painting and shape discovery", "Malerei und Formenfindung"], ["اليوم", "Today", "Heute"]], ["☾", ["وقت الراحة", "Rest time", "Ruhezeit"], ["13:00 — 14:00", "13:00 — 14:00"], ["قادم", "Upcoming", "Demnächst"]]],
    adminLabel: ["لوحة المربيات", "Educator board", "Pädagogischer Vorstand"], adminTitle: ["تحديثات المجموعة", "Group updates", "Gruppenaktualisierungen"], adminRows: [["أ", ["مجموعة الأقحوان", "Daisy group", "Daisy-Gruppe"], ["12 طفلًا • حضور كامل", "12 children • full attendance", "12 Kinder • volle Anwesenheit"], ["جيد", "Good", "Gut"]], ["و", ["وجبة اليوم", "Today’s meal", "Das heutige Essen"], ["تم تسجيل الحساسية مسبقًا", "Allergies pre-recorded", "Allergien vorab aufgezeichnet"], ["جاهزة", "Ready", "Bereit"]], ["ر", ["رسالة إلى الأهل", "Parent note", "Hinweis für Eltern"], ["مستلزمات نشاط الخميس", "Thursday activity supplies", "Aktivitätszubehör für Donnerstag"], ["إرسال", "Send", "Schicken"]]],
    stats: [["12", ["طفلًا في المجموعة", "children in group", "Kinder in der Gruppe"]], ["04", ["أنشطة اليوم", "activities today", "Aktivitäten heute"]], ["100%", ["اكتمال التحديث", "update complete", "Update abgeschlossen"]]], flow: [["تُسجّل المربية", "Educator records", "Aufzeichnungen von Pädagogen"], ["يصل الملخص", "Summary arrives", "Zusammenfassung kommt"], ["يتابع الأهل", "Parents follow", "Die Eltern folgen"]], tone: "amber",
  }),
  "medical-labs": sectorDemo({
    brand: ["مختبر بيّنة", "Bayina Lab", "Bayina-Labor"], headline: ["من طلب الفحص إلى نتيجة جاهزة برمز تحقق", "From test request to a result protected by a verification code", "Von der Testanfrage bis zum durch einen Verifizierungscode geschützten Ergebnis"], description: ["دليل تحضيرات وحالة عينة وتنبيه جاهزية، من دون بيانات صحية حقيقية.", "Preparation guide, sample status and result alert, with no real health data.", "Vorbereitungsanleitung, Probenstatus und Ergebniswarnung, ohne echte Gesundheitsdaten."], action: ["حرّك العينة التجريبية", "Advance the demo sample", "Erweitern Sie das Demo-Beispiel"], result: ["انتقلت العينة الخيالية إلى مرحلة اعتماد النتيجة", "Fictional sample moved to result approval", "Fiktive Stichprobe wurde in die Ergebnisgenehmigung verschoben"],
    clientLabel: ["دليل الفحوصات", "Test guide", "Testübersicht"], clientTitle: ["فحوصات شائعة", "Common tests", "Häufige Untersuchungen"], clientRows: [["⚗", ["فحص دم عام", "Complete blood count", "Großes Blutbild"], ["لا يحتاج إلى صيام", "No fasting required", "Kein Fasten erforderlich"], ["متاح", "Available", "Verfügbar"]], ["◌", ["وظائف الغدة", "Thyroid panel", "Schilddrüsenprofil"], ["تعليمات قبل الزيارة", "Pre-visit guidance", "Hinweise vor dem Termin"], ["عرض", "View", "Ansehen"]], ["⌂", ["سحب منزلي", "Home collection", "Probenentnahme zu Hause"], ["مناطق مختارة في بغداد", "Selected Baghdad areas", "Ausgewählte Gebiete in Bagdad"], ["اطلب", "Request", "Anfragen"]]],
    adminLabel: ["مسار العينات", "Sample workflow", "Beispiel-Workflow"], adminTitle: ["العينات النشطة", "Active samples", "Aktive Proben"], adminRows: [["S1", ["عينة #B-142", "Sample #B-142", "Probe Nr. B-142"], ["تم الاستلام 09:12", "Received 09:12", "Erhalten um 09:12 Uhr"], ["قيد الفحص", "Testing", "Testen"]], ["S2", ["عينة #B-141", "Sample #B-141", "Probe Nr. B-141"], ["بانتظار الاعتماد", "Awaiting approval", "Warten auf Genehmigung"], ["مراجعة", "Review", "Rezension"]], ["S3", ["نتيجة #B-139", "Result #B-139", "Ergebnis #B-139"], ["جاهزة برمز تحقق", "Ready with verification", "Bereit mit Verifizierung"], ["جاهزة", "Ready", "Bereit"]]],
    stats: [["38", ["عينة اليوم", "samples today", "Proben heute"]], ["07", ["قيد الاعتماد", "awaiting approval", "warten auf Genehmigung"]], ["02", ["طلبات منزلية", "home requests", "Hausanfragen"]]], flow: [["تُسجّل العينة", "Register sample", "Probe registrieren"], ["تُفحص وتُراجع", "Test and review", "Testen und bewerten"], ["يصل التنبيه", "Send notification", "Benachrichtigung senden"]], tone: "green",
  }),
  pharmacies: sectorDemo({
    brand: ["صيدلية نبض", "Nabd Pharmacy", "Nabd-Apotheke"], headline: ["توافر ومخزون وطلب تجهيز بلا التباس", "Availability, inventory and preparation requests without confusion", "Verfügbarkeits-, Inventar- und Vorbereitungsanfragen ohne Verwirrung"], description: ["بحث عن منتجات صحية غير وصفية، واختيار فرع، ومتابعة التجهيز.", "Search non-prescription health products, choose a branch and track preparation.", "Suchen Sie nach rezeptfreien Gesundheitsprodukten, wählen Sie eine Filiale und verfolgen Sie die Zubereitung."], action: ["أرسل طلب تجهيز تجريبيًا", "Send a demo preparation request", "Senden Sie eine Demo-Vorbereitungsanfrage"], result: ["حُجز المنتج الخيالي في فرع المنصور لمدة محدودة", "Fictional item reserved at Mansour branch for a limited time", "Fiktiver Artikel, der für eine begrenzte Zeit in der Mansour-Filiale reserviert ist"],
    clientLabel: ["البحث والتوافر", "Search and availability", "Suche und Verfügbarkeit"], clientTitle: ["منتجات صحية", "Health products", "Gesundheitsprodukte"], clientRows: [["✚", ["جهاز قياس حرارة", "Thermometer", "Thermometer"], ["متوفر في فرعين", "Available at two branches", "Erhältlich in zwei Filialen"], ["متوفر", "Available", "Verfügbar"]], ["◇", ["ضمادات طبية", "Medical dressings", "Medizinische Verbände"], ["3 أحجام", "Three sizes", "Drei Größen"], ["اختر", "Choose", "Wählen"]], ["◌", ["عناية يومية", "Daily care", "Tägliche Pflege"], ["مجموعة منتجات مختارة", "Selected product range", "Ausgewähltes Produktsortiment"], ["تصفح", "Browse", "Durchsuchen"]]],
    adminLabel: ["إدارة الفرع", "Branch operations", "Filialbetrieb"], adminTitle: ["المخزون والطلبات", "Stock and requests", "Lagerbestand und Anfragen"], adminRows: [["P1", ["طلب تجهيز #P-82", "Prep request #P-82", "Vorbereitungsanfrage Nr. P-82"], ["فرع المنصور • منتجان", "Mansour • two items", "Mansour • zwei Artikel"], ["للتجهيز", "Prepare", "Vorbereiten"]], ["!", ["مخزون منخفض", "Low stock", "Geringer Lagerbestand"], ["ضمادات الحجم المتوسط", "Medium dressings", "Mittlere Dressings"], ["6 قطع", "6 left", "6 übrig"]], ["⇄", ["نقل بين الفروع", "Branch transfer", "Filialübertragung"], ["من زيونة إلى الكرادة", "Zayouna to Karrada", "Zayouna nach Karrada"], ["قيد النقل", "Moving", "Umzug"]]],
    stats: [["840", ["صنفًا تجريبيًا", "demo SKUs", "Demo-SKUs"]], ["16", ["طلب تجهيز", "prep requests", "Vorbereitungsanfragen"]], ["05", ["تنبيهات مخزون", "stock alerts", "Aktienwarnungen"]]], flow: [["يبحث عن المنتج", "Search item", "Suchelement"], ["يختار الفرع", "Choose branch", "Wählen Sie eine Filiale"], ["يستلم التأكيد", "Receive confirmation", "Bestätigung erhalten"]], tone: "cyan",
  }),
  "sports-clubs": sectorDemo({
    brand: ["نادي حركة", "Haraka Club", "Haraka-Club"], headline: ["عضوية وحصص ومدربون في جدول يشجع على الاستمرار", "Membership, classes and coaches in a schedule built for consistency", "Mitgliedschaft, Kurse und Trainer in einem auf Konsistenz ausgelegten Zeitplan"], description: ["اكتشاف الحصة وحجز المقعد وتسجيل الحضور ومتابعة العضوية.", "Discover a class, reserve a place, record attendance and track membership.", "Entdecken Sie einen Kurs, reservieren Sie einen Platz, erfassen Sie die Anwesenheit und verfolgen Sie die Mitgliedschaft."], action: ["احجز الحصة التجريبية", "Book the demo class", "Buchen Sie den Demokurs"], result: ["حُجز مقعد خيالي في حصة القوة عند 18:30", "Fictional place booked in the 18:30 strength class", "Fiktiver Platz im Kraftkurs 18:30 Uhr gebucht"],
    clientLabel: ["جدول العضو", "Member schedule", "Zeitplan für Mitglieder"], clientTitle: ["حصص اليوم", "Today’s classes", "Die heutigen Kurse"], clientRows: [["●", ["تمارين القوة", "Strength training", "Krafttraining"], ["18:30 • المدرب علي", "18:30 • Coach Ali", "18:30 • Trainer Ali"], ["4 مقاعد", "4 places", "4 Plätze"]], ["◒", ["لياقة وظيفية", "Functional fitness", "Funktionelle Fitness"], ["19:30 • القاعة B", "19:30 • Studio B", "19:30 • Studio B"], ["متاح", "Available", "Verfügbar"]], ["↗", ["جري جماعي", "Group run", "Gruppenlauf"], ["الجمعة • 07:00", "Friday • 07:00", "Freitag • 07:00"], ["انضم", "Join", "Verbinden"]]],
    adminLabel: ["تشغيل النادي", "Club operations", "Vereinsbetrieb"], adminTitle: ["الحصص والعضويات", "Classes and memberships", "Kurse und Mitgliedschaften"], adminRows: [["18", ["حصة القوة", "Strength class", "Kraftkurs"], ["16 من 20 مقعدًا", "16 of 20 places", "16 von 20 Plätzen"], ["مفتوحة", "Open", "Offen"]], ["M", ["عضويات تنتهي قريبًا", "Memberships expiring", "Mitgliedschaften laufen aus"], ["9 خلال هذا الأسبوع", "9 this week", "9 diese Woche"], ["متابعة", "Follow up", "Nachverfolgen"]], ["✓", ["حضور اليوم", "Attendance today", "Anwesenheit heute"], ["74 عضوًا", "74 members", "74 Mitglieder"], ["مباشر", "Live", "Live"]]],
    stats: [["126", ["عضوًا نشطًا", "active members", "aktive Mitglieder"]], ["11", ["حصة اليوم", "classes today", "Klassen heute"]], ["74", ["حضورًا", "check-ins", "Check-ins"]]], flow: [["يختار الحصة", "Choose class", "Klasse wählen"], ["يحجز المقعد", "Book place", "Buchplatz"], ["يُسجّل الحضور", "Check in", "Einchecken"]], tone: "violet",
  }),
  "beauty-salons": sectorDemo({
    brand: ["دار لمسة", "Lamsa Studio", "Lamsa Studio"], headline: ["حجز أنيق يبدأ بالخدمة وينتهي بموعد مؤكد", "A polished booking journey from service to confirmed appointment", "Eine ausgefeilte Buchungsreise vom Service bis zum bestätigten Termin"], description: ["خدمات وأسعار وأخصائيون وأوقات متاحة في واجهة تناسب الهاتف.", "Services, prices, specialists and available times in a mobile-friendly interface.", "Dienstleistungen, Preise, Spezialisten und verfügbare Zeiten in einer mobilfreundlichen Oberfläche."], action: ["أكّد الموعد التجريبي", "Confirm the demo appointment", "Bestätigen Sie den Demo-Termin"], result: ["تأكّد الموعد الخيالي مع نور عند 17:00", "Fictional appointment confirmed with Noor at 17:00", "Fiktiver Termin mit Noor um 17:00 Uhr bestätigt"],
    clientLabel: ["قائمة الخدمات", "Service menu", "Servicemenü"], clientTitle: ["اختاري تجربتك", "Choose your experience", "Wählen Sie Ihr Erlebnis"], clientRows: [["✦", ["تصفيف الشعر", "Hair styling", "Haarstyling"], ["45 دقيقة • من 25,000 د.ع", "45 min • from IQD 25,000", "45 Min. • ab IQD 25.000"], ["احجزي", "Book", "Buch"]], ["◇", ["العناية بالبشرة", "Skin care", "Hautpflege"], ["60 دقيقة • استشارة أولية", "60 min • initial consultation", "60 Min. • Erstgespräch"], ["اختاري", "Choose", "Wählen"]], ["◌", ["العناية بالأظافر", "Nail care", "Nagelpflege"], ["40 دقيقة • 3 أوقات", "40 min • 3 slots", "40 Min. • 3 Slots"], ["متاح", "Available", "Verfügbar"]]],
    adminLabel: ["رزنامة الصالون", "Salon calendar", "Salonkalender"], adminTitle: ["مواعيد اليوم", "Today’s appointments", "Die heutigen Termine"], adminRows: [["ن", ["نور", "Noor", "Noor"], ["17:00 • تصفيف شعر", "17:00 • styling", "17:00 • Styling"], ["مؤكد", "Confirmed", "Bestätigt"]], ["س", ["سارة", "Sara", "Sara"], ["18:00 • عناية بالبشرة", "18:00 • skin care", "18:00 • Hautpflege"], ["مؤكد", "Confirmed", "Bestätigt"]], ["ر", ["رُبى", "Ruba", "Ruba"], ["19:15 • وقت متاح", "19:15 • open slot", "19:15 • freier Slot"], ["متاح", "Available", "Verfügbar"]]],
    stats: [["14", ["موعدًا اليوم", "appointments today", "Termine heute"]], ["03", ["أخصائيات", "specialists", "Spezialisten"]], ["04", ["أوقات متاحة", "open slots", "offene Slots"]]], flow: [["تختار الخدمة", "Choose service", "Wählen Sie Service"], ["تختار الأخصائي", "Choose specialist", "Wählen Sie einen Spezialisten"], ["تؤكد الموعد", "Confirm time", "Uhrzeit bestätigen"]], tone: "amber",
  }),
  accounting: sectorDemo({
    brand: ["مكتب رصيد", "Raseed Office", "Rased-Büro"], headline: ["إقفال شهري واضح بدل مطاردة الملفات", "A clear monthly close instead of chasing files", "Ein klarer Monatsabschluss statt Aktenjagd"], description: ["قائمة وثائق ومهام ومراجعة وحالة نهائية لكل عميل.", "Documents, tasks, review and final status for every client.", "Dokumente, Aufgaben, Überprüfung und Endstatus für jeden Kunden."], action: ["أكمل مهمة تجريبية", "Complete a demo task", "Schließen Sie eine Demo-Aufgabe ab"], result: ["أُضيف كشف البنك الخيالي وانتقل الإقفال إلى المراجعة", "Fictional bank statement added and close moved to review", "Fiktiver Kontoauszug hinzugefügt und zur Überprüfung verschoben"],
    clientLabel: ["مساحة العميل", "Client workspace", "Client-Arbeitsbereich"], clientTitle: ["إقفال تموز", "July close", "Juli geschlossen"], clientRows: [["✓", ["فواتير المبيعات", "Sales invoices", "Verkaufsrechnungen"], ["24 ملفًا مرفوعًا", "24 files uploaded", "24 Dateien hochgeladen"], ["مكتمل", "Complete", "Vollständig"]], ["$", ["كشف الحساب المصرفي", "Bank statement", "Kontoauszug"], ["ملف واحد مطلوب", "One file required", "Eine Datei erforderlich"], ["ناقص", "Missing", "Fehlen"]], ["∑", ["ملخص المصروفات", "Expense summary", "Spesenübersicht"], ["قيد المراجعة", "Under review", "Wird überprüft"], ["مراجعة", "Review", "Rezension"]]],
    adminLabel: ["لوحة المكتب", "Office dashboard", "Kanzlei-Dashboard"], adminTitle: ["حالة العملاء", "Client status", "Mandantenstatus"], adminRows: [["A", ["شركة ألف", "Company Alef", "Firma Alef"], ["اكتمل 8 من 9", "8 of 9 complete", "8 von 9 abgeschlossen"], ["قريب", "Nearly done", "Fast fertig"]], ["B", ["متجر باء", "Store Baa", "Geschäft Baa"], ["ينقص ملفان", "Two files missing", "Zwei Dateien fehlen"], ["متابعة", "Follow up", "Nachverfolgen"]], ["C", ["مكتب جيم", "Office Jeem", "Büro Jeem"], ["جاهز للمراجعة", "Ready for review", "Bereit zur Überprüfung"], ["جاهز", "Ready", "Bereit"]]],
    stats: [["18", ["عميلًا نشطًا", "active clients", "aktive Kunden"]], ["82%", ["اكتمال الإقفال", "close complete", "Schließen abgeschlossen"]], ["07", ["ملفات ناقصة", "missing files", "fehlende Dateien"]]], flow: [["يرفع العميل", "Client uploads", "Client-Uploads"], ["يراجع المحاسب", "Accountant reviews", "Bewertungen von Buchhaltern"], ["يُغلق الشهر", "Close month", "Monat schließen"]], tone: "green",
  }),
  architecture: sectorDemo({
    brand: ["أثر للهندسة", "Athar Studio", "Athar Studio"], headline: ["مشروع معماري من الفكرة إلى اعتماد المخطط", "An architectural project from concept to drawing approval", "Ein Architekturprojekt vom Konzept bis zur Zeichnungsfreigabe"], description: ["معرض أعمال ومتطلبات وإصدارات مخططات وقرارات عميل موثقة.", "Portfolio, briefs, drawing revisions and recorded client decisions.", "Portfolio, Briefings, Zeichnungsüberarbeitungen und aufgezeichnete Kundenentscheidungen."], action: ["اعتمد الإصدار التجريبي", "Approve the demo revision", "Genehmigen Sie die Demo-Revision"], result: ["اعتُمد المخطط الخيالي R03 وانتقلت المرحلة إلى التصميم التفصيلي", "Fictional R03 plan approved and moved to detailed design", "Der fiktive R03-Plan wurde genehmigt und in den detaillierten Entwurf überführt"],
    clientLabel: ["بوابة المشروع", "Project portal", "Projektportal"], clientTitle: ["منزل الجادرية", "Jadriya House", "Jadriya-Haus"], clientRows: [["R1", ["المخطط الأولي", "Concept plan", "Konzeptplan"], ["اعتمد في 04 آب", "Approved 4 Aug", "Genehmigt am 4. August"], ["مكتمل", "Complete", "Vollständig"]], ["R3", ["توزيع الطابق الأرضي", "Ground-floor layout", "Grundriss im Erdgeschoss"], ["الإصدار الثالث • للمراجعة", "Revision three • review", "Revision drei • Überprüfung"], ["قرار", "Decision", "Entscheidung"]], ["3D", ["المشاهد الخارجية", "Exterior views", "Außenansichten"], ["4 مشاهد جاهزة", "Four views ready", "Vier Ansichten bereit"], ["جاهزة", "Ready", "Bereit"]]],
    adminLabel: ["إدارة المكتب", "Studio management", "Studioleitung"], adminTitle: ["المراحل والاعتمادات", "Stages and approvals", "Stufen und Genehmigungen"], adminRows: [["01", ["التصميم الأولي", "Concept design", "Konzeptdesign"], ["100%", "100%"], ["مكتمل", "Complete", "Vollständig"]], ["02", ["التصميم التفصيلي", "Detailed design", "Detailliertes Design"], ["يبدأ بعد الاعتماد", "Starts after approval", "Beginnt nach Genehmigung"], ["قادم", "Next", "Nächste"]], ["!", ["قرار العميل", "Client decision", "Kundenentscheidung"], ["توزيع الصالة", "Living area layout", "Aufteilung des Wohnbereichs"], ["مطلوب", "Required", "Erforderlich"]]],
    stats: [["03", ["إصدارات", "revisions", "Überarbeitungen"]], ["12", ["لوحة معتمدة", "approved sheets", "genehmigte Blätter"]], ["01", ["قرار مطلوب", "decision needed", "Entscheidung nötig"]]], flow: [["يُرفع الإصدار", "Upload revision", "Revision hochladen"], ["يراجعه العميل", "Client reviews", "Kundenrezensionen"], ["يُوثّق الاعتماد", "Record approval", "Genehmigung aufzeichnen"]], tone: "cyan",
  }),
  recruitment: sectorDemo({
    brand: ["كفاءات", "Kafaat", "Kafaat"], headline: ["مرشحون ومقابلات وقرارات في خط توظيف واحد", "Candidates, interviews and decisions in one hiring pipeline", "Kandidaten, Vorstellungsgespräche und Entscheidungen in einer Einstellungspipeline"], description: ["فرز أولي وملفات مرشحين وجدولة مقابلات وتحديثات واضحة.", "Pre-screening, candidate profiles, interview scheduling and clear updates.", "Vorauswahl, Kandidatenprofile, Terminplanung für Vorstellungsgespräche und klare Aktualisierungen."], action: ["انقل المرشح إلى المقابلة", "Move candidate to interview", "Bewegen Sie den Kandidaten zum Vorstellungsgespräch"], result: ["انتقل المرشح الخيالي أحمد إلى مرحلة المقابلة الفنية", "Fictional candidate Ahmed moved to technical interview", "Der fiktive Kandidat Ahmed ging zum technischen Vorstellungsgespräch über"],
    clientLabel: ["بوابة الوظائف", "Jobs portal", "Stellenportal"], clientTitle: ["فرص مفتوحة", "Open roles", "Offene Rollen"], clientRows: [["D", ["مصمم واجهات", "UI designer", "UI-Designer"], ["بغداد • دوام كامل", "Baghdad • full time", "Bagdad • Vollzeit"], ["تقدّم", "Apply", "Anwenden"]], ["S", ["مندوب مبيعات", "Sales representative", "Außendienstmitarbeiter"], ["البصرة • خبرة سنتين", "Basra • 2 years", "Basra • 2 Jahre"], ["تقدّم", "Apply", "Anwenden"]], ["A", ["محاسب", "Accountant", "Buchhalter"], ["أربيل • حضوري", "Erbil • on site", "Erbil • vor Ort"], ["مفتوحة", "Open", "Offen"]]],
    adminLabel: ["خط التوظيف", "Hiring pipeline", "Einstellungspipeline"], adminTitle: ["مرشحون نشطون", "Active candidates", "Aktive Kandidaten"], adminRows: [["أ", ["أحمد كريم", "Ahmed Kareem", "Ahmed Kareem"], ["مصمم واجهات • 82%", "UI designer • 82%", "UI-Designer • 82 %"], ["فرز أولي", "Screening", "Vorführung"]], ["س", ["سارة ليث", "Sara Laith", "Sara Laith"], ["محاسبة • مقابلة اليوم", "Accounting • interview today", "Buchhaltung • Vorstellungsgespräch heute"], ["مقابلة", "Interview", "Interview"]], ["م", ["محمد علي", "Mohammed Ali", "Mohammed Ali"], ["مبيعات • مراجع مكتملة", "Sales • references complete", "Verkäufe • Referenzen vollständig"], ["قرار", "Decision", "Entscheidung"]]],
    stats: [["46", ["مرشحًا", "candidates", "Kandidaten"]], ["08", ["مقابلات", "interviews", "Interviews"]], ["05", ["وظائف مفتوحة", "open roles", "offene Rollen"]]], flow: [["يتقدم المرشح", "Candidate applies", "Der Kandidat bewirbt sich"], ["يُفرز ويُقابل", "Screen and interview", "Screening und Interview"], ["يصل القرار", "Reach decision", "Entscheidung treffen"]], tone: "violet",
  }),
  "training-institutes": sectorDemo({
    brand: ["معهد بيان", "Bayan Institute", "Bayan-Institut"], headline: ["اختبار مستوى وجدول وتقدم في رحلة تعليمية واحدة", "Placement, schedule and progress in one learning journey", "Platzierung, Zeitplan und Fortschritt in einer Lernreise"], description: ["اختبار قصير يقترح المستوى، ثم اختيار المجموعة ومتابعة الحضور.", "A short placement check, group selection and attendance tracking.", "Ein kurzer Einstufungscheck, Gruppenauswahl und Anwesenheitskontrolle."], action: ["أكمل اختبار المستوى التجريبي", "Complete the demo placement", "Schließen Sie die Demoplatzierung ab"], result: ["اقتُرح المستوى B1 وأصبحت مجموعتان متاحتين", "Level B1 suggested with two groups available", "Empfohlenes Niveau B1 mit zwei verfügbaren Gruppen"],
    clientLabel: ["مسار المتدرب", "Learner journey", "Lernreise"], clientTitle: ["اللغة الإنجليزية", "English language", "Englische Sprache"], clientRows: [["A2", ["المستوى الحالي", "Current level", "Aktueller Stand"], ["نتيجة التقييم الأولي", "Initial assessment result", "Erstes Bewertungsergebnis"], ["مبدئي", "Initial", "Anfänglich"]], ["B1", ["المستوى المقترح", "Suggested level", "Empfohlenes Level"], ["4 مهارات • 24 جلسة", "Four skills • 24 sessions", "Vier Fertigkeiten • 24 Sitzungen"], ["مقترح", "Suggested", "Empfohlen"]], ["◷", ["المجموعة المسائية", "Evening group", "Abendgruppe"], ["الأحد والثلاثاء • 18:00", "Sun & Tue • 18:00", "So und Di • 18:00 Uhr"], ["6 مقاعد", "6 places", "6 Plätze"]]],
    adminLabel: ["إدارة المعهد", "Institute office", "Institutsbüro"], adminTitle: ["المجموعات النشطة", "Active groups", "Aktive Gruppen"], adminRows: [["B1", ["الإنجليزية B1", "English B1", "Englisch B1"], ["18 من 24 متدربًا", "18 of 24 learners", "18 von 24 Lernenden"], ["مفتوحة", "Open", "Offen"]], ["D", ["التصميم المهني", "Vocational design", "Berufliche Gestaltung"], ["الحضور 91%", "91% attendance", "91 % Anwesenheit"], ["نشطة", "Active", "Aktiv"]], ["C", ["شهادات هذا الشهر", "Certificates this month", "Zertifikate diesen Monat"], ["22 شهادة للمراجعة", "22 to review", "22 zur Überprüfung"], ["مراجعة", "Review", "Rezension"]]],
    stats: [["09", ["مجموعات نشطة", "active groups", "aktive Gruppen"]], ["126", ["متدربًا", "learners", "Lernende"]], ["91%", ["نسبة الحضور", "attendance", "Teilnahme"]]], flow: [["يختبر مستواه", "Check level", "Füllstand prüfen"], ["يختار المجموعة", "Choose group", "Gruppe auswählen"], ["يتابع التقدم", "Track progress", "Verfolgen Sie den Fortschritt"]], tone: "amber",
  }),
  automotive: sectorDemo({
    brand: ["مسار للسيارات", "Masar Auto", "Masar Auto"], headline: ["المركبة من الحجز إلى الفحص ثم التسليم", "A vehicle journey from booking to inspection and handover", "Eine Fahrzeugreise von der Buchung bis zur Inspektion und Übergabe"], description: ["كتالوج وحجز وتجهيز وموافقة على العمل وحالة مباشرة للمركبة.", "Catalogue, booking, preparation, work approval and live vehicle status.", "Katalog, Buchung, Vorbereitung, Arbeitsgenehmigung und Live-Fahrzeugstatus."], action: ["وافق على الإصلاح التجريبي", "Approve the demo repair", "Genehmigen Sie die Demo-Reparatur"], result: ["اعتُمد تغيير البطارية الخيالي وانتقلت المركبة إلى التنفيذ", "Fictional battery replacement approved and moved to work", "Der fiktive Batteriewechsel wurde genehmigt und mit der Arbeit begonnen"],
    clientLabel: ["ملف المركبة", "Vehicle profile", "Fahrzeugprofil"], clientTitle: ["Toyota Camry 2022", "Toyota Camry 2022"], clientRows: [["◉", ["الفحص الأولي", "Initial inspection", "Erstinspektion"], ["اكتمل في 10:20", "Completed 10:20", "Um 10:20 Uhr abgeschlossen"], ["مكتمل", "Complete", "Vollständig"]], ["!", ["موافقة مطلوبة", "Approval required", "Genehmigung erforderlich"], ["استبدال البطارية", "Battery replacement", "Batteriewechsel"], ["قرار", "Decision", "Entscheidung"]], ["◷", ["موعد التسليم", "Handover time", "Übergabezeit"], ["اليوم • 17:30", "Today • 17:30", "Heute • 17:30"], ["متوقع", "Expected", "Erwartet"]]],
    adminLabel: ["لوحة الورشة", "Workshop board", "Werkstatttafel"], adminTitle: ["المركبات النشطة", "Active vehicles", "Aktive Fahrzeuge"], adminRows: [["B2", ["Camry • B2", "Camry • B2"], ["بانتظار الموافقة", "Awaiting approval", "Warten auf Genehmigung"], ["متوقفة", "Paused", "Angehalten"]], ["A1", ["Sportage • A1", "Sportage • A1"], ["صيانة دورية", "Routine service", "Routinemäßiger Service"], ["قيد العمل", "In service", "Im Dienst"]], ["C3", ["Corolla • C3", "Corolla • C3"], ["جاهزة للتسليم", "Ready for handover", "Bereit zur Übergabe"], ["جاهزة", "Ready", "Bereit"]]],
    stats: [["11", ["مركبة اليوم", "vehicles today", "Fahrzeuge heute"]], ["04", ["قيد العمل", "in service", "im Dienst"]], ["02", ["بانتظار قرار", "awaiting approval", "warten auf Genehmigung"]]], flow: [["يحجز العميل", "Customer books", "Kundenbücher"], ["تُفحص المركبة", "Inspect vehicle", "Fahrzeug prüfen"], ["يوافق ويتابع", "Approve and track", "Genehmigen und verfolgen"]], tone: "green",
  }),
  logistics: sectorDemo({
    brand: ["وصل للشحن", "Wasal Logistics", "Wasal Logistik"], headline: ["شحنة واضحة من الاستلام إلى التسليم", "A clear shipment journey from pickup to delivery", "Ein klarer Versandweg von der Abholung bis zur Zustellung"], description: ["عنوان ومسار وسائق ومحاولات تسليم وتحديثات حالة في شاشة واحدة.", "Address, route, driver, delivery attempts and status updates in one screen.", "Adresse, Route, Fahrer, Zustellversuche und Statusaktualisierungen auf einem Bildschirm."], action: ["حرّك الشحنة إلى المرحلة التالية", "Move shipment to next stage", "Verschieben Sie die Lieferung in die nächste Phase"], result: ["غادرت الشحنة الخيالية مركز الفرز نحو المنصور", "Fictional shipment left the hub for Mansour", "Die fiktive Lieferung verließ den Hub in Richtung Mansour"],
    clientLabel: ["تتبع الشحنة", "Shipment tracking", "Sendungsverfolgung"], clientTitle: ["الشحنة #W-2048", "Shipment #W-2048", "Sendung Nr. W-2048"], clientRows: [["✓", ["استلام الشحنة", "Shipment collected", "Sendung abgeholt"], ["بغداد الجديدة • 09:10", "New Baghdad • 09:10", "Neu-Bagdad • 09:10"], ["مكتمل", "Complete", "Vollständig"]], ["⇄", ["مركز الفرز", "Sorting hub", "Sortierzentrum"], ["غادرت عند 12:25", "Departed 12:25", "Abfahrt um 12:25 Uhr"], ["مباشر", "Live", "Live"]], ["⌖", ["التسليم", "Delivery", "Lieferung"], ["المنصور • 15:00–17:00", "Mansour • 15:00–17:00", "Mansour • 15:00–17:00"], ["قادم", "Next", "Nächste"]]],
    adminLabel: ["مركز التوزيع", "Dispatch centre", "Versandzentrum"], adminTitle: ["جولات اليوم", "Today’s routes", "Die heutigen Routen"], adminRows: [["R1", ["جولة المنصور", "Mansour route", "Mansour-Route"], ["18 شحنة • السائق حيدر", "18 shipments • Haider", "18 Sendungen • Haider"], ["في الطريق", "On route", "Unterwegs"]], ["R2", ["جولة الكرادة", "Karrada route", "Karrada-Route"], ["14 شحنة • محاولتان", "14 shipments • 2 attempts", "14 Sendungen • 2 Versuche"], ["متابعة", "Follow up", "Nachverfolgen"]], ["R3", ["جولة زيونة", "Zayouna route", "Zayouna-Route"], ["11 شحنة • 82%", "11 shipments • 82%", "11 Sendungen • 82 %"], ["جيدة", "Healthy", "Gesund"]]],
    stats: [["146", ["شحنة اليوم", "shipments today", "Sendungen heute"]], ["09", ["سائقين نشطين", "active drivers", "aktive Fahrer"]], ["82%", ["تم التسليم", "delivered", "geliefert"]]], flow: [["تُستلم الشحنة", "Collect shipment", "Sendung abholen"], ["تُفرز وتُوجّه", "Sort and route", "Sortieren und routen"], ["تُسلّم وتُوثّق", "Deliver and record", "Liefern und aufzeichnen"]], tone: "cyan",
  }),
  hospitality: sectorDemo({
    brand: ["دار دجلة", "Dar Dijla", "Dar Dijla"], headline: ["إقامة تبدأ باختيار واضح وتنتهي بطلب حجز مكتمل", "A stay that starts with clear choice and a complete booking request", "Ein Aufenthalt, der mit einer klaren Auswahl und einer vollständigen Buchungsanfrage beginnt"], description: ["غرف ومزايا وتواريخ وضيوف وتعليمات وصول في تجربة ضيافة واحدة.", "Rooms, amenities, dates, guests and arrival information in one hospitality journey.", "Zimmer, Ausstattung, Daten, Gäste und Ankunftsinformationen in einer Hospitality-Reise."], action: ["أرسل طلب الحجز التجريبي", "Send the demo booking request", "Senden Sie die Demo-Buchungsanfrage"], result: ["استُلم طلب خيالي لغرفة دجلة من 20 إلى 23 آب", "Fictional request received for Dijla Room, 20–23 Aug", "Fiktive Anfrage für Dijla Room vom 20. bis 23. August eingegangen"],
    clientLabel: ["اختيار الإقامة", "Stay selection", "Aufenthaltsauswahl"], clientTitle: ["الغرف المتاحة", "Available rooms", "Verfügbare Zimmer"], clientRows: [["▥", ["غرفة دجلة", "Dijla Room", "Dijla-Zimmer"], ["شخصان • فطور", "Two guests • breakfast", "Zwei Gäste • Frühstück"], ["متاحة", "Available", "Verfügbar"]], ["⌂", ["شقة الرافدين", "Rafidain Suite", "Rafidain-Suite"], ["4 أشخاص • مطبخ", "Four guests • kitchen", "Vier Gäste • Küche"], ["متاحة", "Available", "Verfügbar"]], ["✦", ["إطلالة المدينة", "City View", "Blick auf die Stadt"], ["شرفة • طابق مرتفع", "Balcony • high floor", "Balkon • obere Etage"], ["اطلب", "Request", "Anfrage"]]],
    adminLabel: ["مكتب الاستقبال", "Front desk", "Rezeption"], adminTitle: ["الإشغال والطلبات", "Occupancy and requests", "Belegung und Anfragen"], adminRows: [["20", ["وصول اليوم", "Arrivals today", "Heute eingetroffen"], ["8 حجوزات مؤكدة", "8 confirmed bookings", "8 bestätigte Buchungen"], ["جاهز", "Ready", "Bereit"]], ["23", ["مغادرة اليوم", "Departures today", "Abfahrten heute"], ["5 غرف", "5 rooms", "5 Zimmer"], ["قيد العمل", "In progress", "Im Gange"]], ["!", ["طلب خاص", "Special request", "Sonderwunsch"], ["تسجيل وصول متأخر", "Late check-in", "Später Check-in"], ["ملاحظة", "Note", "Notiz"]]],
    stats: [["78%", ["نسبة الإشغال", "occupancy", "Belegung"]], ["08", ["وصول اليوم", "arrivals today", "Ankünfte heute"]], ["03", ["غرف متاحة", "rooms available", "Zimmer verfügbar"]]], flow: [["يختار الغرفة", "Choose room", "Wählen Sie ein Zimmer"], ["يحدد التواريخ", "Select dates", "Wählen Sie Daten aus"], ["يرسل الطلب", "Send request", "Anfrage senden"]], tone: "amber",
  }),
  events: sectorDemo({
    brand: ["ليلة للمناسبات", "Layla Events", "Layla-Veranstaltungen"], headline: ["مناسبة تُبنى من العدد والقاعة إلى الباقة والتجهيز", "An event built from guest count and venue to package and setup", "Eine Veranstaltung, die von der Anzahl der Gäste und dem Veranstaltungsort bis hin zu Paket und Aufbau reicht"], description: ["مقارنة قاعات وباقات ومخطط تجهيز وقائمة قرارات قبل الموعد.", "Venue and package comparison, setup plan and decision checklist before the date.", "Veranstaltungsort- und Paketvergleich, Aufbauplan und Entscheidungscheckliste vor dem Termin."], action: ["احفظ مخطط المناسبة التجريبي", "Save the demo event plan", "Speichern Sie den Demo-Veranstaltungsplan"], result: ["حُفظ مخطط خيالي لـ180 ضيفًا مع باقة المساء", "Fictional plan saved for 180 guests with Evening package", "Fiktiver Plan für 180 Gäste mit Abendpauschale gespeichert"],
    clientLabel: ["مخطط المناسبة", "Event planner", "Veranstaltungsplaner"], clientTitle: ["اختر القاعة والباقة", "Choose venue and package", "Wählen Sie Veranstaltungsort und Paket"], clientRows: [["180", ["عدد الضيوف", "Guest count", "Anzahl der Gäste"], ["قابل للتعديل", "Adjustable", "Einstellbar"], ["180", "180"]], ["✧", ["قاعة النخيل", "Palm Hall", "Palmenhalle"], ["حتى 220 ضيفًا", "Up to 220 guests", "Bis zu 220 Gäste"], ["متاحة", "Available", "Verfügbar"]], ["M", ["باقة المساء", "Evening package", "Abendpaket"], ["ضيافة • إضاءة • تنسيق", "Catering • lighting • styling", "Catering • Beleuchtung • Styling"], ["مختارة", "Selected", "Ausgewählt"]]],
    adminLabel: ["لوحة المنظم", "Planner board", "Planertafel"], adminTitle: ["قرارات وتجهيزات", "Decisions and setup", "Entscheidungen und Einrichtung"], adminRows: [["✓", ["مخطط الطاولات", "Table plan", "Tischplan"], ["18 طاولة • 10 ضيوف", "18 tables • 10 guests", "18 Tische • 10 Gäste"], ["جاهز", "Ready", "Bereit"]], ["!", ["اختيار الألوان", "Colour selection", "Farbauswahl"], ["مطلوب قبل 18 آب", "Due before 18 Aug", "Fällig vor dem 18. August"], ["قرار", "Decision", "Entscheidung"]], ["◷", ["موعد التجربة", "Tasting session", "Verkostung"], ["الأربعاء • 17:00", "Wednesday • 17:00", "Mittwoch • 17:00"], ["مؤكد", "Confirmed", "Bestätigt"]]],
    stats: [["180", ["ضيفًا", "guests", "Gäste"]], ["18", ["طاولة", "tables", "Tische"]], ["02", ["قرارات مطلوبة", "decisions needed", "Entscheidungen nötig"]]], flow: [["يحدد التفاصيل", "Set details", "Details festlegen"], ["يقارن الباقات", "Compare packages", "Pakete vergleichen"], ["يعتمد المخطط", "Approve plan", "Plan genehmigen"]], tone: "violet",
  }),
  manufacturing: sectorDemo({
    brand: ["مصنع أساس", "Asas Factory", "Asas-Fabrik"], headline: ["خط إنتاج يُظهر الأمر والجودة والتوقف لحظة بلحظة", "A production line showing orders, quality and downtime as they happen", "Eine Produktionslinie, die Aufträge, Qualität und Ausfallzeiten sofort anzeigt"], description: ["أوامر عمل ومحطات ومواد وفحص جودة وصيانة ضمن لوحة تشغيل.", "Work orders, stations, materials, quality checks and maintenance in one board.", "Arbeitsaufträge, Stationen, Materialien, Qualitätsprüfungen und Wartung in einem Board."], action: ["شغّل المحطة التجريبية", "Run the demo station", "Führen Sie die Demostation aus"], result: ["اكتملت الدفعة الخيالية #B-71 واجتازت فحص الجودة", "Fictional batch #B-71 completed and passed quality check", "Fiktive Charge Nr. B-71 fertiggestellt und Qualitätsprüfung bestanden"],
    clientLabel: ["خطة الإنتاج", "Production plan", "Produktionsplan"], clientTitle: ["أوامر العمل", "Work orders", "Arbeitsaufträge"], clientRows: [["B71", ["دفعة #B-71", "Batch #B-71", "Charge Nr. B-71"], ["240 وحدة • خط 2", "240 units • line 2", "240 Einheiten • Linie 2"], ["قيد العمل", "Running", "Läuft"]], ["B72", ["دفعة #B-72", "Batch #B-72", "Charge Nr. B-72"], ["180 وحدة • بعد B-71", "180 units • after B-71", "180 Einheiten • nach B-71"], ["قادمة", "Queued", "In der Warteschlange"]], ["M2", ["المادة الخام M2", "Raw material M2", "Rohstoff M2"], ["تكفي 1.8 وردية", "1.8 shifts remaining", "Noch 1,8 Schichten übrig"], ["تنبيه", "Alert", "Alarm"]]],
    adminLabel: ["غرفة التشغيل", "Operations room", "Operationssaal"], adminTitle: ["حالة المحطات", "Station status", "Stationsstatus"], adminRows: [["01", ["القص", "Cutting", "Schneiden"], ["98% كفاءة", "98% efficiency", "98 % Effizienz"], ["تعمل", "Running", "Läuft"]], ["02", ["التجميع", "Assembly", "Montage"], ["دفعة B-71", "Batch B-71", "Charge B-71"], ["تعمل", "Running", "Läuft"]], ["03", ["فحص الجودة", "Quality check", "Qualitätsprüfung"], ["4 عينات بانتظار الفحص", "4 samples waiting", "4 Proben warten"], ["فحص", "Inspect", "Überprüfen"]]],
    stats: [["82%", ["كفاءة الوردية", "shift efficiency", "Schalteffizienz"]], ["420", ["وحدة اليوم", "units today", "Einheiten heute"]], ["04", ["عينات جودة", "quality samples", "Qualitätsproben"]]], flow: [["يُفتح أمر العمل", "Open work order", "Arbeitsauftrag öffnen"], ["يمر بالمحطات", "Move through stations", "Bewegen Sie sich durch Stationen"], ["يُعتمد الفحص", "Approve quality", "Qualität genehmigen"]], tone: "green",
  }),
  insurance: sectorDemo({
    brand: ["أمان للوساطة", "Aman Brokerage", "Aman Brokerage"], headline: ["تغطية مفهومة وطلب عرض ومطالبة قابلة للتتبع", "Understandable coverage, quote requests and trackable claims", "Verständliche Deckung, Angebotsanfragen und nachverfolgbare Schadensfälle"], description: ["مقارنة مبسطة وحقول مكتملة وقائمة مستندات وحالة مطالبة واضحة.", "Plain comparison, complete fields, document checklist and clear claim status.", "Einfacher Vergleich, vollständige Felder, Dokumenten-Checkliste und klarer Anspruchsstatus."], action: ["أرسل طلب العرض التجريبي", "Send the demo quote request", "Senden Sie die Demo-Angebotsanfrage"], result: ["أُرسل الطلب الخيالي للمراجعة دون إصدار سعر أو وثيقة", "Fictional request sent for review without issuing a price or policy", "Fiktive Anfrage zur Überprüfung ohne Angabe eines Preises oder einer Richtlinie"],
    clientLabel: ["مقارنة التغطية", "Coverage comparison", "Abdeckungsvergleich"], clientTitle: ["خيارات توضيحية", "Illustrative options", "Anschauliche Optionen"], clientRows: [["S", ["تغطية أساسية", "Essential cover", "Unverzichtbarer Schutz"], ["مزايا رئيسية موضحة", "Core benefits explained", "Kernvorteile erklärt"], ["قارن", "Compare", "Vergleichen"]], ["P", ["تغطية موسعة", "Extended cover", "Erweiterter Versicherungsschutz"], ["حدود واستثناءات أوضح", "Clearer limits and exclusions", "Klarere Grenzen und Ausschlüsse"], ["قارن", "Compare", "Vergleichen"]], ["C", ["مطالبة حالية", "Existing claim", "Bestehender Anspruch"], ["تم استلام 3 مستندات", "Three documents received", "Drei Dokumente erhalten"], ["متابعة", "Track", "Schiene"]]],
    adminLabel: ["لوحة الوسيط", "Broker dashboard", "Broker-Dashboard"], adminTitle: ["الطلبات والمطالبات", "Quotes and claims", "Zitate und Behauptungen"], adminRows: [["Q1", ["طلب عرض #Q-91", "Quote #Q-91", "Zitat #Q-91"], ["الحقول مكتملة", "Fields complete", "Felder vollständig"], ["مراجعة", "Review", "Rezension"]], ["C8", ["مطالبة #C-28", "Claim #C-28", "Anspruch Nr. C-28"], ["بانتظار تقرير واحد", "Waiting for one report", "Warte auf einen Bericht"], ["ناقص", "Incomplete", "Unvollständig"]], ["R", ["تجديد قريب", "Renewal due", "Verlängerung fällig"], ["بعد 12 يومًا", "In 12 days", "In 12 Tagen"], ["تنبيه", "Alert", "Alarm"]]],
    stats: [["18", ["طلب عرض", "quote requests", "Angebotsanfragen"]], ["07", ["مطالبات نشطة", "active claims", "aktive Ansprüche"]], ["05", ["تجديدات قريبة", "renewals due", "Verlängerungen fällig"]]], flow: [["يقارن الخيارات", "Compare options", "Vergleichen Sie Optionen"], ["يُكمل الطلب", "Complete request", "Vollständige Anfrage"], ["يراجعه المختص", "Specialist review", "Fachgutachten"]], tone: "cyan",
  }),
  "religious-travel": sectorDemo({
    brand: ["قافلة للزيارات", "Qafila Travel", "Qafila-Reise"], headline: ["برنامج زيارة ومجموعة ومستندات في رحلة منظمة", "An organised pilgrimage itinerary, group and document journey", "Eine organisierte Pilgerroute, Gruppen- und Dokumentenreise"], description: ["تفاصيل الأيام ونقاط التجمع وقائمة المستندات وتحديثات المجموعة دون تأكيد وهمي.", "Daily details, meeting points, document checklist and group updates without false confirmation.", "Tägliche Details, Treffpunkte, Dokumentencheckliste und Gruppenaktualisierungen ohne falsche Bestätigung."], action: ["أرسل طلب الانضمام التجريبي", "Send the demo join request", "Senden Sie die Demo-Beitrittsanfrage"], result: ["استُلم طلب خيالي للانضمام إلى مجموعة النجف وكربلاء", "Fictional request received for the Najaf and Karbala group", "Fiktive Anfrage für die Gruppe Nadschaf und Karbala eingegangen"],
    clientLabel: ["برنامج الزائر", "Traveller itinerary", "Reiseplan"], clientTitle: ["زيارة النجف وكربلاء", "Najaf and Karbala visit", "Besuch von Nadschaf und Kerbela"], clientRows: [["01", ["اليوم الأول", "Day one", "Tag eins"], ["الوصول ونقطة التجمع", "Arrival and meeting point", "Ankunft und Treffpunkt"], ["عرض", "View", "Sicht"]], ["02", ["اليوم الثاني", "Day two", "Tag zwei"], ["برنامج الزيارة والنقل", "Visit programme and transport", "Besuchsprogramm und Transport"], ["عرض", "View", "Sicht"]], ["✓", ["قائمة المستندات", "Document checklist", "Checkliste für Dokumente"], ["اكتمل 4 من 5", "4 of 5 complete", "4 von 5 vollständig"], ["ناقص واحد", "One missing", "Einer fehlt"]]],
    adminLabel: ["إدارة المجموعة", "Group management", "Gruppenleitung"], adminTitle: ["الرحلات والمشاركون", "Trips and participants", "Reisen und Teilnehmer"], adminRows: [["G1", ["مجموعة 21 آب", "21 Aug group", "21. August Gruppe"], ["34 من 40 مشاركًا", "34 of 40 travellers", "34 von 40 Reisenden"], ["مفتوحة", "Open", "Offen"]], ["D", ["المستندات", "Documents", "Unterlagen"], ["6 ملفات تحتاج متابعة", "6 files need follow-up", "6 Dateien müssen weiterverfolgt werden"], ["متابعة", "Follow up", "Nachverfolgen"]], ["M", ["تنبيه التجمع", "Meeting alert", "Besprechungsalarm"], ["يرسل قبل 6 ساعات", "Sends 6 hours before", "Sendet 6 Stunden vorher"], ["جاهز", "Ready", "Bereit"]]],
    stats: [["34", ["مشاركًا", "travellers", "Reisende"]], ["05", ["أيام البرنامج", "itinerary days", "Reiseroute Tage"]], ["06", ["ملفات ناقصة", "missing files", "fehlende Dateien"]]], flow: [["يختار البرنامج", "Choose programme", "Programm auswählen"], ["يُكمل المستندات", "Complete documents", "Vollständige Unterlagen"], ["يتابع المجموعة", "Follow group", "Folge der Gruppe"]], tone: "amber",
  }),
};

const industries: Record<string, ContextDemo> = {
  clinics: {
    brand: ["عيادة الشفاء", "Al-Shifa Clinic", "Al-Shifa-Klinik"], headline: ["حجز موعد واضح للمراجع والعيادة", "Clear appointment booking for patients and clinic staff", "Übersichtliche Terminbuchung für Patienten und Klinikpersonal"], description: ["اختيار الاختصاص والطبيب والوقت ثم تأكيد آمن دون بيانات صحية حقيقية.", "Choose speciality, doctor and time, then get a safe confirmation without real health data.", "Wählen Sie Fachrichtung, Arzt und Zeit und erhalten Sie eine sichere Bestätigung ohne echte Gesundheitsdaten."], action: ["احجز موعدًا تجريبيًا", "Book a demo appointment", "Buchen Sie einen Demo-Termin"], result: ["تم حجز موعد خيالي: الأحد، 10:30", "Fictional appointment booked: Sunday, 10:30", "Gebuchter fiktiver Termin: Sonntag, 10:30 Uhr"],
    client: { label: ["حجز المراجع", "Patient booking", "Patientenbuchung"], title: ["اختر موعدًا متاحًا", "Choose an available time", "Wählen Sie eine verfügbare Zeit"], rows: [["✚", ["طب الأسرة", "Family medicine", "Familienmedizin"], ["د. نور • الأحد 10:30", "Dr Noor • Sunday 10:30", "Dr. Noor • Sonntag 10:30"], ["متاح", "Available", "Verfügbar"]], ["◎", ["طب الأسنان", "Dentistry", "Zahnheilkunde"], ["د. ليث • الأحد 12:00", "Dr Laith • Sunday 12:00", "Dr. Laith • Sonntag 12:00"], ["متاح", "Available", "Verfügbar"]], ["◌", ["استشارة أطفال", "Paediatrics", "Pädiatrie"], ["د. زهراء • الاثنين 09:00", "Dr Zahra • Monday 09:00", "Dr. Zahra • Montag 09:00"], ["متاح", "Available", "Verfügbar"]]] },
    admin: { label: ["جدول العيادة", "Clinic schedule", "Klinikplan"], title: ["مواعيد اليوم", "Today's appointments", "Die heutigen Termine"], rows: [["10", ["موعد تجريبي #31", "Demo appointment #31", "Demo-Termin Nr. 31"], ["10:30 • طب الأسرة", "10:30 • family medicine", "10:30 • Familienmedizin"], ["مؤكد", "Confirmed", "Bestätigt"]], ["11", ["موعد تجريبي #32", "Demo appointment #32", "Demo-Termin Nr. 32"], ["11:15 • فحص عام", "11:15 • general check", "11:15 • Generalüberprüfung"], ["بانتظار الوصول", "Awaiting arrival", "Warten auf Ankunft"]], ["12", ["موعد تجريبي #33", "Demo appointment #33", "Demo-Termin Nr. 33"], ["12:00 • أسنان", "12:00 • dentistry", "12:00 • Zahnmedizin"], ["تم التذكير", "Reminded", "Erinnert"]]] },
    stats: [["12", ["موعدًا اليوم", "appointments today", "Termine heute"]], ["03", ["أطباء متاحون", "available doctors", "verfügbare Ärzte"]], ["0", ["تداخلات", "conflicts", "Konflikte"]]], flow: [["اختيار الاختصاص", "Choose speciality", "Spezialität wählen"], ["اختيار الوقت", "Choose time", "Wählen Sie die Zeit"], ["استلام التأكيد", "Get confirmation", "Holen Sie sich eine Bestätigung"]], tone: "cyan",
  },
  restaurants: {
    brand: ["مقهى النخلة", "Palm Café", "Palm Café"], headline: ["قائمة رقمية وطلب واضح عبر الهاتف", "A mobile menu and clear ordering journey", "Ein mobiles Menü und ein übersichtlicher Bestellvorgang"], description: ["الأصناف والإضافات والسعر وطريقة الاستلام في تجربة واحدة.", "Items, options, price and fulfilment in one experience.", "Artikel, Optionen, Preis und Erfüllung in einem Erlebnis."], action: ["أرسل طلبًا تجريبيًا", "Place a demo order", "Geben Sie eine Demobestellung auf"], result: ["وصل الطلب الخيالي إلى شاشة المطبخ", "Fictional order sent to the kitchen screen", "Fiktive Bestellung an den Küchenbildschirm gesendet"],
    client: { label: ["قائمة الزبون", "Customer menu", "Kundenmenü"], title: ["الأكثر طلبًا", "Popular today", "Heute beliebt"], rows: [["☕", ["لاتيه بالهيل", "Cardamom latte", "Kardamom-Latte"], ["حجم وسط • 5,000 د.ع", "Medium • IQD 5,000", "Mittel • IQD 5.000"], ["أضف", "Add", "Hinzufügen"]], ["◒", ["برغر دجاج", "Chicken burger", "Hühnerburger"], ["مع بطاطا • 9,500 د.ع", "With fries • IQD 9,500", "Mit Pommes • IQD 9.500"], ["خصص", "Customise", "Anpassen"]], ["◇", ["كنافة صغيرة", "Small kunafa", "Kleine Kunafa"], ["طازجة • 4,000 د.ع", "Fresh • IQD 4,000", "Frisch • IQD 4.000"], ["أضف", "Add", "Hinzufügen"]]] },
    admin: { label: ["شاشة المطبخ", "Kitchen screen", "Küchenschirm"], title: ["طلبات قيد التحضير", "Orders being prepared", "Bestellungen werden vorbereitet"], rows: [["24", ["طلب #24", "Order #24", "Bestellnummer 24"], ["برغر ×2 • لاتيه ×1", "Burger ×2 • latte ×1", "Burger ×2 • Latte ×1"], ["قيد التحضير", "Preparing", "Vorbereiten"]], ["25", ["طلب #25", "Order #25", "Bestellnummer 25"], ["كنافة ×1 • شاي ×2", "Kunafa ×1 • tea ×2", "Kunafa ×1 • Tee ×2"], ["جديد", "New", "Neu"]], ["23", ["طلب #23", "Order #23", "Bestellnummer 23"], ["استلام من الفرع", "Branch pickup", "Abholung in der Filiale"], ["جاهز", "Ready", "Bereit"]]] },
    stats: [["18", ["صنفًا متاحًا", "available items", "verfügbare Artikel"]], ["07", ["طلبات مفتوحة", "open orders", "offene Bestellungen"]], ["22m", ["متوسط التجهيز", "average prep", "durchschnittliche Vorbereitung"]]], flow: [["يختار الأصناف", "Choose items", "Wählen Sie Artikel aus"], ["يخصص الطلب", "Customise order", "Bestellung anpassen"], ["يتابع التجهيز", "Track preparation", "Streckenvorbereitung"]], tone: "amber",
  },
  retail: {
    brand: ["متجر الرافدين", "Rafidain Store", "Rafidain-Shop"], headline: ["متجر عراقي يعرض المنتجات والمخزون والطلبات بوضوح", "An Iraqi store with clear products, stock and orders", "Ein irakischer Laden mit übersichtlichen Produkten, Lagerbeständen und Bestellungen"], description: ["تصفح سريع، وسلة مختصرة، وتحديث واضح لحالة الطلب.", "Fast browsing, simple cart and clear order status.", "Schnelles Browsen, einfacher Warenkorb und klarer Bestellstatus."], action: ["أضف إلى السلة التجريبية", "Add to demo cart", "Zum Demo-Warenkorb hinzufügen"], result: ["أُضيف منتج خيالي إلى السلة", "Fictional product added to the cart", "Fiktives Produkt zum Warenkorb hinzugefügt"],
    client: { label: ["واجهة المتجر", "Storefront", "Schaufenster"], title: ["منتجات مختارة", "Selected products", "Ausgewählte Produkte"], rows: [["□", ["مصباح مكتبي", "Desk lamp", "Schreibtischlampe"], ["متوفر • 32,000 د.ع", "Available • IQD 32,000", "Verfügbar • IQD 32.000"], ["أضف", "Add", "Hinzufügen"]], ["◇", ["حافظة هاتف", "Phone case", "Handyhülle"], ["3 ألوان • 15,000 د.ع", "3 colours • IQD 15,000", "3 Farben • IQD 15.000"], ["اختر", "Choose", "Wählen"]], ["△", ["سماعة لاسلكية", "Wireless headset", "Kabelloses Headset"], ["ضمان سنة • 48,000 د.ع", "1-year warranty • IQD 48,000", "1 Jahr Garantie • IQD 48.000"], ["أضف", "Add", "Hinzufügen"]]] },
    admin: { label: ["لوحة التاجر", "Merchant dashboard", "Händler-Dashboard"], title: ["الطلبات والمخزون", "Orders and inventory", "Bestellungen und Inventar"], rows: [["#", ["طلب #812", "Order #812", "Bestellnr. 812"], ["3 منتجات • بغداد", "3 items • Baghdad", "3 Artikel • Bagdad"], ["للتجهيز", "To pack", "Zum Packen"]], ["!", ["سماعة لاسلكية", "Wireless headset", "Kabelloses Headset"], ["تبقى 4 قطع", "4 units left", "4 Einheiten übrig"], ["مخزون منخفض", "Low stock", "Geringer Lagerbestand"]], ["↗", ["مبيعات هذا الأسبوع", "Sales this week", "Verkauf diese Woche"], ["+18% مقارنة بالأسبوع السابق", "+18% vs previous", "+18 % gegenüber dem Vorjahr"], ["جيد", "Healthy", "Gesund"]]] },
    stats: [["64", ["منتجًا", "products", "Produkte"]], ["11", ["طلب اليوم", "orders today", "Bestellungen heute"]], ["05", ["تنبيهات مخزون", "stock alerts", "Aktienwarnungen"]]], flow: [["بحث وتصفح", "Search & browse", "Suchen und stöbern"], ["سلة وتأكيد", "Cart & confirm", "Warenkorb & bestätigen"], ["تجهيز وتتبع", "Pack & track", "Packen und verfolgen"]], tone: "violet",
  },
  construction: {
    brand: ["مشروع النخيل", "Palm Project", "Palm-Projekt"], headline: ["لوحة تربط المراحل والملفات والدفعات", "A board connecting milestones, files and payments", "Eine Tafel, die Meilensteine, Dateien und Zahlungen verbindet"], description: ["رؤية موحّدة لما أُنجز، وما تأخر، وما يحتاج إلى قرار.", "One view of what is done, delayed and awaiting a decision.", "Eine Sicht auf das, was getan wird, verzögert wird und auf eine Entscheidung wartet."], action: ["حدّث مرحلة تجريبية", "Update a demo milestone", "Aktualisieren Sie einen Demo-Meilenstein"], result: ["انتقلت مرحلة الهيكل إلى حالة «مكتمل»", "Structure milestone moved to complete", "Der Strukturmeilenstein wurde zum Abschluss verschoben"],
    client: { label: ["عرض المشروع", "Project view", "Projektansicht"], title: ["تقدم المشروع", "Project progress", "Projektfortschritt"], rows: [["01", ["الأعمال الترابية", "Groundwork", "Grundlage"], ["أُنجزت وفق الخطة", "Completed to plan", "Nach Plan fertiggestellt"], ["مكتمل", "Complete", "Vollständig"]], ["02", ["الهيكل الإنشائي", "Structure", "Struktur"], ["الفحص النهائي اليوم", "Final inspection today", "Heute Endkontrolle"], ["قيد التنفيذ", "In progress", "Im Gange"]], ["03", ["الأعمال الكهربائية", "Electrical work", "Elektroarbeiten"], ["تبدأ بعد الاعتماد", "Starts after approval", "Beginnt nach Genehmigung"], ["قادم", "Upcoming", "Demnächst"]]] },
    admin: { label: ["إدارة التنفيذ", "Delivery management", "Liefermanagement"], title: ["المراحل المفتوحة", "Open milestones", "Offene Meilensteine"], rows: [["!", ["اعتماد مخطط الكهرباء", "Approve electrical plan", "Elektroplan genehmigen"], ["مطلوب من الاستشاري", "Consultant action required", "Beratertätigkeit erforderlich"], ["قرار", "Decision", "Entscheidung"]], ["▣", ["تقرير الموقع الأسبوعي", "Weekly site report", "Wöchentlicher Standortbericht"], ["12 صورة وملاحظة واحدة", "12 photos and one note", "12 Fotos und eine Notiz"], ["جاهز", "Ready", "Bereit"]], ["$", ["دفعة المرحلة الثانية", "Stage two payment", "Zahlung der zweiten Stufe"], ["تاريخ الاستحقاق 18 آب", "Due 18 Aug", "Fällig am 18. August"], ["قادم", "Upcoming", "Demnächst"]]] },
    stats: [["68%", ["نسبة الإنجاز", "completion", "Fertigstellung"]], ["14", ["ملفًا معتمدًا", "approved files", "genehmigte Dateien"]], ["02", ["قرارات مطلوبة", "decisions needed", "Entscheidungen nötig"]]], flow: [["تحديث الموقع", "Site update", "Site-Update"], ["اعتماد المرحلة", "Approve milestone", "Meilenstein genehmigen"], ["إصدار التقرير", "Issue report", "Problembericht"]], tone: "green",
  },
  consulting: {
    brand: ["مكتب بُعد", "Dimension Office", "Dimensionsbüro"], headline: ["معالج يجمع متطلبات المشروع قبل الاجتماع", "An intake wizard that captures requirements before the meeting", "Ein Aufnahmeassistent, der Anforderungen vor dem Meeting erfasst"], description: ["نوع المشروع، والموقع، والمساحة، والملفات، والجدول الزمني المتوقع.", "Project type, location, area, files and expected timeline.", "Projekttyp, Standort, Bereich, Dateien und erwarteter Zeitplan."], action: ["أكمل طلبًا تجريبيًا", "Complete demo brief", "Komplettes Demo-Briefing"], result: ["اكتمل الملخص وأُنشئ رقم طلب خيالي", "Brief complete and fictional request number created", "Kurze vollständige und fiktive Anfragenummer erstellt"],
    client: { label: ["معالج العميل", "Client wizard", "Client-Assistent"], title: ["ملخص مشروعك", "Your project brief", "Ihre Projektbeschreibung"], rows: [["⌂", ["نوع المشروع", "Project type", "Projekttyp"], ["تصميم منزل سكني", "Residential house design", "Entwurf eines Wohnhauses"], ["مكتمل", "Complete", "Vollständig"]], ["▰", ["المساحة والموقع", "Area and location", "Gebiet und Standort"], ["420 م² • بغداد", "420 m² • Baghdad", "420 m² • Bagdad"], ["مكتمل", "Complete", "Vollständig"]], ["◷", ["المدة المتوقعة", "Expected timeline", "Voraussichtlicher Zeitplan"], ["البدء خلال 3 أشهر", "Start within 3 months", "Beginnen Sie innerhalb von 3 Monaten"], ["محدد", "Set", "Satz"]]] },
    admin: { label: ["مراجعة المكتب", "Office review", "Bürobewertung"], title: ["الطلبات الواردة", "Incoming briefs", "Eingehende Briefings"], rows: [["01", ["طلب #E-204", "Brief #E-204", "Brief Nr. E-204"], ["تصميم سكني • كامل", "Residential • complete", "Wohngebäude • abgeschlossen"], ["مؤهل", "Qualified", "Qualifiziert"]], ["02", ["طلب #E-203", "Brief #E-203", "Brief Nr. E-203"], ["استشارة إنشائية", "Structural consultation", "Strukturelle Beratung"], ["مراجعة", "Review", "Rezension"]], ["03", ["طلب #E-202", "Brief #E-202", "Brief Nr. E-202"], ["يحتاج مخطط الأرض", "Needs site plan", "Benötigt Lageplan"], ["ناقص", "Incomplete", "Unvollständig"]]] },
    stats: [["5/5", ["أقسام مكتملة", "sections complete", "Abschnitte abgeschlossen"]], ["03", ["ملفات تجريبية", "demo attachments", "Demo-Anhänge"]], ["1", ["قرار مطلوب", "decision needed", "Entscheidung nötig"]]], flow: [["يجيب عن الأسئلة", "Answers questions", "Beantwortet Fragen"], ["يرفع الملفات", "Adds files", "Fügt Dateien hinzu"], ["يصل ملخص واضح", "Clear brief arrives", "Klarer Brief kommt"]], tone: "cyan",
  },
  travel: {
    brand: ["رحلات دجلة", "Tigris Travel", "Tigris-Reise"], headline: ["عروض قابلة للمقارنة وطلب سفر مكتمل", "Comparable offers and a complete travel request", "Vergleichbare Angebote und eine vollständige Reiseanfrage"], description: ["الوجهة والتاريخ والمسافرون والخدمات دون تأكيد وهمي.", "Destination, dates, travellers and services without false confirmation.", "Reiseziel, Daten, Reisende und Dienstleistungen ohne falsche Bestätigung."], action: ["أرسل طلب سفر تجريبيًا", "Send a demo travel request", "Senden Sie eine Demo-Reiseanfrage"], result: ["استُلم الطلب للمراجعة وليس للحجز", "Request received for review—not booking", "Anfrage zur Überprüfung erhalten – keine Buchung"],
    client: { label: ["عروض المسافر", "Traveller offers", "Angebote für Reisende"], title: ["باقات مقترحة", "Suggested packages", "Empfohlene Pakete"], rows: [["✦", ["إسطنبول — 5 ليالٍ", "Istanbul — 5 nights", "Istanbul – 5 Nächte"], ["فندق ونقل • تاريخ مرن", "Hotel & transfer • flexible", "Hotel & Transfer • flexibel"], ["اطلب عرضًا", "Request quote", "Angebot anfordern"]], ["✦", ["أنطاليا — 6 ليالٍ", "Antalya — 6 nights", "Antalya – 6 Nächte"], ["منتجع وإفطار", "Resort & breakfast", "Resort & Frühstück"], ["اطلب عرضًا", "Request quote", "Angebot anfordern"]], ["✦", ["دبي — 4 ليالٍ", "Dubai — 4 nights", "Dubai – 4 Nächte"], ["فندق وسط المدينة", "Central hotel", "Zentrales Hotel"], ["قارن", "Compare", "Vergleichen"]]] },
    admin: { label: ["متابعة الطلبات", "Request follow-up", "Fordern Sie eine Nachverfolgung an"], title: ["طلبات تحتاج عرضًا", "Requests needing a quote", "Anfragen, die ein Angebot benötigen"], rows: [["01", ["عائلة من 4 أشخاص", "Family of four", "Vierköpfige Familie"], ["بغداد • إسطنبول", "Baghdad • Istanbul", "Bagdad • Istanbul"], ["تسعير", "Quoting", "Zitieren"]], ["02", ["مسافران", "Two travellers", "Zwei Reisende"], ["النجف • دبي", "Najaf • Dubai", "Nadschaf • Dubai"], ["بيانات كاملة", "Complete", "Vollständig"]], ["03", ["مجموعة تدريب", "Training group", "Trainingsgruppe"], ["أربيل • أنطاليا", "Erbil • Antalya", "Erbil • Antalya"], ["يحتاج تاريخًا", "Needs date", "Datum erforderlich"]]] },
    stats: [["08", ["عروض متاحة", "available offers", "verfügbare Angebote"]], ["04", ["وجهات", "destinations", "Reiseziele"]], ["24h", ["وقت الرد المتوقع", "expected response", "erwartete Reaktion"]]], flow: [["يقارن العروض", "Compare offer", "Angebot vergleichen"], ["يُكمل الطلب", "Complete request", "Vollständige Anfrage"], ["يستلم عرضًا", "Receive quote", "Angebot erhalten"]], tone: "amber",
  },
  education: {
    brand: ["أكاديمية خطوة", "Khatwa Academy", "Khatwa-Akademie"], headline: ["رحلة الدورة من الاكتشاف إلى التسجيل", "A course journey from discovery to enrolment", "Eine Kursreise von der Entdeckung bis zur Einschreibung"], description: ["تفاصيل الدورة، والمواعيد، والمدرب، والتقدم في مكان واحد.", "Course details, sessions, trainer and progress in one place.", "Kursdetails, Sitzungen, Trainer und Fortschritt an einem Ort."], action: ["سجّل في دورة تجريبية", "Join a demo course", "Nehmen Sie an einem Demokurs teil"], result: ["أُنشئ تسجيل خيالي وحُدّد تاريخ البدء", "Fictional enrolment created and start date added", "Fiktive Anmeldung erstellt und Startdatum hinzugefügt"],
    client: { label: ["بوابة الطالب", "Student portal", "Studentenportal"], title: ["دورات مقترحة", "Suggested courses", "Vorgeschlagene Kurse"], rows: [["▱", ["أساسيات Excel", "Excel essentials", "Excel-Grundlagen"], ["12 ساعة • يبدأ 20 آب", "12 hours • starts 20 Aug", "12 Stunden • beginnt am 20. August"], ["8 مقاعد", "8 seats", "8 Sitzplätze"]], ["⌘", ["التسويق الرقمي", "Digital marketing", "Digitales Marketing"], ["16 ساعة • مسائي", "16 hours • evening", "16 Stunden • Abend"], ["متاح", "Available", "Verfügbar"]], ["◎", ["إدارة المشاريع", "Project management", "Projektmanagement"], ["20 ساعة • حضوري", "20 hours • in person", "20 Stunden • persönlich"], ["قريبًا", "Soon", "Bald"]]] },
    admin: { label: ["إدارة المركز", "Centre dashboard", "Mittleres Armaturenbrett"], title: ["التسجيل والحضور", "Enrolment and attendance", "Anmeldung und Anwesenheit"], rows: [["أ", ["مجموعة Excel — A", "Excel group — A", "Excel-Gruppe – A"], ["18 مسجلًا من 24", "18 of 24 enrolled", "18 von 24 eingeschrieben"], ["مفتوح", "Open", "Offen"]], ["ت", ["جلسة التسويق 03", "Marketing session 03", "Marketingsitzung 03"], ["حضور 92%", "92% attendance", "92 % Anwesenheit"], ["تمت", "Done", "Erledigt"]], ["ش", ["الشهادات", "Certificates", "Zertifikate"], ["14 شهادة جاهزة", "14 certificates ready", "14 Zertifikate liegen bereit"], ["للمراجعة", "Review", "Rezension"]]] },
    stats: [["06", ["دورات نشطة", "active courses", "aktive Kurse"]], ["84", ["طالبًا تجريبيًا", "demo learners", "Demo-Lernende"]], ["91%", ["نسبة الحضور", "attendance", "Teilnahme"]]], flow: [["يختار الدورة", "Choose course", "Kurs wählen"], ["يُسجّل بياناته", "Enrol", "Einschreiben"], ["يتابع تقدمه", "Track progress", "Verfolgen Sie den Fortschritt"]], tone: "violet",
  },
  maintenance: {
    brand: ["خدمة البيت", "Home Service", "Heimservice"], headline: ["طلب صيانة يبدأ بوصف العطل وينتهي بإغلاقه", "A maintenance request from issue to completion", "Eine Wartungsanfrage von der Ausgabe bis zur Fertigstellung"], description: ["نوع الخدمة، والموقع، والموعد، والفني، والحالة في مسار واحد.", "Service type, location, slot, technician and status in one flow.", "Servicetyp, Standort, Slot, Techniker und Status in einem Fluss."], action: ["سجّل عطلًا تجريبيًا", "Log a demo issue", "Melden Sie ein Demo-Problem an"], result: ["أُنشئ طلب خيالي وأُسند إلى فني", "Fictional request created and assigned", "Fiktive Anfrage erstellt und zugewiesen"],
    client: { label: ["طلب العميل", "Customer request", "Kundenwunsch"], title: ["اختر نوع الخدمة", "Choose service type", "Wählen Sie den Servicetyp"], rows: [["⚡", ["عطل كهربائي", "Electrical issue", "Elektrisches Problem"], ["فحص قاطع أو إنارة", "Breaker or lighting check", "Unterbrecher- oder Beleuchtungsprüfung"], ["اطلب", "Request", "Anfrage"]], ["◉", ["تسرب ماء", "Water leak", "Wasserleck"], ["مطبخ أو حمام", "Kitchen or bathroom", "Küche oder Badezimmer"], ["عاجل", "Urgent", "Dringend"]], ["△", ["صيانة تكييف", "AC maintenance", "Wartung der Klimaanlage"], ["تنظيف أو تشخيص", "Clean or diagnose", "Reinigen oder diagnostizieren"], ["احجز", "Book", "Buch"]]] },
    admin: { label: ["جدول الفنيين", "Technician schedule", "Technikerplan"], title: ["طلبات اليوم", "Today's jobs", "Die heutigen Jobs"], rows: [["01", ["طلب #M-88", "Job #M-88", "Job Nr. M-88"], ["المنصور • كهرباء", "Mansour • electrical", "Mansour • elektrisch"], ["الفني في الطريق", "En route", "Unterwegs"]], ["02", ["طلب #M-89", "Job #M-89", "Job Nr. M-89"], ["الكرادة • تسرب", "Karrada • leak", "Karrada • Leck"], ["عاجل", "Urgent", "Dringend"]], ["03", ["طلب #M-90", "Job #M-90", "Job Nr. M-90"], ["زيونة • تكييف", "Zayouna • AC", "Zayouna • AC"], ["16:00", "16:00"]]] },
    stats: [["09", ["طلبات اليوم", "jobs today", "Arbeitsplätze heute"]], ["04", ["فنيين متاحين", "available technicians", "verfügbare Techniker"]], ["36m", ["متوسط التوجيه", "average dispatch", "durchschnittlicher Versand"]]], flow: [["يصف العطل", "Describe issue", "Beschreiben Sie das Problem"], ["يُسند الفني", "Assign technician", "Techniker beauftragen"], ["يتابع ويقيّم", "Track & rate", "Verfolgen und bewerten"]], tone: "green",
  },
  distribution: {
    brand: ["موزّع العراق", "Iraq Distributor", "Irak-Händler"], headline: ["طلبات وكلاء ومبيعات حسب المحافظة", "Dealer orders and sales by governorate", "Händlerbestellungen und Verkäufe nach Gouvernement"], description: ["سعر الوكيل والحد الائتماني وحالة الطلب في لوحة واحدة.", "Dealer pricing, credit limit and order status in one dashboard.", "Händlerpreise, Kreditlimit und Bestellstatus in einem Dashboard."], action: ["اعتمد طلبًا تجريبيًا", "Approve a demo order", "Genehmigen Sie eine Demobestellung"], result: ["اعتُمد الطلب الخيالي وحُجز المخزون", "Fictional order approved and stock reserved", "Fiktive Bestellung genehmigt und Lagerbestand reserviert"],
    client: { label: ["بوابة الوكيل", "Dealer portal", "Händlerportal"], title: ["طلب جملة جديد", "New wholesale order", "Neue Großhandelsbestellung"], rows: [["A", ["منتج الفئة A", "Category A product", "Produkt der Kategorie A"], ["سعر وكيل • متوفر 240", "Dealer price • 240 available", "Händlerpreis • 240 verfügbar"], ["اطلب", "Order", "Befehl"]], ["B", ["منتج الفئة B", "Category B product", "Produkt der Kategorie B"], ["سعر وكيل • متوفر 85", "Dealer price • 85 available", "Händlerpreis • 85 verfügbar"], ["اطلب", "Order", "Befehl"]], ["C", ["منتج الفئة C", "Category C product", "Produkt der Kategorie C"], ["عرض 10+1", "10+1 offer", "10+1 Angebot"], ["عرض", "Offer", "Angebot"]]] },
    admin: { label: ["لوحة المبيعات", "Sales dashboard", "Vertriebs-Dashboard"], title: ["الأداء حسب المنطقة", "Regional performance", "Regionale Leistung"], rows: [["BG", ["بغداد", "Baghdad", "Bagdad"], ["54 طلبًا • +12%", "54 orders • +12%", "54 Bestellungen • +12 %"], ["الأعلى", "Top", "Spitze"]], ["BR", ["البصرة", "Basra", "Basra"], ["31 طلبًا • +8%", "31 orders • +8%", "31 Bestellungen • +8 %"], ["ينمو", "Growing", "Anbau"]], ["NJ", ["النجف", "Najaf", "Nadschaf"], ["22 طلبًا • ثابت", "22 orders • stable", "22 Bestellungen • stabil"], ["مستقر", "Stable", "Stabil"]]] },
    stats: [["27", ["وكيلًا نشطًا", "active dealers", "aktive Händler"]], ["142", ["طلبًا شهريًا", "monthly orders", "monatliche Bestellungen"]], ["94%", ["توفر المخزون", "stock availability", "Lagerverfügbarkeit"]]], flow: [["يرسل الوكيل", "Dealer submits", "Händler reicht ein"], ["يُراجع الائتمان", "Check credit", "Bonität prüfen"], ["يُحجز المخزون", "Reserve stock", "Reservebestand"]], tone: "cyan",
  },
  startups: {
    brand: ["نسخة أولى", "First Version", "Erste Version"], headline: ["نسخة أولية (MVP) تختبر أهم رحلة قبل التوسع", "An MVP prototype that tests the core journey", "Ein MVP-Prototyp, der die Kernreise testet"], description: ["فرضية واضحة، وميزات أساسية، ومؤشرات للتعلّم.", "Clear hypothesis, essential features and learning signals.", "Klare Hypothese, wesentliche Merkmale und Lernsignale."], action: ["شغّل تجربة النسخة الأولية", "Run MVP experiment", "Führen Sie ein MVP-Experiment durch"], result: ["سُجّل تفاعل خيالي في لوحة التعلّم", "Fictional interaction recorded in the learning board", "Auf der Lerntafel aufgezeichnete fiktive Interaktion"],
    client: { label: ["النموذج الأولي", "Prototype", "Prototyp"], title: ["التجربة الأساسية", "Core experience", "Kernerfahrung"], rows: [["01", ["اكتشف القيمة", "Discover value", "Entdecken Sie den Wert"], ["رسالة واحدة واضحة", "One clear promise", "Ein klares Versprechen"], ["مفهوم", "Clear", "Klar"]], ["02", ["جرّب الميزة", "Try the feature", "Probieren Sie die Funktion aus"], ["أقل عدد من الخطوات", "Fewest possible steps", "Wenigste mögliche Schritte"], ["نشط", "Active", "Aktiv"]], ["03", ["أرسل رأيك", "Share feedback", "Feedback teilen"], ["سؤالان فقط", "Only two questions", "Nur zwei Fragen"], ["سريع", "Quick", "Schnell"]]] },
    admin: { label: ["لوحة التعلم", "Learning board", "Lerntafel"], title: ["ماذا تعلمنا؟", "What did we learn?", "Was haben wir gelernt?"], rows: [["H1", ["هل المشكلة مهمة؟", "Does the problem matter?", "Spielt das Problem eine Rolle?"], ["31 من 42 أكملوا الرحلة", "31 of 42 completed", "31 von 42 abgeschlossen"], ["إشارة قوية", "Strong signal", "Starkes Signal"]], ["H2", ["هل العرض مفهوم؟", "Is the offer clear?", "Ist das Angebot klar?"], ["8 أسئلة متكررة", "8 repeated questions", "8 wiederholte Fragen"], ["يحتاج تعديلًا", "Iterate", "Iterieren"]], ["H3", ["هل يعود المستخدم؟", "Will users return?", "Werden Benutzer zurückkehren?"], ["قياس الأسبوع القادم", "Measure next week", "Nächste Woche messen"], ["قيد الاختبار", "Testing", "Testen"]]] },
    stats: [["01", ["رحلة أساسية", "core journey", "Kernreise"]], ["03", ["فرضيات", "hypotheses", "Hypothesen"]], ["42", ["تفاعلًا تجريبيًا", "demo interactions", "Demo-Interaktionen"]]], flow: [["نبني الأساس", "Build core", "Kern aufbauen"], ["نقيس السلوك", "Measure behaviour", "Verhalten messen"], ["نقرر التوسع", "Decide what scales", "Entscheiden Sie, welche Skalen"]], tone: "violet",
  },
  ...expandedIndustryDemos,
};

export function getContextDemo(kind: "service" | "industry", slug: string) {
  return (kind === "service" ? services : industries)[slug];
}
