export const demoProjects = [
  { id: "store", icon: "◇", titleAr: "متجر إلكتروني عراقي", titleEn: "Iraqi online store", titleDe: "Irakischer Onlineshop", metric: "12", labelAr: "طلبًا تجريبيًا", labelEn: "demo orders", labelDe: "Demo-Bestellungen", statusAr: "جاهز للتجهيز", statusEn: "Ready to pack", statusDe: "Bereit zur Bearbeitung" },
  { id: "clinic", icon: "✚", titleAr: "حجز عيادة", titleEn: "Clinic booking", titleDe: "Terminbuchung für Praxen", metric: "08:30", labelAr: "الموعد التالي", labelEn: "next slot", labelDe: "nächster Termin", statusAr: "تم التأكيد", statusEn: "Confirmed", statusDe: "Bestätigt" },
  { id: "restaurant", icon: "◒", titleAr: "طلبات مطعم", titleEn: "Restaurant orders", titleDe: "Restaurantbestellungen", metric: "7", labelAr: "طلبات قيد التحضير", labelEn: "orders cooking", labelDe: "Bestellungen in Zubereitung", statusAr: "قيد التحضير", statusEn: "In kitchen", statusDe: "In Zubereitung" },
  { id: "sales", icon: "▦", titleAr: "متابعة مبيعات", titleEn: "Sales tracking", titleDe: "Vertriebsübersicht", metric: "24", labelAr: "فرصة نشطة", labelEn: "active leads", labelDe: "aktive Kontakte", statusAr: "متابعة اليوم", statusEn: "Due today", statusDe: "Heute fällig" },
  { id: "maintenance", icon: "⌑", titleAr: "طلبات صيانة", titleEn: "Maintenance requests", titleDe: "Wartungsanfragen", metric: "5", labelAr: "طلبات مفتوحة", labelEn: "open requests", labelDe: "offene Anfragen", statusAr: "تم تعيين الفني", statusEn: "Technician assigned", statusDe: "Techniker zugewiesen" },
  { id: "crm", icon: "◎", titleAr: "متابعة العملاء", titleEn: "Customer follow-up", titleDe: "Kundennachverfolgung", metric: "68%", labelAr: "معدل المتابعة", labelEn: "follow-up rate", labelDe: "Nachverfolgungsquote", statusAr: "تذكير تلقائي", statusEn: "Auto reminder", statusDe: "Automatische Erinnerung" },
  { id: "workflow", icon: "↯", titleAr: "مسار أتمتة", titleEn: "Automation workflow", titleDe: "Automatisierter Ablauf", metric: "6", labelAr: "خطوات مترابطة", labelEn: "connected steps", labelDe: "verbundene Schritte", statusAr: "يعمل في الوضع التجريبي", statusEn: "Demo running", statusDe: "Demo läuft" },
] as const;
