import type { Locale } from "./siteSettings";

type LegalSection = { title: Record<Locale, string>; paragraphs: Record<Locale, string[]> };
export type LegalDocument = { slug: string; title: Record<Locale, string>; summary: Record<Locale, string>; sections: LegalSection[] };

const review = {
  ar: "هذه مسودة تشغيلية أُعدّت للمراجعة، وليست استشارة قانونية. يجب أن يراجعها مختص قانوني ألماني، وأن تُستكمل الحقول المؤقتة، مع الاستعانة بمختص عراقي عندما ينطبق القانون العراقي، قبل الإطلاق أو التعاقد.",
  en: "This is an operational draft for review, not legal advice. A German legal professional—and Iraqi counsel where Iraqi law applies—must review it and complete all placeholders before launch or contracting.",
};

export const legalSources = [
  { label: "§ 5 DDG", url: "https://www.gesetze-im-internet.de/ddg/__5.html" },
  { label: "Art. 13 GDPR", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679" },
  { label: "§ 25 TDDDG", url: "https://www.gesetze-im-internet.de/ttdsg/__25.html" },
  { label: "§ 312g BGB", url: "https://www.gesetze-im-internet.de/bgb/__312g.html" },
  { label: "EGBGB withdrawal model", url: "https://www.gesetze-im-internet.de/bgbeg/anlage_1.html" },
  { label: "Iraqi Ministry of Justice — electronic transactions implementation instructions", url: "https://moj.gov.iq/upload/pdf/4826_compressed_659.pdf" },
];

const commonIdentity = {
  title: { ar: "هوية مزوّد الخدمة", en: "Service provider identity" },
  paragraphs: {
    ar: ["مزوّد الخدمة والطرف المتعاقد هو Omar Al‑Ezzi (عمر العزي)، ويُدار تنفيذ الخدمات من دوسلدورف، ألمانيا. لا تزال بيانات الاسم التجاري والشكل القانوني والبريد والرقم الضريبي الواجب نشره حقولًا مؤقتة تحتاج إلى التحقق.", "لا يعني استهداف السوق العراقي وجود شركة أو مكتب أو ممثل متعاقد في العراق."],
    en: ["The service provider and contracting party is Omar Al‑Ezzi, operating from Düsseldorf, Germany. The trading name, legal form, business email and any tax identifier that must be published remain subject to verification.", "Serving the Iraqi market does not imply a company, office or contracting representative in Iraq."],
  },
};

export const legalDocuments: LegalDocument[] = [
  { slug: "impressum", title: { ar: "معلومات مزوّد الخدمة / Impressum", en: "Provider information / Impressum" }, summary: review, sections: [commonIdentity, { title: { ar: "بيانات الاتصال", en: "Contact details" }, paragraphs: { ar: ["العنوان: Vautierstr. 57, 40237 Düsseldorf, Germany.", "البريد: [NEW_BUSINESS_EMAIL] — الهاتف: [TO_BE_ADDED]. يجب استكمال وسيلة اتصال إلكترونية فعّالة قبل الإطلاق.", "الشكل القانوني: [VERIFY]. رقم USt-IdNr. أو Wirtschafts-Identifikationsnummer: [VERIFY IF AVAILABLE]. لا تُنشر Steuernummer تلقائيًا."], en: ["Address: Vautierstr. 57, 40237 Düsseldorf, Germany.", "Email: [NEW_BUSINESS_EMAIL] — phone: [TO_BE_ADDED]. A working electronic contact method must be added before launch.", "Legal form: [VERIFY]. VAT or business identification number: [VERIFY IF AVAILABLE]. A German tax number is not published automatically."] } }, { title: { ar: "أساس المسودة", en: "Draft basis" }, paragraphs: { ar: ["تستند حقول معلومات مزوّد الخدمة إلى § 5 DDG، الذي يطلب إتاحة الاسم والعنوان ووسيلة اتصال إلكترونية وبيانات التسجيل أو الترخيص أو رقم USt-IdNr. عند انطباقها."], en: ["The provider fields are based on § 5 DDG, including name, address, electronic contact details and registration, authorisation or VAT identifiers where applicable."] } }] },
  { slug: "privacy", title: { ar: "سياسة الخصوصية", en: "Privacy notice" }, summary: review, sections: [commonIdentity, { title: { ar: "البيانات والأغراض", en: "Data and purposes" }, paragraphs: { ar: ["تعالج نماذج التواصل الاسم ووسيلة التواصل وبيانات النشاط ووصف المشروع والموقع التقريبي ومصدر الإحالة؛ بغرض الرد على الطلب وتقييمه والتحضير لعلاقة تعاقدية. حقل الميزانية اختياري.", "لا تُرسل الطلبات في النسخة المحلية الحالية إلى بريد إلكتروني أو نظام لإدارة علاقات العملاء (CRM) أو ممثل. عند ربط مزوّد خارجي، يجب تحديث هذه الصفحة وتوضيح هوية المزوّد ومكان المعالجة ومدة الاحتفاظ والأساس القانوني."], en: ["Contact forms process a name, contact method, business details, project description, approximate location and referral source to reply, assess the request and prepare a potential contract. Budget is optional.", "The current local version does not forward submissions to email, a CRM or representatives. This notice must be updated before any external provider is connected."] } }, { title: { ar: "الأساس والاحتفاظ والحقوق", en: "Basis, retention and rights" }, paragraphs: { ar: ["تشمل الأسس المتوقعة اتخاذ خطوات، بناءً على طلب صاحب البيانات، قبل التعاقد، وتنفيذ العقد عند إبرامه، والمصلحة المشروعة في حماية الأمن ومنع إساءة الاستخدام عند انطباقها. يجب اعتماد الأسس النهائية قانونيًا.", "مدة الاحتفاظ: [DEFINE RETENTION PERIODS]. يحق لصاحب البيانات طلب الوصول أو التصحيح أو الحذف أو التقييد أو الاعتراض أو نقل البيانات عند استيفاء الشروط، كما يحق له تقديم شكوى إلى سلطة حماية البيانات المختصة.", "لطلبات الخصوصية، استخدم [NEW_BUSINESS_EMAIL]. لا تُستخدم بيانات الطلب للتسويق من دون موافقة منفصلة."], en: ["Expected legal bases include pre-contractual steps requested by the data subject, contract performance where agreed, and legitimate interests in security and abuse prevention where applicable. Final bases require legal approval.", "Retention: [DEFINE RETENTION PERIODS]. Depending on applicable conditions, users may request access, correction, deletion, restriction, objection or portability and may complain to the competent data protection authority.", "Use [NEW_BUSINESS_EMAIL] for privacy requests. Enquiry data is not used for marketing without separate consent."] } }, { title: { ar: "النقل الدولي والممثلون", en: "International transfers and representatives" }, paragraphs: { ar: ["قد يكون العملاء في العراق بينما توجد الإدارة في ألمانيا. يجب توثيق مسارات نقل البيانات الفعلية ومزوّدي الاستضافة والبريد الإلكتروني وWhatsApp ونظام إدارة علاقات العملاء (CRM) قبل الإطلاق.", "لا تُشارك بيانات الطلب مع ممثل أو مسوّق إلا بعد تفعيل دوره فعليًا، وإبلاغ العميل، وتحديد أساس قانوني وضمانات مناسبة."], en: ["Customers may be in Iraq while operations are in Germany. Actual transfer paths and hosting, email, WhatsApp and CRM providers must be documented before launch.", "Enquiry data is not shared with a representative or marketer unless they are genuinely active, the user is informed and a legal basis and safeguards are documented."] } }] },
  { slug: "terms", title: { ar: "شروط الخدمة / AGB", en: "Terms of service / AGB" }, summary: review, sections: [commonIdentity, { title: { ar: "العرض والتعاقد", en: "Quotes and contracting" }, paragraphs: { ar: ["لا يُعدّ طلب التواصل أو التقييم الأولي قبولًا للمشروع أو سعرًا نهائيًا. ينشأ الالتزام فقط بعد اعتماد عرض مكتوب يحدّد النطاق والمخرجات والسعر والعملة والضرائب والجدول الزمني والدفعات.", "يحدّد العرض عدد جولات التعديل، ومسؤوليات العميل عن المحتوى والموافقات، والآثار المترتبة على التأخير أو تغيير النطاق."], en: ["A contact request or initial assessment is neither project acceptance nor a final price. Work begins only after a written quote defines scope, deliverables, price, currency, taxes, schedule and milestones.", "The quote defines revision rounds, the client’s content and approval responsibilities and the effect of delays or scope changes."] } }, { title: { ar: "التسليم والخدمات الخارجية", en: "Delivery and third parties" }, paragraphs: { ar: ["تُحدَّد في العقد ملكية الكود والتصميم والملفات وبيانات الدخول وفترة الدعم. وتبقى تراخيص المكتبات والخدمات الخارجية خاضعة لشروط أصحابها.", "تُعدّ خدمات النطاق والاستضافة والبريد الإلكتروني والدفع وواجهات البرمجة (API) خدمات منفصلة أو تابعة لأطراف أخرى، ولا تُضمن استمراريتها خارج نطاق التزام مكتوب."], en: ["Ownership of code, design, files, credentials and support periods is defined in the contract. Open-source and third-party licences retain their own terms.", "Domains, hosting, email, payments and APIs may be separate or third-party services and are not guaranteed beyond a written commitment."] } }, { title: { ar: "المسؤولية والقانون", en: "Liability and governing law" }, paragraphs: { ar: ["تحتاج حدود المسؤولية والقانون المختص والمحكمة المختصة إلى صياغة قانونية تلائم وجود المزوّد في ألمانيا والعملاء في العراق، ولا يجوز أن تنتقص هذه الصياغة من حقوق المستهلك الإلزامية."], en: ["Liability limits, governing law and jurisdiction need tailored legal drafting for a German-based provider serving Iraq and must not remove mandatory consumer rights."] } }] },
  { slug: "cookies", title: { ar: "سياسة ملفات الارتباط", en: "Cookie policy" }, summary: review, sections: [{ title: { ar: "الحالة الحالية", en: "Current status" }, paragraphs: { ar: ["لا تستخدم النسخة الحالية أدوات للتحليلات أو التسويق، ولا تستخدم ملفات ارتباط إعلانية. تُحفظ تفضيلات اللغة والوضع الخفيف وإجابات المعالج مؤقتًا على الجهاز فقط، باستخدام التخزين المحلي (localStorage).", "إذا أُضيفت تقنيات غير ضرورية لاحقًا، فيجب منعها قبل الحصول على الموافقة، وشرح أغراضها ومددها ومزوّديها، وجعل الرفض بسهولة القبول نفسها، وفق § 25 TDDDG وDSGVO."], en: ["The current version uses no analytics, marketing or advertising cookies. Language, lite mode and draft wizard answers are stored in localStorage on the user’s device.", "If non-essential technologies are added, they must be blocked before consent, disclosed by purpose, duration and provider, and made as easy to reject as accept under § 25 TDDDG and GDPR."] } }] },
  { slug: "withdrawal", title: { ar: "الإلغاء والتراجع", en: "Cancellation and withdrawal" }, summary: review, sections: [{ title: { ar: "متى ينطبق؟", en: "When does it apply?" }, paragraphs: { ar: ["قد يتمتع المستهلك بحق التراجع عن العقود المبرمة عن بُعد وفق القانون الألماني، وتختلف القواعد بحسب صفة العميل ونوع الخدمة ومدى تخصيصها ووقت بدء التنفيذ.", "لا يبدأ التنفيذ المبكر خلال مدة التراجع إلا بعد توثيق الطلب والموافقات والإقرارات اللازمة، حيثما تنطبق. يجب تزويد المستهلك بنموذج وتعليمات قانونية معتمدة قبل التعاقد."], en: ["A consumer may have a withdrawal right for distance contracts under German law. The result depends on customer status, the service type, customisation and when performance starts.", "Early performance during a withdrawal period requires documented instructions, requests and acknowledgements where applicable. An approved withdrawal notice and model form must be supplied before contracting."] } }] },
  { slug: "quotes", title: { ar: "شروط عروض الأسعار", en: "Quote terms" }, summary: review, sections: [{ title: { ar: "النطاق والسعر", en: "Scope and price" }, paragraphs: { ar: ["كل عرض سعر أولي وغير ملزم، ما لم يُذكر خلاف ذلك. يُثبَّت السعر النهائي بعد تحديد النطاق، ويبيّن العرض العملة والضرائب والدفعات والمخرجات والافتراضات ومدة صلاحيته.", "تُقيَّم الخصائص أو التعديلات الخارجة عن النطاق، وتُعتمد كتابيًا قبل التنفيذ."], en: ["Each quote is preliminary and non-binding unless stated otherwise. Final pricing follows scope definition and specifies currency, tax, milestones, deliverables, assumptions and validity.", "Out-of-scope features or revisions are assessed and approved in writing before implementation."] } }] },
  { slug: "digital-projects", title: { ar: "شروط المشاريع الرقمية", en: "Digital project terms" }, summary: review, sections: [{ title: { ar: "التنفيذ والقبول", en: "Delivery and acceptance" }, paragraphs: { ar: ["يحدّد العقد مراحل التصميم والبرمجة والاختبار ومراجعة العميل والقبول. لا تُعدّ المواعيد نهائية قبل تثبيت النطاق وتوفّر المحتوى والموافقات.", "تُوثَّق معايير القبول والأعطال وطلبات التغيير والنسخ الاحتياطية والحماية والصيانة وخدمات ما بعد الإطلاق بصورة مستقلة لكل مشروع."], en: ["The contract defines design, development, testing, client review and acceptance stages. Dates are not final until scope, content and approvals are confirmed.", "Acceptance criteria, defects, change requests, backups, security, maintenance and post-launch support are documented for each project."] } }] },
  { slug: "representatives", title: { ar: "بيان الممثلين والمسوقين", en: "Representative and marketer notice" }, summary: review, sections: [{ title: { ar: "الدور والتعاقد", en: "Role and contracting" }, paragraphs: { ar: ["لا يوجد ممثل نشط معروض حاليًا. أي ممثل أو مسوّق يُضاف مستقبلًا ليس الطرف المتعاقد تلقائيًا ولا يملك تقديم التزامات أو أسعار نهائية إلا بتفويض مكتوب.", "يبقى الطرف المتعاقد مزوّد الخدمة المبين في معلومات الموقع. لا تُشارك بيانات العميل مع ممثل إلا بعد توضيح ذلك ووجود أساس قانوني مناسب."], en: ["No active representative is currently listed. Any future representative or marketer is not automatically the contracting party and cannot make binding commitments or final prices without written authority.", "The contracting party remains the provider identified on this site. Customer data is shared with a representative only after disclosure and a suitable legal basis."] } }] },
  { slug: "ip-delivery", title: { ar: "الملكية الفكرية والتسليم", en: "IP and delivery" }, summary: review, sections: [{ title: { ar: "ما الذي يُسلَّم؟", en: "What is delivered?" }, paragraphs: { ar: ["قد يشمل التسليم، بحسب الاتفاق، ملفات الكود والتصميم وإعدادات الاستضافة والنطاق المسجّل باسم العميل والحسابات والوثائق والتدريب وبيانات الدخول وفترة دعم.", "تحدّد وثائق المشروع الحقوق المنقولة وتوقيت انتقالها، وتستثني حقوق الأدوات والمكتبات والخطوط والمكوّنات الخارجية المرخّصة من أصحابها."], en: ["Depending on the agreement, delivery may include code, design files, hosting configuration, a client-owned domain, accounts, documentation, training, credentials and a support period.", "Project documents define transferred rights and timing while excluding third-party tools, libraries, fonts and components governed by their own licences."] } }] },
  { slug: "legal-review", title: { ar: "إشعار المراجعة القانونية", en: "Legal review notice" }, summary: review, sections: [{ title: { ar: "عناصر معلقة", en: "Open items" }, paragraphs: { ar: ["قبل الإطلاق يجب التحقق من: الشكل القانوني، البريد والهاتف، الرقم الضريبي الواجب نشره، التسجيل أو الجهة الرقابية، سلطة حماية البيانات، سياسة الاحتفاظ، مزودي الاستضافة والبريد والنماذج، شروط الدفع والعملة، حق التراجع، القانون والمحكمة، والالتزامات العراقية السارية.", "جرى الرجوع إلى مصادر رسمية ألمانية وأوروبية وعراقية مدرجة في هذه الصفحة، لكن لا تُعد هذه المسودة اعتمادًا قانونيًا نهائيًا."], en: ["Before launch verify: legal form, email and phone, publishable tax identifier, registration or supervisory authority, data protection authority, retention, hosting/email/form providers, payment and currency terms, withdrawal rules, governing law and jurisdiction, and applicable Iraqi obligations.", "Official German, EU and Iraqi sources listed on this page were consulted, but this draft is not final legal approval."] } }] },
];
