"use client";

import { useState } from "react";
import type { Locale } from "@/src/content/siteSettings";
import { demoProjects } from "@/src/content/demoProjects";

export function DemoLab({ locale }: { locale: Locale }) {
  const [active, setActive] = useState<(typeof demoProjects)[number]["id"]>("store");
  const [pulse, setPulse] = useState(0);
  const ar = locale === "ar";
  const current = demoProjects.find(x => x.id === active) ?? demoProjects[0];
  const rows = ar ? ["طلب تجريبي #104", "طلب تجريبي #103", "طلب تجريبي #102"] : ["Demo request #104", "Demo request #103", "Demo request #102"];
  return <section id="demos" className="section demos-section"><div className="container"><div className="section-heading split"><div><span className="eyebrow">{ar ? "جرّب نموذجًا بنفسك" : "Try a demo yourself"}</span><h2>{ar ? "شاهد كيف تبدو الفكرة عندما تعمل فعليًا." : "See what the idea could feel like in action."}</h2></div><p>{ar ? "هذه نماذج توضيحية تستخدم بيانات خيالية. لا تحفظ بيانات حقيقية، ولا تنفّذ عمليات دفع أو طلبات فعلية." : "These use fictional data. They store no real information and execute no real order or payment."}</p></div><div className="demo-shell"><div className="demo-tabs" role="tablist" aria-label={ar ? "اختر نموذجًا" : "Choose a demo"}>{demoProjects.map(demo => <button type="button" role="tab" aria-selected={active === demo.id} onClick={() => setActive(demo.id)} key={demo.id}><span>{demo.icon}</span>{ar ? demo.titleAr : demo.titleEn}</button>)}</div><div className="demo-stage" role="tabpanel"><div className="demo-window"><div className="demo-bar"><span></span><span></span><span></span><b>demo.local/{current.id}</b></div><div className="demo-dashboard"><aside><div className="demo-logo">{current.icon}</div><i></i><i></i><i></i><i></i></aside><div className="demo-content"><div className="demo-title"><div><small>{ar ? "نموذج توضيحي" : "Illustrative demo"}</small><h3>{ar ? current.titleAr : current.titleEn}</h3></div><button type="button" onClick={() => setPulse(x => x + 1)}>{ar ? "شغّل تفاعلًا" : "Run interaction"}<span>↯</span></button></div><div className="demo-metrics"><article><strong>{current.metric}</strong><span>{ar ? current.labelAr : current.labelEn}</span></article><article><strong>{pulse || "03"}</strong><span>{ar ? "تحديثات اليوم" : "updates today"}</span></article><article><strong>98%</strong><span>{ar ? "بيانات مكتملة" : "data complete"}</span></article></div><div className="demo-table"><div className="table-head"><span>{ar ? "الطلب" : "Request"}</span><span>{ar ? "الحالة" : "Status"}</span><span>{ar ? "آخر تحديث" : "Updated"}</span></div>{rows.map((row, i) => <div className={pulse && i === 0 ? "table-row pulse" : "table-row"} key={row}><span><i>{current.icon}</i>{row}</span><span><b></b>{ar ? current.statusAr : current.statusEn}</span><span>{ar ? `قبل ${i + 2} د` : `${i + 2}m ago`}</span></div>)}</div></div></div></div><div className="demo-disclaimer"><span>i</span><p><b>{ar ? "هذا نموذج توضيحي، وليس مشروعًا تابعًا لعميل حقيقي." : "This is an illustrative demo—not a real client project."}</b><br />{ar ? "جميع الأسماء والبيانات خيالية، ولا تُرسل أي طلبات فعلية." : "All names and data are fictional; no action is actually submitted."}</p></div></div></div></div></section>;
}
