"use client";

import { useState } from "react";
import type { ContextDemo, DemoRow, Pair } from "@/src/content/contextDemos";
import type { Locale } from "@/src/content/siteSettings";
import { ExpandedIndustryPreview, expandedIndustrySlugs } from "@/src/components/ExpandedIndustryPreview";

type Props = { demo: ContextDemo; locale: Locale; slug: string };

export function DomainPreview({ demo, locale, slug }: Props) {
  const [step, setStep] = useState(0);
  const [selected, setSelected] = useState(0);
  const [count, setCount] = useState(0);
  const ar = locale === "ar";
  const ran = step > 0;
  const onRun = () => setStep(value => value + 1);
  const t = (pair: Pair) => pair[ar ? 0 : 1];
  const client = demo.client.rows;
  const admin = demo.admin.rows;
  const action = <button className="specialized-action" type="button" onClick={onRun}>{ran ? (ar ? "أعد التجربة ↻" : "Run again ↻") : t(demo.action)}</button>;
  const result = <div className={`specialized-result${ran ? " show" : ""}`} role="status" aria-live="polite">✓ {ran ? t(demo.result) : ""}</div>;

  const title = (r: DemoRow) => t(r[1]);
  const meta = (r: DemoRow) => t(r[2]);
  const status = (r: DemoRow) => t(r[3]);

  if ((expandedIndustrySlugs as readonly string[]).includes(slug)) return <ExpandedIndustryPreview demo={demo} locale={locale} slug={slug} />;

  if (slug === "websites") return <div className="specialized-canvas website-preview">
    <div className="website-nav"><b>{t(demo.brand)}</b><span>{ar ? "الرئيسية   خدماتنا   أعمالنا" : "Home   Services   Work"}</span><i>{ar ? "اطلب عرضًا" : "Get a quote"}</i></div>
    <div className="website-hero"><div><small>{ar ? "موقع شركة واضح وعملي" : "A clear, practical company website"}</small><h3>{ar ? "يشرح خدمتك، ثم يقود الزائر إلى إرسال طلب واضح." : "Explain the service, then guide the visitor to a clear enquiry."}</h3><p>{t(demo.description)}</p>{action}{result}</div><div className={`website-journey${ran ? " completed" : ""}`} aria-label={ar ? "رحلة الزائر من صفحة الخدمة إلى إرسال الطلب" : "Visitor journey from service page to enquiry"}><header><div><small>{ar ? "رحلة الزائر" : "Visitor journey"}</small><b>{ar ? "من الزيارة إلى طلب عمل" : "From visit to enquiry"}</b></div><span>● {ar ? "نموذج مباشر" : "Live demo"}</span></header><div className="journey-steps"><article><i>01</i><div><b>{ar ? "قرأ صفحة الخدمة" : "Viewed the service"}</b><small>{ar ? "فهم النتيجة وطريقة العمل" : "Understood the offer and process"}</small></div><em>✓</em></article><article><i>02</i><div><b>{ar ? "ملأ نموذج المشروع" : "Completed the project brief"}</b><small>{ar ? "اختار الخدمة ووصف احتياجه" : "Selected a service and described the need"}</small></div><em>✓</em></article><article className="journey-final"><i>03</i><div><b>{ar ? "وصل الطلب إلى الفريق" : "Enquiry reached the team"}</b><small>{ran ? (ar ? "الطلب التجريبي #1048 جاهز للمتابعة" : "Demo enquiry #1048 is ready for follow-up") : (ar ? "اضغط على زر التجربة لإرسال طلب وهمي" : "Use the demo button to send a fictional enquiry")}</small></div><em>{ran ? "✓" : "…"}</em></article></div><footer><span>{ar ? "النتيجة" : "Outcome"}</span><b>{ran ? (ar ? "طلب منظّم بدلًا من رسالة مبهمة" : "A structured enquiry instead of a vague message") : (ar ? "مسار واضح وقابل للقياس" : "A clear, measurable journey")}</b></footer></div></div>
    <div className="website-services">{client.map(r => <article key={r[1][1]}><i>{r[0]}</i><b>{title(r)}</b><span>{meta(r)}</span></article>)}</div>
  </div>;

  if (slug === "web-apps") return <div className="specialized-canvas app-preview">
    <aside className="app-phone"><div className="phone-top"></div><b>{ar ? "مرحبًا، سارة" : "Hello, Sara"}</b><small>{ar ? "طلباتك النشطة" : "Your active requests"}</small>{count > 0 && <article className="new-request"><i>✓</i><span><b>{ar ? `طلب تجريبي جديد ×${count}` : `New demo request ×${count}`}</b><small>{ar ? "تم إنشاؤه الآن" : "Created just now"}</small></span></article>}{client.map(r => <article key={r[1][1]}><i>{r[0]}</i><span><b>{title(r)}</b><small>{meta(r)}</small></span></article>)}<button type="button" aria-label={ar ? "إنشاء طلب تجريبي" : "Create demo request"} onClick={() => { setCount(value => value + 1); onRun(); }}>＋</button></aside>
    <div className="app-console"><header><div><small>{ar ? "لوحة التشغيل" : "Operations"}</small><h3>{t(demo.admin.title)}</h3></div><span className="live-dot">● {ar ? "مباشر" : "Live"}</span></header><div className="app-metrics">{demo.stats.map((s, index) => <article key={s[1][1]}><strong>{index === 1 ? 18 + count : s[0]}</strong><span>{t(s[1])}</span></article>)}</div><div className="app-activity">{count > 0 && <div className="new-request"><i>N</i><span><b>{ar ? "طلب جديد من التطبيق" : "New app request"}</b><small>{ar ? "وصل الآن من واجهة الهاتف" : "Just arrived from mobile"}</small></span><em>{ar ? "جديد" : "New"}</em></div>}{admin.map(r => <div key={r[1][1]}><i>{r[0]}</i><span><b>{title(r)}</b><small>{meta(r)}</small></span><em>{status(r)}</em></div>)}</div>{result}</div>
  </div>;

  if (slug === "commerce") return <div className="specialized-canvas checkout-preview">
    <div className="checkout-products"><header><div><small>{ar ? "سوق دجلة" : "Tigris Market"}</small><h3>{ar ? "اختيارات اليوم" : "Today's picks"}</h3></div><span>⌕</span></header><div>{client.map((r, i) => <article key={r[1][1]}><div className={`product-art art-${i}`}><span>{r[0]}</span></div><b>{title(r)}</b><small>{meta(r)}</small><button type="button" aria-label={`${ar ? "أضف" : "Add"} ${title(r)}`} onClick={() => { setSelected(i); setCount(value => value + 1); }}>＋</button></article>)}</div></div>
    <aside className="checkout-cart"><span className="cart-icon">◇</span><h3>{ar ? "سلة الطلب" : "Order cart"} <small>({count + 2})</small></h3><div className="cart-line"><b>{title(client[0])}</b><span>1 × 28,000</span></div><div className="cart-line"><b>{title(client[1])}</b><span>1 × 12,000</span></div>{count > 0 && <div className="cart-line new-request"><b>{title(client[selected])}</b><span>{count} × {selected === 0 ? "28,000" : selected === 1 ? "12,000" : "35,000"}</span></div>}<div className="cart-total"><span>{ar ? "المجموع التجريبي" : "Demo total"}</span><strong>{40 + count * (selected === 0 ? 28 : selected === 1 ? 12 : 35)},000 <small>{ar ? "د.ع" : "IQD"}</small></strong></div>{action}{result}</aside>
  </div>;

  if (slug === "management-systems") return <div className="specialized-canvas kanban-preview">
    <header><div><small>{t(demo.brand)}</small><h3>{ar ? "مساحة عمل الفريق" : "Team workspace"}</h3></div><button className="specialized-action" type="button" onClick={() => setStep(value => (value + 1) % 3)}>{step === 0 ? (ar ? "نقل المشروع إلى قيد التنفيذ ←" : "Move project to progress") : step === 1 ? (ar ? "نقل المشروع إلى مكتمل ✓" : "Mark project complete") : (ar ? "إعادة المشروع إلى البداية ↻" : "Reset project")}</button></header>
    <div className="kanban-board"><section><b>{ar ? "قائمة المهام" : "To do"}<i>{step === 0 ? "3" : "2"}</i></b>{step === 0 && <article className="movable-card"><span>{ar ? "مشروع" : "Project"}</span><h4>{title(client[0])}</h4><small>{meta(client[0])}</small><div className="card-actions"><button type="button" onClick={() => setStep(1)}>{ar ? "ابدأ العمل" : "Start work"}</button></div></article>}{admin.slice(0,2).map(r => <article key={r[1][1]}><span>{status(r)}</span><h4>{title(r)}</h4><small>{meta(r)}</small><div className="avatars">س　أ</div></article>)}</section><section><b>{ar ? "قيد التنفيذ" : "In progress"}<i>{step === 1 ? "3" : "2"}</i></b>{step === 1 && <article className="movable-card moved"><span>{ar ? "قيد التنفيذ" : "In progress"}</span><h4>{title(client[0])}</h4><small>{meta(client[0])}</small><div className="progress"><i></i></div><div className="card-actions"><button type="button" onClick={() => setStep(0)}>{ar ? "إرجاع إلى السابق" : "Move back"}</button><button type="button" onClick={() => setStep(2)}>{ar ? "إكمال ✓" : "Complete ✓"}</button></div></article>}</section><section><b>{ar ? "مكتمل" : "Done"}<i>{step === 2 ? "4" : "3"}</i></b>{step === 2 && <article className="movable-card completed"><span>✓ {ar ? "تم الإنجاز" : "Completed"}</span><h4>{title(client[0])}</h4><small>{meta(client[0])}</small><div className="card-actions"><button type="button" onClick={() => setStep(1)}>{ar ? "إعادة فتح المشروع" : "Reopen"}</button></div></article>}{client.slice(1).map(r => <article key={r[1][1]}><span>✓</span><h4>{title(r)}</h4><small>{meta(r)}</small></article>)}</section></div><div className="kanban-hint">{ar ? "جرّب أزرار البطاقة أو الزر العلوي لنقل المشروع بين الحالات." : "Use the card controls or top action to move the project between stages."}</div>
  </div>;

  if (slug === "booking-crm") return <div className="specialized-canvas crm-preview">
    <div className="crm-calendar"><header><button type="button" onClick={() => setCount(value => Math.max(0,value - 1))}>‹</button><div><small>{ar ? "آب 2026" : "August 2026"}</small><h3>{ar ? `اليوم المختار: ${16 + count} آب` : `Selected: ${16 + count} Aug`}</h3></div><button type="button" onClick={() => setCount(value => Math.min(4,value + 1))}>›</button></header><div className="week-strip">{["16","17","18","19","20"].map((d,i)=><button type="button" className={i===count?"active":""} onClick={() => setCount(i)} key={d}><small>{ar ? ["أح","إث","ثل","أر","خم"][i] : ["Su","Mo","Tu","We","Th"][i]}</small><b>{d}</b></button>)}</div><div className="time-slots">{client.map((r,i)=><button type="button" className={i===selected?"selected":""} onClick={() => setSelected(i)} key={r[1][1]}><b>{r[0]}:00</b><span>{meta(r)}</span><i>{i===selected ? (ar ? "مختار" : "Selected") : status(r)}</i></button>)}</div></div>
    <aside className="crm-profile"><div className="profile-head"><span>م</span><div><h3>{ar ? "مريم خالد" : "Maryam Khalid"}</h3><small>{ar ? "عميلة جديدة" : "New customer"}</small></div></div><ol><li className="done">{ar ? "تواصل أولي" : "Initial contact"}</li><li className={ran?"done":"active"}>{ar ? "حجز استشارة" : "Consultation booked"}</li><li>{ar ? "إرسال العرض" : "Send proposal"}</li></ol>{action}{result}</aside>
  </div>;

  if (slug === "automation") return <div className="specialized-canvas automation-preview">
    <header><div><small>AUTOFLOW / 204</small><h3>{ar ? "مسار معالجة طلب جديد" : "New request workflow"}</h3></div><span className={ran?"run-status active":"run-status"}>● {ran ? (ar?"اكتمل":"Completed") : (ar?"جاهز للتشغيل":"Ready to run")}</span></header>
    <div className="automation-flow">{[["✉",ar?"نموذج الموقع":"Website form",ar?"استقبال البيانات":"Capture data"],["⌁",ar?"التحقق والتصنيف":"Validate & classify",ar?"الخدمة والمحافظة":"Service & location"],["◎","CRM",ar?"إنشاء سجل":"Create record"],["↯",ar?"إشعار المسؤول":"Notify owner",ar?"إنشاء مهمة وإرسال رسالة":"Task & message"]].map((node,i)=><span className="automation-node-wrap" key={node[1]}><button type="button" className={step > i ? "automation-node complete" : step === i ? "automation-node current" : "automation-node"} onClick={() => setStep(i + 1)}><i>0{i+1}</i><span>{node[0]}</span><b>{node[1]}</b><small>{node[2]}</small></button>{i<3&&<em>→</em>}</span>)}</div>
    <div className="automation-log"><code className={step>0?"ok":""}>request.{step>0?"received":"waiting"}</code><code className={step>1?"ok":""}>validation.{step>1?"passed":"waiting"}</code><code className={step>2?"ok":""}>crm.{step>2?"created":"waiting"}</code><button className="specialized-action" type="button" onClick={() => setStep(value => value >= 4 ? 0 : value + 1)}>{step >= 4 ? (ar?"إعادة المسار ↻":"Reset workflow ↻") : (ar?`تشغيل الخطوة ${step+1}`:`Run step ${step+1}`)}</button></div>{result}
  </div>;

  if (slug === "performance-care") return <div className="specialized-canvas audit-preview">
    <aside className="audit-score"><div className={ran?"score-ring improved":"score-ring"}><strong>{ran?"96":"92"}</strong><span>{ar ? "الأداء" : "Performance"}</span></div><h3>{ar ? "صحة الموقع جيدة" : "Site health is good"}</h3><p>{ar ? "ثلاث فرص للتحسين، مرتبة حسب الأثر." : "Three opportunities ranked by impact."}</p>{action}</aside>
    <div className="audit-report"><header><h3>{ar ? "تقرير الفحص" : "Audit report"}</h3><span>A / 92</span></header>{admin.map((r,i)=><article key={r[1][1]}><div><b>{title(r)}</b><small>{meta(r)}</small></div><div className="audit-bar"><i style={{width:`${[82,64,48][i]}%`}}></i></div><em>{status(r)}</em></article>)}{result}</div>
  </div>;

  if (slug === "clinics") return <div className="specialized-canvas clinic-preview">
    <aside className="clinic-brand"><span>✚</span><b>{t(demo.brand)}</b><small>{ar ? "رعاية تبدأ بموعد واضح" : "Care starts with a clear booking"}</small><div><i>✓</i>{ar ? "لا تُحفظ بيانات صحية" : "No health data stored"}</div></aside>
    <div className="clinic-booking"><div className="clinic-step"><span>1</span><b>{ar ? "اختر الاختصاص والموعد" : "Choose speciality and time"}</b></div><div className="doctor-cards">{client.map((r,i)=><button type="button" className={i===selected?"selected":""} onClick={() => setSelected(i)} key={r[1][1]}><div className={`doctor-avatar doctor-${i}`}>{r[0]}</div><div><b>{title(r)}</b><small>{meta(r)}</small></div><em>{status(r)}</em></button>)}</div><div className="clinic-times">{["10:30","11:15","12:00","14:30"].map((time,i)=><button type="button" onClick={() => setCount(i)} className={i===count?"selected":""} key={time}>{time}</button>)}</div>{action}{result}</div>
    <aside className="clinic-summary"><small>{ar ? "ملخص الموعد" : "Appointment summary"}</small><div className="date-card"><strong>16</strong><span>{ar ? "الأحد • آب" : "Sunday • Aug"}</span></div><p><b>{title(client[selected])}</b><span>{meta(client[selected]).split("•")[0]} • {["10:30","11:15","12:00","14:30"][count]}</span></p><i>{ran ? (ar ? "✓ موعد تجريبي مؤكد" : "✓ Demo booking confirmed") : (ar ? "اختر ثم أكد الموعد" : "Choose and confirm")}</i></aside>
  </div>;

  if (slug === "restaurants") return <div className="specialized-canvas restaurant-preview">
    <header><div className="restaurant-logo">ن</div><div><small>{ar ? "قائمة اليوم" : "Today's menu"}</small><h3>{t(demo.brand)}</h3></div><div className="restaurant-chips"><span>{ar ? "الكل" : "All"}</span><span>{ar ? "مشروبات" : "Drinks"}</span><span>{ar ? "وجبات" : "Meals"}</span></div></header>
    <div className="restaurant-menu">{client.map((r,i)=><article key={r[1][1]}><div className={`dish dish-${i}`}><span>{r[0]}</span><i></i></div><small>{ar ? ["مميز","الأكثر طلبًا","طازج يوميًا"][i] : ["Signature","Popular","Fresh daily"][i]}</small><h4>{title(r)}</h4><p>{meta(r)}</p><button type="button" aria-label={`${ar?"أضف":"Add"} ${title(r)}`} onClick={() => { setSelected(i); setCount(value => value + 1); }}>＋</button></article>)}</div>
    <div className="restaurant-ticket"><div><b>#{ran?"25":"24"}</b><span>{ran ? (ar ? "أُرسل إلى المطبخ" : "Sent to kitchen") : (ar ? "جارٍ إعداد الطلب" : "Building order")}</span></div><p>{ar ? "برغر دجاج × 2" : "Chicken burger × 2"}</p><p>{count > 0 ? `${title(client[selected])} × ${count}` : (ar ? "أضف صنفًا من القائمة" : "Add an item from the menu")}</p>{action}{result}</div>
  </div>;

  if (slug === "retail") return <div className="specialized-canvas retail-preview">
    <header><b>{t(demo.brand)}</b><div className="retail-search">⌕ {ar ? "ابحث عن منتج..." : "Search products..."}</div><span>◇ <i>{count}</i></span></header><div className="retail-layout"><aside><b>{ar ? "التصنيفات" : "Categories"}</b>{[ar?"الكل":"All",ar?"المنزل":"Home",ar?"إلكترونيات":"Electronics",ar?"إكسسوارات":"Accessories"].map((x,i)=><button type="button" className={i===selected?"active":""} onClick={() => setSelected(i)} key={x}>{x}</button>)}</aside><div className="retail-products">{client.map((r,i)=><article className={selected>0 && i !== selected-1 ? "filtered" : ""} key={r[1][1]}><div className={`retail-art retail-${i}`}><span>{r[0]}</span>{i===2&&<em>{ar?"جديد":"New"}</em>}</div><h4>{title(r)}</h4><p>{meta(r)}</p><button type="button" onClick={() => { setCount(value => value + 1); onRun(); }}>{ar?"أضف للسلة":"Add to cart"}</button></article>)}</div></div>{result}
  </div>;

  if (slug === "construction") return <div className="specialized-canvas construction-preview">
    <header><div><small>{ar ? "مشروع سكني • بغداد" : "Residential project • Baghdad"}</small><h3>{t(demo.brand)}</h3></div><div className="construction-progress"><strong>{ran?"74%":"68%"}</strong><span><i style={{width:ran?"74%":"68%"}}></i></span></div></header><div className="blueprint-grid"><div className="building-shape"><span></span><span></span><span></span><i></i></div><div className="milestone-list">{client.map((r,i)=><article className={ran&&i===1?"complete":""} key={r[1][1]}><span>{r[0]}</span><div><b>{title(r)}</b><small>{meta(r)}</small></div><em>{ran&&i===1?(ar?"مكتمل":"Complete"):status(r)}</em></article>)}{action}</div><aside><b>{ar ? "قرارات مطلوبة" : "Decisions needed"}</b>{admin.slice(0,2).map(r=><p key={r[1][1]}><span>!</span>{title(r)}</p>)}{result}</aside></div>
  </div>;

  if (slug === "consulting") return <div className="specialized-canvas consulting-preview">
    <aside className="consulting-steps"><b>{ar ? "طلب مشروع جديد" : "New project brief"}</b>{[ar?"نوع المشروع":"Project type",ar?"الموقع والمساحة":"Location & area",ar?"الملفات":"Documents",ar?"المدة والميزانية":"Timing & budget",ar?"المراجعة":"Review"].map((x,i)=><span className={i<3||ran?"done":i===3?"active":""} key={x}><i>{i<3||ran?"✓":i+1}</i>{x}</span>)}</aside><div className="consulting-form"><small>{ran ? (ar ? "اكتملت الخطوات الخمس" : "Completed 5 of 5") : (ar ? "الخطوة 4 من 5" : "Step 4 of 5")}</small><h3>{ar ? "متى ترغب في بدء المشروع؟" : "When should the project begin?"}</h3><div className="consulting-options">{[ar ? "خلال شهر" : "Within a month",ar ? "خلال ثلاثة أشهر" : "Within 3 months",ar ? "غير محدد" : "Not decided"].map((option,i)=><button type="button" onClick={() => setSelected(i)} className={selected===i?"selected":""} key={option}>{option}</button>)}</div><label>{ar ? "ملاحظات إضافية" : "Additional notes"}<span>{ar ? "يمكنك توضيح الأولويات هنا..." : "Add your priorities here..."}</span></label>{action}{result}</div><aside className="brief-card"><span>⌁</span><h4>{ar ? "ملخص فوري" : "Live brief"}</h4>{client.map(r=><p key={r[1][1]}><small>{title(r)}</small><b>{meta(r)}</b></p>)}<p><small>{ar?"موعد البدء":"Start timing"}</small><b>{[ar ? "خلال شهر" : "Within a month",ar ? "خلال ثلاثة أشهر" : "Within 3 months",ar ? "غير محدد" : "Not decided"][selected]}</b></p></aside>
  </div>;

  if (slug === "travel") return <div className="specialized-canvas travel-preview">
    <div className="travel-hero"><div><small>{ar ? "اكتشف وجهتك القادمة" : "Discover your next destination"}</small><h3>{ar ? "رحلة أوضح، من البحث إلى استلام العرض." : "Clearer travel, from search to quote."}</h3></div><div className="travel-search"><span>⌖ <b>{ar ? "من بغداد" : "From Baghdad"}</b></span><span>✦ <b>{ar ? "إلى إسطنبول" : "To Istanbul"}</b></span><span>◷ <b>20 — 25 AUG</b></span><button>⌕</button></div></div><div className="travel-cards">{client.map((r,i)=><article key={r[1][1]}><div className={`destination destination-${i}`}><span>{["IST","AYT","DXB"][i]}</span><i></i></div><h4>{title(r)}</h4><p>{meta(r)}</p><div><span>★★★★★</span><button type="button" onClick={onRun}>{status(r)}</button></div></article>)}</div>{result}
  </div>;

  if (slug === "education") return <div className="specialized-canvas education-preview">
    <aside className="education-sidebar"><div className="academy-mark">خ</div><b>{t(demo.brand)}</b><nav><span className="active">▱ {ar ? "دوراتي" : "My courses"}</span><span>⌁ {ar ? "الجدول" : "Schedule"}</span><span>✓ {ar ? "الشهادات" : "Certificates"}</span></nav><div className="learner"><i>س</i><span><b>{ar ? "سارة أحمد" : "Sara Ahmed"}</b><small>{ar ? "طالبة" : "Learner"}</small></span></div></aside><div className="education-main"><header><div><small>{ar ? "تابع التعلّم" : "Continue learning"}</small><h3>{ar ? "أهلًا، سارة. لنكمل من حيث توقّفنا." : "Welcome back, Sara. Let's continue."}</h3></div><span>🔔</span></header><div className="featured-course"><div className="course-play">▶</div><div><small>{ar ? "الدورة الحالية" : "Current course"}</small><h4>{title(client[0])}</h4><p>{meta(client[0])}</p><div className="course-progress"><span><i style={{width:ran?"78%":"62%"}}></i></span><b>{ran?"78%":"62%"}</b></div>{action}</div></div><div className="lesson-row">{client.slice(1).map((r,i)=><article key={r[1][1]}><span>{i?"◎":"⌘"}</span><div><b>{title(r)}</b><small>{meta(r)}</small></div><em>{status(r)}</em></article>)}</div>{result}</div>
  </div>;

  if (slug === "maintenance") return <div className="specialized-canvas maintenance-preview">
    <div className="maintenance-map"><div className="map-road one"></div><div className="map-road two"></div><span className="map-pin customer">⌂</span><span className={`map-pin tech${ran?" arrived":""}`}>⌑</span><div className="eta"><small>{ar ? "الخدمة المختارة" : "Selected service"}</small><b>{ran ? (ar?"وصل الفني إلى الموقع":"Technician arrived") : title(client[selected])}</b></div></div><aside className="maintenance-panel"><header><span>⌑</span><div><small>{ar ? "طلب صيانة" : "Service request"}</small><h3>{ar ? "كيف نساعدك؟" : "How can we help?"}</h3></div></header><div className="service-types">{client.map((r,i)=><button className={i===selected?"selected":""} onClick={() => { setSelected(i); setStep(0); }} type="button" key={r[1][1]}><i>{r[0]}</i><span><b>{title(r)}</b><small>{meta(r)}</small></span></button>)}</div>{action}{result}</aside>
  </div>;

  if (slug === "distribution") return <div className="specialized-canvas distribution-preview">
    <header><div><small>{ar ? "شبكة المبيعات" : "Sales network"}</small><h3>{ar ? "الأداء حسب المحافظة" : "Performance by governorate"}</h3></div><div className="dist-total"><strong>{ran?"148":"142"}</strong><span>{ar ? "طلبًا هذا الشهر" : "orders this month"}</span></div></header><div className="distribution-grid"><div className="sales-chart">{admin.map((r,i)=><article key={r[1][1]}><div><b>{title(r)}</b><span>{meta(r)}</span></div><div className="bar-track"><i style={{width:`${[86,62,44][i]}%`}}></i></div><em>{status(r)}</em></article>)}{action}</div><div className="province-map"><span className="province p1">BG<strong>54</strong></span><span className="province p2">BR<strong>31</strong></span><span className="province p3">NJ<strong>22</strong></span><i></i></div><aside><b>{ar ? "تنبيهات المخزون" : "Stock alerts"}</b>{client.map(r=><p key={r[1][1]}><span>{r[0]}</span><b>{title(r)}</b><em>{status(r)}</em></p>)}{result}</aside></div>
  </div>;

  return <div className="specialized-canvas startup-preview">
    <header><div><small>MVP / EXPERIMENT 01</small><h3>{ar ? "اختبار الفرضية الأساسية" : "Core hypothesis experiment"}</h3></div><span>{ar ? "الأسبوع الثاني" : "Week 2"}</span></header><div className="startup-grid"><aside><b>{ar ? "الفرضية" : "Hypothesis"}</b><blockquote>{ar ? "يحتاج أصحاب المشاريع إلى طريقة أسرع لوصف أفكارهم." : "Business owners need a faster way to describe their idea."}</blockquote><div className="confidence"><span>{ar ? "مستوى الثقة الحالي" : "Current confidence"}</span><strong>{ran?"82%":"64%"}</strong><i><em style={{width:ran?"82%":"64%"}}></em></i></div>{action}</aside><div className="experiment-funnel">{client.map((r,i)=><article key={r[1][1]} style={{width:`${100-i*16}%`}}><span>{r[0]}</span><div><b>{title(r)}</b><small>{meta(r)}</small></div><em>{["42","36","31"][i]}</em></article>)}</div><aside className="learning-notes"><b>{ar ? "مؤشرات التعلّم" : "Learning signals"}</b>{admin.map(r=><p key={r[1][1]}><span>{r[0]}</span><b>{title(r)}</b><small>{meta(r)}</small></p>)}{result}</aside></div>
  </div>;
}
